### ISSUE TITLE
Using variables in kbd files?

### ISSUE THREAD

**Issue by precondition** [kmonad/kmonad#101]
Hello,

I was wondering whether it was possible to declare (integer) variables in the personal kbd files. My home row mods all use the same tapping term, which results in a lot of copied 170 in my code:
```clojure
(defalias
    gui_a (tap-hold-next-release 170 a lmet)
    alt_s (tap-hold-next-release 170 s lalt)
    sft_d (tap-hold-next-release 170 d lsft)
    ctl_f (tap-hold-next-release 170 f lctl)

    gui_; (tap-hold-next-release 170 ; rmet)
    alt_l (tap-hold-next-release 170 l lalt)
    sft_k (tap-hold-next-release 170 k rsft)
    ctl_j (tap-hold-next-release 170 j rctl)

    spc_nav (tap-hold-next-release 200 spc (layer-toggle nav))
)
```
I was wondering whether it would be possible to declare a new variable called `TAPPING_TERM` and assign it 170 with the possibility of being able to write `sft_k (tap-hold-next-release TAPPING_TERM k rsft)` and `spc_nav (tap-hold-next-release TAPPING_TERM+30 spc (layer-toggle nav))`.

I've tried
```clojure
(defalias
    TAPPING_TERM (170)
;; home row mods...
```
which produced the following error (same thing happens if I remove the parentheses around 170):
```
kmonad: Parse error at 19:19:
   |
19 |     TAPPING_TERM (170)
   |                   ^
Unrecognized compose-char
```
 and I've also tried:
```clojure
(defalias
    TAPPING_TERM = 170
;; home row mods...
```
which produced yet another error:
```
kmonad: Parse error at 20:6:
   |
20 |     gui_a (tap-hold-next-release TAPPING_TERM a lmet)
   |      ^
Unrecognized compose-char
```

Am I doing this wrong or is it simply not supported (yet)?

**Comment by david-janssen** [comment]
First of all: sorry for the late reply. Dealing with a complicated move :-)
Secondly: it's not supported yet.

However, it is very much in the plans.

**Comment by david-janssen** [comment]
Actually, to give some clarification: an alias is a name for a button, i.e. a valid entry in a `(deflayer)` statement. Therefore we only have variable-names for buttons at the moment, and also why it would be a little bit more difficult then 'just adding support for numbers', because we also have to adjust the contexts in which variable-dereferencing is allowed, and then add a lot of typechecking and other such constructs.

**Comment by rosshadden** [comment]
I'm sure this is a long shot because it's not a mere feature addition, but what if kmonad exposed a proper programming language instead of the current kbd lisp config? Something like Clojure or Haskell in which we could make all the variables, env-logic, functions, and imports anyone would ever want.

For example I know you can already run arbitrary coed by creating external files and executing them, but it would be really cool to define and run functions in the config.

```clojure
(defn someFn
	(notify-send "someFn" "notifying because we are doing a thing")
	(update-a-mode-or-something-in-polybar-or-whatever-like-how-vim-tells-you-the-mode-it-is-in "someFn")
	(layer-switch another-layer)
	(anotherAction))

(defsrc
	a b c d)

(deflayer default
	_ _ (someFn) _)
```

**Comment by david-janssen** [comment]
Yeah, that is very much the dream. One of my 'someday' features is to implement MAL into Haskell. That is even the reason why I moved to the lispy syntax (old version were in a very strange, homerolled format).

The other version you proposed: use Haskell to configure KMonad, is already almost possible. There are a few changes that need to be made to make it easier to skip the lispy config language, but most of the core code is written as a library, so it would be relatively straightforward to just 'write your own KMonad'. 

However, I suddenly had a few influxes of users, and they come with great ideas about different buttons, and with a lot of cross-platform issues. So this kept getting delayed for more short-term and arguably important stuff. This feature is definitely coming, but I do not know when.

**Comment by manna-harbour** [comment]
For integer constants, a work around for now could be to use a makefile and external pre-processor.

**Comment by manna-harbour** [comment]
When functions are added, it'd be nice to also be able to use the `-` syntax from `S-x` etc.

**Comment by vherrmann** [comment]
@david-janssen What do you think about using [Axel](https://axellang.github.io/) for the configuration?

**Comment by thoelze1** [comment]
> One of my 'someday' features is to implement MAL into Haskell

Do you mean that kmonad would basically become an interpreter for a (config) program written in a custom lisp?

**Comment by vherrmann** [comment]
Apparently the klang branch got removed. But the version of my local repository is old enough, so that i still have the branch.
I guess the information about the branch should still be inside of this git repo. The interesting commmit is:

>ed6d43df95d72f869eb73c435f107e335e28c55f
>Author:     David Janssen <janssen.dhj@gmail.com>
>AuthorDate: Fri Sep 11 18:28:52 2020 -0500
>Commit:     David Janssen <janssen.dhj@gmail.com>
>CommitDate: Fri Sep 11 18:28:52 2020 -0500

**Comment by david-janssen** [comment]
> Do you mean that kmonad would basically become an interpreter for a (config) program written in a custom lisp?

I was half-toying with the idea. I think that's probably too big of a solution at the moment, but I think there exists some algebra for defining buttons that is much simpler and compositional than what we're currently doing.

**Comment by david-janssen** [comment]
> @david-janssen What do you think about using Axel for the configuration?

Looking at https://github.com/axellang/axel, he seems just about as dependable as me :-). I'm not going to tinker with the language for the immediate future. But when I have dealt with 2 or 3 other big things I want to do, I'll start casting about.

**Comment by manna-harbour** [comment]
Here's a work around using a macro processor: #435.

**Comment by slotThe** [comment]
I will close this in favour of #237, so we have one issue where we can discuss some things that we want for a potential new config lang
