### ISSUE TITLE
Integrate simple if statements

### ISSUE THREAD

**Issue by arandomliz** [kmonad/kmonad#128]
The idea is the following: When press ESC I would like to reset the status of the keyboard. I.e. disable caps lock and such. 

I know that this would be possible (but hacky) using the code blocks, but I think it would be more secure when something like this would be directly integrated in the language. 

I could think of something like
```
(defalias 
   mes  #((if caps_on then CAPS else _))
)
```

**Comment by Corey-Keller** [comment]
I'd also like to voice my support for this as well. The example given is actually what I'm hoping to achieve in #278

**Comment by slotThe** [comment]
I will close this in favour of #237, so we have one issue where we can discuss some things that we want for a potential new config lang
