### ISSUE TITLE
Is chording possible?

### ISSUE THREAD

**Issue by wmertens** [kmonad/kmonad#179]
On Mac OS X I was using the original Karabiner to make a Waytools keyboard emulator. For example, when I held down D+F, then JKLI turn into cursor keys. D or F just work as normal keys otherwise, and ideally, rollover also works (typing D then F but releasing D just after F was pressed should not switch to chord mode).

Is it possible to do something like that with kmonad?

**Comment by slotThe** [comment]
You can certainly hack something together with different layers, though that's probably not what you had in mind.

To directly answer your question, there's no `(chord a b c)` functionality right now, no.  @elkowar is working on something (see #157) that would probably fit the bill though, so "maybe soon" :)

**Comment by MaxGyver83** [comment]
Yes, it's possible. I have it configured the same way but I have to hold down only the `F` key (actually I have it like that but mirrored).

**Comment by MaxGyver83** [comment]
If it's okay for you only to hold down `F` for getting the arrow keys on JKLI, this is a minimal config:

```clojure
(defcfg
  ;; Linux/Windows/MacOS specific part
  fallthrough true
)

(defsrc f j k l i)
(deflayer layer1 @f2 j k l i)
(deflayer layer2 _ lft down rght up)
(defalias f2 (tap-hold-next-release 500 f (layer-toggle layer2)))
```

**Comment by slotThe** [comment]
Ah yeah, I forgot to mention that if you only want to hold down one key
it's much easier!

**Comment by eighal** [comment]
> ```clojure
> 
> (defalias f2 (tap-hold-next-release 500 f (layer-toggle layer2)))
> ```

I've been using
` (defalias f2 (tap-next f (layer-toggle layer2)))`
to achieve the same thing ... I'm not sure what the pros and cons are of your way versus my way.

**Comment by UristMcKorobochka** [comment]
@eighal hold versions allow that:
P@f2 500 R@f2 --> nothing
non-hold version: P@f2 500 R@f2 --> f (I changed my mind, but I don't want That!)
Hold versions are generally better for that reason.

**Comment by eighal** [comment]
> @eighal hold versions allows that:
> P@f2 configured time passes R@f2 --> nothing
> non-hold version: P@f2 same time passes R@f2 --> f (I changed my mind, but I don't want That!)
> Hold versions are generally better for that reason.

Thank you!
