### ISSUE TITLE
Create reference for all available functions

### ISSUE THREAD

**Issue by slotThe** [kmonad/kmonad#210]
So far, all of the functions one can use to change key behaviour (`around`, `tap-hold-next-release`, ...) are mentioned in the [tutorial](https://github.com/david-janssen/kmonad/blob/master/keymap/tutorial.kbd).  However, it may be nice to have a sort "quick reference guide" for all functions and what they do.  This would improve discoverability considerably I think.

**Comment by salahdin-ahmed** [comment]
I think making them into a man page would be very useful. However, I think it won't be so convenient for Windows users!

**Comment by david-janssen** [comment]
I like the idea, but instead of a `man` page the central point of this documentation should be on Github somewhere. Then, if someone wants to turn this into a `man` page, be my guest.

**Comment by salahdin-ahmed** [comment]
I think this issue should be closed after b0d4bec44be459f8c7b052fe7e9a6bd09413ce34 and 22a79f4e3658fbe3f672e3696a021104afaac221.
