### ISSUE TITLE
Problems with getting the right key

### ISSUE THREAD

**Issue by premell** [kmonad/kmonad#236]
Ive been trying to get kmonad to work for a few hours now but have encounter a few problems when it comes to changing keys. I cannot figure out what output pattern so ill just list a few examples of my output
![image](https://user-images.githubusercontent.com/65544203/118116900-2981f000-b3eb-11eb-94f0-362afa2697f8.png)
Here I have 1->0 in defsrc and 1->2 in standardlayer, I never touch the 0 to the right. However it makes it so that when i press the "1" it outputs 1, and my "0" to the right it outputs 2. I dont have "1" in either of my layers yet it still manages to output "1"

Another example: 

![image](https://user-images.githubusercontent.com/65544203/118117143-8087c500-b3eb-11eb-9159-042c7142c7b1.png)
here the numbers but the special characters is acting super weird. For instance "-" -> "+", "\(" -> ")", "{" -> "Å", "@" -> " " "

I assume that this has something to do with the original keys but I cannot quite figure out the pattern or how to fix it. Is there anyway to get say literal ouput "+" or something?

**Comment by thoelze1** [comment]
Your `defsrc` should contain the keys as they appear on (as they are emitted by) the keyboard. In your first screenshot, the leftmost `0` should be a `1`

**Comment by premell** [comment]
Thank you that fixed my problem with the numbers! However I still have problems with a button pressing for example "@" or pressing "%" in one layer and "&" in another. Is this also a problem with my defsrc not being correct? I actually have it on english layout as defsrc because thats what I want but my keyboard has a swedish layout. Should I change the defsrc to the swedish layout?

**Comment by david-janssen** [comment]
> here the numbers but the special characters is acting super weird. For instance "-" -> "+", "(" -> ")", "{" -> "Å", "@" -> " " "

Are you maybe not on basic US-QWERTY? We have to stick to remapping pure key-events to other pure key-events. Lots of OSes then remap these based on internationalization standards and such.

I always suggest setting your OS to US-english, and then putting all the things you need into KMonad. Sorry that we can't give better internationalization support, but with all the different OSes and localizations that's a bit of a headache. Maybe if we ever have more manpower than pending tasks :).

**Comment by premell** [comment]
I am getting more and more confused. My physical keyboard has a swedish layout, however my localectl says everything is US
![image](https://user-images.githubusercontent.com/65544203/118154491-66fc7280-b417-11eb-9101-7159b48a983e.png)
and when I am typing I have US layout. However when I start kmonad it switches back to the swedish layout, even though my kmonad config is all in US layout. I dont understand, either localectl dosent cover all the options or kmonad somehow registers  my keyboard, which also seems really strange. 

> I always suggest setting your OS to US-english, and then putting all the things you need into KMonad. Sorry that we can't give better internationalization support, but with all the different OSes and localizations that's a bit of a headache. Maybe if we ever have more manpower than pending tasks :).

By the way, I have a lot to do right now, also I dont know that much about Kmonad yet, but whenever I am free I would be happy to write some documentation.

**Comment by david-janssen** [comment]
Happy to hear you got it working. Giving the documentation some love and attention is definitely something on our list, when time permits. Pull requests are always very welcome ;-)
