### ISSUE TITLE
Looking for help to design a logo: Submission deadline: Saturday 22-05 at 23:59:59 UTC

### ISSUE THREAD

**Issue by david-janssen** [kmonad/kmonad#239]
Now that we have a `kmonad` organization, it might be a good idea to also have a logo, perhaps a lowercase greek kappa? Happy to hear suggestions and ideas. If anyone is willing to play around and make us one, that would be cool too.

**Comment by vherrmann** [comment]
What do you think about those two?
![kappa](https://user-images.githubusercontent.com/50072577/118182867-c3708980-b439-11eb-9df7-87cee2221f5e.png)
![kappa1](https://user-images.githubusercontent.com/50072577/118182869-c4a1b680-b439-11eb-818d-8c66257d1a03.png)

**Comment by molleweide** [comment]
I like the first one. It's nice to look at.

**Comment by Rougemoot** [comment]
I'd love something behind the kappa to remind of the chip on QMK's logo, as a nod to the project that inspired kmonad (iirc?)

**Comment by molleweide** [comment]
> I'd love something behind the kappa to remind of the chip on QMK's logo, as a nod to the project that inspired kmonad (iirc?)

Yes! And i also think the color should be uniform and not gradient on both. I think it would look more solid with a single color.

**Comment by david-janssen** [comment]
I like the letter a lot, especially the first one. I also think it would look better with either a uniform color, or a gentle gradient that is the same across all three components of the symbol, so it looks more like 1 letter instead of 3 entities. Maybe something in a dark blue?

(Hahaha, feeling very picky now :-). Most importantly: thank you for your effort! This is already 85% of the way there, so well done! Looking forward to what you come up with).

**Comment by vherrmann** [comment]
I remade the pngs into svgs and used the qmk background:
https://m0rtis.com/nextcloud/s/BwPbpi3pqK2JYZM

**Comment by david-janssen** [comment]
I like the background idea. I have just checked in with the QMK people to make sure they wouldn't mind :-)

https://github.com/qmk/qmk_firmware/issues/12896

**Comment by vherrmann** [comment]
Another idea i just got, is to use a keycap instead of a chip

**Comment by david-janssen** [comment]
It might be hard to represent a keycap in 2D? On the other hand, if you manage to represent it in such a way that it looks like a key with a Kappa on the key (not superimposed on the image) that might look really cool.

I think the real issue here is: I know nothng of graphic design.

**Comment by vherrmann** [comment]
> I think the real issue here is: I know nothng of graphic design.
Same xD

**Comment by molleweide** [comment]
u

> I like the letter a lot, especially the first one. I also think it would look better with either a uniform color, or a gentle gradient that is the same across all three components of the symbol, so it looks more like 1 letter instead of 3 entities. Maybe something in a dark blue?

yes!!!

**Comment by vherrmann** [comment]
I just uploaded another attempt (logo-uniform.svg)

**Comment by molleweide** [comment]
cool! yeah now i think it is more about subtleties as david said because it is starting to look real pro now!! f

**Comment by vherrmann** [comment]
I made another attempt with a slight gradient (logo-slight-gradient.svg)

**Comment by david-janssen** [comment]
> „Learning by doing“

Hey, that's how I learned Haskell! :-)

So, looking at logo-uniform, my detail-focused side came out, and here are my views:
- I like the shapes
- I still think that the 2 colors in the kappa make it look like 'lk' instead of a single letter kappa. Either the same color, or a horizontal gradient from darker to lighter that continues (i.e., 1 gradient of which the K is a cutout, not 2 separate gradients for the left-stick and the right sticks), or maybe simply as is but with closer colors. Many solutions possible, but would be cool if they seemed more part of a single entity.
- I like the colors, but now the colors of the K are dark, and so is the background. Making the background lighter would make it fade into an actual white background, so instead, we could severely lighten the dark-gray of the chip, and then add a think black stroke around both the edge of the chip, and maybe, (experiment) the letter itself.
- Finally, it might make sense to experiment with a slight stroke around the branches of the chip as well.

What do you think?

**Comment by david-janssen** [comment]
Ooh, just saw the slight gradient. I like it, but it still suffers a little bit from LK-syndrome. Much better already

**Comment by molleweide** [comment]
> LK-syndrome

yes if I squint my eyes then it becomes how I want it.

**Comment by vherrmann** [comment]
What do you think about ![key2-uniform](https://user-images.githubusercontent.com/50072577/118319821-997f9b80-b4fb-11eb-87e3-6bc76cef6b13.png)

**Comment by molleweide** [comment]
This one is really cool actually. Here I also like the double colors more. However, I feel that the dark color could be tweaked a little bit maybe. The keycap looks great IMO. Feels retro.

**Comment by Rougemoot** [comment]
To be honest that feels quite outdated to me, no offence. The combination of colors looks very Word97 to me, and the "3d" effect as well.

Also, why are we not going for [this lowercase kappa symbol](https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Greek_lowercase_kappa_variant.svg/1054px-Greek_lowercase_kappa_variant.svg.png)? To me it looks much cooler

**Comment by molleweide** [comment]
> Also, why are we not going for [this lowercase kappa symbol](https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Greek_lowercase_kappa_variant.svg/1054px-Greek_lowercase_kappa_variant.svg.png)? To me it looks much cooler

That's also a good idea.

**Comment by molleweide** [comment]
fu

> What do you think about

it could be cool if the background of the button is in some kind of dark purple and the symbol
in some kind of yellow or neon pink.

**Comment by Rougemoot** [comment]
Keeping with the "inspired by QMK" theme but deviating a *bit* from their actual logo to avoid confusion, I also thought that since QMK's logo background is a chip, because it's hardware, since kmonad is its software counterpart it might be nice to replace it with something representing software, maybe a terminal with a big kappa on it, in the same style as the QMK logo.

**Comment by david-janssen** [comment]
Not a fan of the green, myself. The lower-case kappa looks cool, but also looks like a stylized `n`.

I've heard back from the guys in QMK, they're fine with us using a chip-background if we want to, but they would like it to be clearly distinquishable from theirs, since they use it (without the foreground letter) in a lot of documentation.

I'm starting to feel bad that there's one guy trying a bunch of stuff and us standing there telling him what we don't like about it. As long as you are happy making adjustments and trying stuff, I want you to know it's very cool. However, if you're getting annoyed at the process, I'd also be happy to be the one that generates stuff. Are you using inkscape files?

**Comment by vherrmann** [comment]
> As long as you are happy making adjustments and trying stuff, I want you to know it's very cool. However, if you're getting annoyed at the process, I'd also be happy to be the one that generates stuff.

It's fine, i find it interesting, how to learn about inkscape.

> Are you using inkscape files?

inkscape files are just svgs

**Comment by david-janssen** [comment]
> inkscape files are just svgs

Oohh yeah, it's GIMP that has their own project files. 

> i find it interesting

Happy to hear, looking forward to your next creation

**Comment by elkowar** [comment]
We're setting up the discord server as agreed upon in #242 right now, and we do need a logo for that. Given that none has been agreed upon _yet_, is it okay if we used the first proposal by @vherrmann for now, until something concrete has been decided? I personally really like that one, and we'll of course change it once an official logo has been chosen.
(This is also asking you @vherrmann for permission to use that icon for now ^^)

**Comment by vherrmann** [comment]
@elkowar : Of course you can use it.

**Comment by vherrmann** [comment]
I think generally i would license those pictures with CC-BY-SA :).

**Comment by david-janssen** [comment]
@elkowar That sounds like a good solution.

**Comment by vherrmann** [comment]
A few new ideas:

![bitmap](https://user-images.githubusercontent.com/50072577/118363250-c1224280-b593-11eb-8488-37f6cece8c4f.png)
![bitmap](https://user-images.githubusercontent.com/50072577/118363325-1e1df880-b594-11eb-9c1b-c487a0bbd3a7.png)

**Comment by molleweide** [comment]
> A few new ideas:
> 
> ![bitmap](https://user-images.githubusercontent.com/50072577/118363363-4c9bd380-b594-11eb-9b1d-2edc07adc6a8.png)
> ![bitmap](https://user-images.githubusercontent.com/50072577/118363376-6806de80-b594-11eb-9ee3-482b73bed6f7.png)
> 
> (logo*-terminal-uniform.svg)

these are also really nice. I like the second one because the symbols feel a bit to separated on the first one.  

also, because the dollar sign is in another font style it could make sense to make it a bit smaller also. or test layering the dollar behind so it becomes a stack of three? anyways, I'm thinking aloud. Nice work.

**Comment by Rougemoot** [comment]
Not a fan of the dollar thing.
To be honest I’ve grown quite fond of [this one](https://github.com/kmonad/kmonad/issues/239#issuecomment-840811188) (on the top). It just needs a background, maybe (no but maybe not, even). I like the gradient and the colors. Maybe you could just “glue” the letters together, as David suggested.

**Comment by 6gk** [comment]
The one 3 comments above is too terminal-y to me.

Admittedly I can't do design, but I think maybe a mix between a keyboard & the haskell logo might be worth considering?

The one that seems to be trending is ok, but the way colour is used there feels a bit weird - I might play around with it later.

**Comment by david-janssen** [comment]
I also think that the smooshed-together shape is nicer than the more-separate shape. I actually like the dollar-sign one, especially the first one. The only thing I would change is to make the $ and K occur at the same height. 

Or if the $ isn't to your liking anymore, we could do a `K:` although that looks a bit windows-drivey :p

I'm going to let people experiment with this for a week. Come up with the craziest ideas. Then in a week, we'll take a poll. Happy to be 100% democratic about this, unless clearly and obnoxiously vulgar (like poop or swastikas). (Now I hope this doesn't turn into a Boaty McBoatface type deal, because if you guys vote silly, we're gonna have a silly logo).

Deadline announced: Saturday the 22nd at midnight, UTC, at which point submissions will be frozen.

(Also, we can always redo the logo in half a years time or so. If Firefox proved anything, it's that).

**Comment by vherrmann** [comment]
@6gk @Rougemoot @molleweide 
![kappa-together-uniform](https://user-images.githubusercontent.com/50072577/118370144-a86f5800-b5a6-11eb-8d09-104f04ec00fa.png)

**Comment by 6gk** [comment]
Oh I like that version (top) more.

I think the top line bit on the K is a bit too thin, and the connection between the | and < is a bit weak, but nice.

(also not really a fan of the overhang in the top-right)

**Comment by vherrmann** [comment]
@david-janssen @molleweide  Another few attempts
![logo2-terminal-flat](https://user-images.githubusercontent.com/50072577/118370653-fbe2a580-b5a8-11eb-9e2b-c2bb29987454.png)
![bitmap](https://user-images.githubusercontent.com/50072577/118370678-1d439180-b5a9-11eb-8873-a74bf192deae.png)
![bitmap](https://user-images.githubusercontent.com/50072577/118370720-511eb700-b5a9-11eb-90b0-b6be09ef3f03.png)

**Comment by 6gk** [comment]
![image](https://user-images.githubusercontent.com/40295114/118370975-96fd6e80-b5ed-11eb-91af-e9ae586694cf.png)

Been messing around with a few things on discord.

**Comment by vherrmann** [comment]
@6gk I like the first one

**Comment by vherrmann** [comment]
@6gk 
![kappa-together-uniform4](https://user-images.githubusercontent.com/50072577/118371191-bd021f00-b5ab-11eb-931f-ba79e4946a62.png)
![kapp-together-uniform3](https://user-images.githubusercontent.com/50072577/118371192-bd9ab580-b5ab-11eb-9c19-953174b93d40.png)

**Comment by 6gk** [comment]
First one being the top-left one?  Imo it's a bit too busy & the onion rings could have been done *wayy* better.

> Although i think the κ isn't centered

Very likely, I added the circle/square last-minute just to make sure they conformed to both circular and square icons.

**Comment by 6gk** [comment]
@vherrmann Yess I much prefer the thickness on the new top one, and it does seem to be connected better.  Nice :+1:

**Comment by david-janssen** [comment]
Aaaaaaahhh, competition breeds creativity. I'm starting to really like the looks of a lot of these.

**Comment by Rougemoot** [comment]
@vherrmann I really like that, though I loved the "inverted gradient" thing in the original (having the gradient in different directions for the two shapes)

**Comment by molleweide** [comment]
fu

> ![image](https://user-images.githubusercontent.com/40295114/118370975-96fd6e80-b5ed-11eb-91af-e9ae586694cf.png)
> 
> Was messing around with a few things on discord, might as well post here too.
> 
> top-left: too "70s wacky hypnosis", made with onion in mind
> 
> bottom-left: edited version of that to be less so
> 
> bottom-right: tried to do a keyboard with some haskell things, eh

i like the pink border. i prefer when the first L-component is shifted down as in the earlier ones.

**Comment by molleweide** [comment]
> i prefer when the first L-component is shifted down as in the earlier ones.

or i'm not sure actually but the quirky ness that occurs when the L component is pulled down a bit is nice.

**Comment by thoelze1** [comment]
> bottom-left: edited version of that to be less so

Great job! I just realized that with some adjustments, the `<` part of the `K` could be made to look like the `>` part of the Haskell logo! Could be a cool way to reflect Haskell in the logo

**Comment by 6gk** [comment]
@thoelze1 Honestly that's a very interesting idea, I might play around with it tomorrow.

**Comment by vherrmann** [comment]
Another few changes:
![kappa-circle](https://user-images.githubusercontent.com/50072577/118375281-26405d00-b5c1-11eb-931e-2a7837cf1286.png)
![kapp-together-uniform5](https://user-images.githubusercontent.com/50072577/118375282-26d8f380-b5c1-11eb-9bab-971c2c114630.png)
![kapp-together-uniform6](https://user-images.githubusercontent.com/50072577/118375283-27718a00-b5c1-11eb-832e-2ca58caa2e1e.png)

**Comment by vherrmann** [comment]
And another one:
![kapp-together-uniform7](https://user-images.githubusercontent.com/50072577/118375677-859f6c80-b5c3-11eb-835d-3ae4bd66bda1.png)

**Comment by premell** [comment]
Hear me out guys. What if we made like a circle of a keyboard and put the K in the middle
![image](https://user-images.githubusercontent.com/65544203/118375998-a9fc4880-b5c5-11eb-85aa-12d327c9b387.png)
Kind of like this but with a keyboard instead. And then maybe have the QMK strips out from the middle of the circle? Someone said above that we should make the QMK logo but more software focused and I personally think squre=hardware, circle=software

**Comment by david-janssen** [comment]
Please do make sure that any images you use are copyright free. And be aware that anything non-svg will not scale well.

**Comment by vherrmann** [comment]
I removed the line between | and <:
![kappa-together-uniform8](https://user-images.githubusercontent.com/50072577/118376321-a10c7680-b5c7-11eb-86d6-91354a7c4664.png)
![kappa-together-uniform9](https://user-images.githubusercontent.com/50072577/118376322-a10c7680-b5c7-11eb-87df-c23f925ad749.png)

**Comment by elkowar** [comment]
I godda say, still like the very first one the most by far ^^' although these new ones are also nice! Not a fan of the borders though, tbh. Looks a bit too childish imo

**Comment by david-janssen** [comment]
Ok, so here is my own crazy idea that I haven't got the inkscape skill to produce quickly. Maybe someone does, and is inspired by my thought, and if not, maybe I'll get around to it before the deadline, maybe not, but, here it is:

The egyptian hieroglyph for 'K' looks alot like a teacup:
http://www.mummies2pyramids.info/images/letter-k-hieroglyphic.png

The greek symbol for monad is a circle with a dot:
https://en.wikipedia.org/wiki/Monad_(philosophy)

So what if we make it look like a sun rising out of a teacup, maybe emerging like 70% or so, so that the dot is visible.

It would be something very different than greek letters, and might be fun. I already managed to find an egyptian K-glyph in svg on the internets in no time. But then I started trying to make a circle and 'cut of the bottom' and  I realized that I know *nothing* of this stuff.

**Comment by vherrmann** [comment]
@david-janssen 

Want to make a trade? Bc I have some questions regarding haskell…

**Comment by david-janssen** [comment]
> Bc I have some questions regarding haskell… (or rather, at the moment one specific question)

Happy to help, even without the trading aspect :). I'll pop into discord, where I'm assuming you're at.

**Comment by vherrmann** [comment]
@david-janssen Can you send your files? I seem to be unable to find a svg of the k hieroglyphic…

**Comment by 6gk** [comment]
I spent a bit more time messing with @vherrmann's logo

## 1

![image](https://user-images.githubusercontent.com/40295114/118387575-86d3a680-b662-11eb-80d2-1b64e6b1fbb0.png)

## 2

![image](https://user-images.githubusercontent.com/40295114/118387581-8cc98780-b662-11eb-9353-af9a0889f0e9.png)

## 3

![image](https://user-images.githubusercontent.com/40295114/118387593-94892c00-b662-11eb-8946-262398085e71.png)

## 4

![image](https://user-images.githubusercontent.com/40295114/118387595-981cb300-b662-11eb-83a7-af22b10418dd.png)

**Comment by david-janssen** [comment]
Managed to extract it from here: https://www.freepik.com/free-vector/hand-drawn-egyptian-hieroglyphics-background_2720638.htm#page=1&query=hieroglyph&position=8

If we choose to use it we should put an attribution somewhere in the documentation.
[egyptian_k.tar.gz](https://github.com/kmonad/kmonad/files/6488812/egyptian_k.tar.gz)

**Comment by premell** [comment]
![image](https://user-images.githubusercontent.com/65544203/118394692-7ca3af00-b646-11eb-8918-c999b46df4be.png)
Something like this is what i meant with the keyboard circle with a K in the middle. Although this is kinda rough as I dont know how to use gimp

**Comment by 6gk** [comment]
Oh, and to be clear, in the designs I posted earlier the background circle/square were just to see how it fits for person reference, I subconsciously block them out and therefore forgot to remove them when posting.

**Comment by molleweide** [comment]
> Oh, and to be clear, in the designs I posted earlier the background circle/square were just to see how it fits for person reference, I subconsciously block them out and therefore forgot to remove them when posting.

Overall I like the first two a lot but not quite there yet. something feels bit off dunno what exctly

**Comment by molleweide** [comment]
> I removed the line between | and <:
> ![kappa-together-uniform8](https://user-images.githubusercontent.com/50072577/118376321-a10c7680-b5c7-11eb-86d6-91354a7c4664.png)

I like with the gap more.

**Comment by thoelze1** [comment]
Haskell meets QMK

<img width="300" alt="kmonad" src="https://user-images.githubusercontent.com/18474102/118651992-046ff180-b7de-11eb-84ff-698eefaf987e.png">

**Comment by Vermoot** [comment]
ooh, that's pretty nice!

**Comment by david-janssen** [comment]
Seconded! Super cool!

**Comment by thoelze1** [comment]
![kmonad2](https://user-images.githubusercontent.com/18474102/118655230-3cc4ff00-b7e1-11eb-9cdf-46af0474d6ac.png)

**Comment by Vermoot** [comment]
I much prefer the first one. Having a square-ish logo makes many things easier, and i really don't like the Haskell colors

**Comment by david-janssen** [comment]
I also like the first a lot more, the second one feels like we have a tick on our K. That was the first association that popped in my head :). I, however, do like the Haskell colours.

**Comment by molleweide** [comment]
how about keeping haskell colors, which i also kinda like, but with a lighter background. Maybe light brown/beige or light green, or whatever else that makes a better contrast and feels nice.

or my maybe only keep the haskell K, which is pretty cool., and then having a nice background on a future landing page that complinets the two shades of purple/pink.

**Comment by molleweide** [comment]
or add one more left arrow to the k, like `K<<`.

**Comment by 6gk** [comment]
> and i really don't like the Haskell colors

Of course the gruvbox user has a bad taste in colours :)

> I, however, do like the Haskell colours.

quite agree

**Comment by david-janssen** [comment]
> Of course the gruvbox user has a bad taste in colours :)

I like gruvbox too...

**Comment by MaxGyver83** [comment]
> <img width="300" alt="kmonad" src="https://user-images.githubusercontent.com/18474102/118656551-86fab000-b7e2-11eb-898d-71fd80e5b43a.png">

This is my favourite so far. But I also think a little bit more contrast would be nice. And I'm not sure if people understand why there is a chip in the background. But I don't know how we could symbolize software instead of the QMK chip!?

**Comment by david-janssen** [comment]
Having a second look, I agree with you. A bit more contrast would be nice.

In regards to the chip, I honestly doubt anybody would seriously think about a logo more than 0.2s. As long as it looks pleasing to the eye, the fact that the nod to QMK is a bit too subtle doesn't really matter.

**Comment by 6gk** [comment]
I quite like the simple `K<` present on the haskell-coloured QMK-clone logo, not as sure about the background chip though.

**Comment by david-janssen** [comment]
So, the submission deadline is coming up, here is how things are going to go (and typing this out I realized I haven't thought this out well).

Everyone gets to upload 1 logo to: #263

- Submission opportunities will be closed on Tuesday evening.
- The logo need-not have occured in this thread (which means that the submission deadline for this thread was pointless, which I've just realized)
- Please name your submission, something short and representative, like "Purple Baseball K"

On wednesday morning I will open voting, at which point everyone gets to submit to the voting thread a post with their sequential "Top 3 picks". Like this:
1. Purple baseball K
2. Haskell K on chip
3. Teacup with sun
Here the names have to line up with the names assigned to the submissions in #263

Counting works like this:
- If a logo wins a majority of first-preference votes (>50%) that logo is chosen
- If not, we eliminate the logo with the *least* amount of 1st preference votes, exposing the 2nd preference of those who voted for it.
- Rinse and repeat until we have a majority
- If at the end of all that we still don't have a majority, I pick from the remaining logos.

NOTE: If you choose to submit a logo to the candidates thread, that logo *must be* your 1st choice. If someone else has already copied over your first-preference pick, then don't copy over a logo yourself. 

I retain veto power, but will only use it to block swastikas and anusses and the like. (The greendale flag from community keeps ghosting through my head).

**Comment by Vermoot** [comment]
@thoelze1 Don't forget to submit yours, I liked it!

@david-janssen I feel like restricting to one submission per person isn't necessary, and even maybe not a good idea. Looking at this issue and Discord, only a couple people have made logos, and some of them had multiple good submissions

**Comment by 6gk** [comment]
Not to mention, there are literally only 2 submissions atm.

**Comment by 6gk** [comment]
Also, @david-janssen what do you think is a good idea for the licensing?  

The CC licenses (CC-BY-SA 2.0 / CC-BY 4.0 / CC0) seem good, and I'd be ok with licensing mine under those (Leaving the choice up to you :upside_down_face:) - but if you know any better licenses I'm also all ears.

**Comment by david-janssen** [comment]
> only a couple people have made logos, and some of them had multiple good submissions

Maybe I wasn't clear: it's perfectly fine to submit a logo someone else has created if you intend to vote for it :-).

However, sure: go ahead! Submit whatever, because right now a choice of 2 is a bit small indeed.

**Comment by david-janssen** [comment]
Deadline extended by 1 day for reasons of confusion.

**Comment by 6gk** [comment]
> The CC licenses (CC-BY-SA 2.0 / CC-BY 4.0 / CC0) seem good, and I'm perfectly fine with releasing
> mine under whichever of those 3 you like the most, but if you know any better licenses I'm also all ears.

TLDRs of those 3 CC licenses:

**[CC0:](https://creativecommons.org/share-your-work/public-domain/cc0)** Practically public domain - no attribution required, any purpose, etc.

**[CC-BY:](https://creativecommons.org/licenses/by/4.0)** Only restriction is attribution - "You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use."

**[CC-BY-SA:](https://creativecommons.org/licenses/by-sa/4.0)** Requires attribution *and* to be under the same license - "If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original"

I guess since you haven't really thought about licenses until now, I'll go with CC-BY-SA, like @vherrmann did (https://github.com/kmonad/kmonad/issues/239#issuecomment-841636083)

**Comment by david-janssen** [comment]
> I'll go with CC-BY-SA

That sounds perfectly reasonable

**Comment by MaxGyver83** [comment]
This could be an alternative to @thoelze1's "Haskell meets QMK" with a higher contrast:

![grafik](https://user-images.githubusercontent.com/13970628/119723220-81017080-be6d-11eb-9355-a3ec4909d995.png)

But I'm not sure if the colors match well. I have submitted the original with Haskell colors. (It's not good having too many too similar candidates in a ballot.) I don't know if @thoelze1 is going to submit any of his logos.

**Comment by 6gk** [comment]
So the time is up on the ballot?  

I'll eagerly await the poll - personally I'd do a 1-week voting period.

### May the best logo win!

Good luck everybody :)

**Comment by david-janssen** [comment]
> I'll eagerly await the poll - personally I'd do a 1-week voting period.

Very good, wish granted

> This could be an alternative to @thoelze1's "Haskell meets QMK" with a higher contrast:

Correction: 'could have been'. Didn't end up in the poll thread in time. Pity, because I like that one best :D. I'll probably be rerunning this towards the end of the year, so then we can have another go.

**Comment by slotThe** [comment]
On Wed, May 26 2021 22:57, David Janssen wrote:
> Correction: 'could have been'. Didn't end up in the poll thread in
> time. Pity, because I like that one best :D. I'll probably be
> rerunning this towards the end of the year, so then we can have
> another go.

I think we can afford to be a little bit more lenient with these kinds
of things; don't you think? :)

**Comment by david-janssen** [comment]
> I think we can afford to be a little bit more lenient with these kinds of things; don't you think? :)

But, but, but... What about my POWER?

Ok, I'll copy the color-changed haskell logo over right now.
