### ISSUE TITLE
[macOS] Key getting "stuck" for a few seconds on the login screen at wake up

### ISSUE THREAD

**Issue by Vermoot** [kmonad/kmonad#241]
When I have kmonad running and I close my laptop and open it back up after a few minutes, I have to log back on (just entering my password to unlock the computer, the user session is still running).

When doing so, very often the second or third letter I type gets "stuck" and repeats for a few seconds, so then I have to delete all that's typed into the password field and type my password again.

It's not a huge problem, but it's pretty frustrating.

**Comment by thoelze1** [comment]
I've been experiencing problems at wake up too. For me, kmonad will momentarily fail to grab input and then stutter for a few keystrokes as it regrabs input. I've been putting this off because the issue hasn't been a big deal for me, but now that others are experiencing similar problems I'll add it to my list.

How are you starting kmonad?

**Comment by Rougemoot** [comment]
For now I've only ever used kmonad started manually in a terminal. Even some months ago when I used it all the time, I had the same issue, but it was also just in a terminal, I never took the time to find a proper solution to start it at boot etc

**Comment by thoelze1** [comment]
Since running kmonad as a launchd service, I have experienced fewer bugs at wake up. Perhaps if you use launchd too, you'll experience less frequent bugs or at least less severe bugs at wake up. See #105, `launchd(8)` and `launchctl(1)`

**Comment by Rougemoot** [comment]
I'll definitely try it out!

**Comment by Vermoot** [comment]
Alright so I haven't managed to make kmonad launch at login/startup like discussed yet, but I've been running it in a terminal for some time **without** `-l debug` and the issue is gone, as far as I can tell.

So the lagginess and sticking on login screen seem to be related to running kmonad with the debug option.

**Comment by david-janssen** [comment]
So, is it safe to say that this is solved, or at least, moderately alleviated, with the fix of "Don't run KMonad in maximum logging mode in the background"? Where is the output being directed when we run KMonad in the background on Mac? The only thing debug changes is just the amount of logging-data we provide to `stdout`, and if that isn't being directed somewhere sane, maybe we start building up a huge buffer of data?

**Comment by Vermoot** [comment]
This particular issue is "solved" by not using `-l debug` indeed (although it's not a matter of having it in the background, until now I've always used kmonad in a terminal, manually started).

As for the rest of your question, I can't say. I'm not too well-versed in the inner workings of kmonad on macOS.

**Comment by david-janssen** [comment]
Wait, so I'm not entirely clear on what's going on. If you run kmonad *without* `-l debug` you don't get this issue at all, but if you run it *with* `-l debug` you get this issue, even if just running KMonad in a terminal?

That's interesting, and very strange. The only thing `-l debug` changes is that it causes even simple key-events to print to the screen. Everything else is exactly the same. So maybe the fact that we are writing data to a terminal causes MacOS to pause KMonad execution for a moment while the display wakes up? Strangeness.

@thoelze1 Do you have any idea what might be going on here?

**Comment by Vermoot** [comment]
> If you run kmonad without -l debug you don't get this issue at all, but if you run it with -l debug you get this issue, even if just running KMonad in a terminal?

That's exactly it.

> So maybe the fact that we are writing data to a terminal causes MacOS to pause KMonad execution for a moment while the display wakes up?

It's very noticeable and much more consistent at wakeup, on the login screen, but it does also happen at other times, just while using the computer. I'm guessing this is during hangups, generally when I get micro-freezes or general lagginess. This *is* a 7 year-old Macbook, after all.

**Comment by david-janssen** [comment]
Then I think I'm going to close this issue, since it seems to be attributable to: 'asking my MacBook to do too many things at the same time makes it be a little slow'. I really wouldn't know how to address this :-)
