### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by premell** [kmonad/kmonad#248]
I've written some documentation for Kmonad, but wanted to check how you'd want it structured before continuing. Currently I've mostly just written stuff down without much thought, just so you could have an outline when explaining how you want the documentation to be. I wasn't quite sure how to make a pull request since there was no "Add page" button on the wiki, so  i'll just post it here for the time being. 

A few thoughts;
1. I think its good to have a getting started page that is somewhere between the example config and the user configs in complexity. A few sentences for each section but not much more than that, because I remember being quite scared when I first saw the example config because the amount of text. Also I think its good to represent how a kmonad file is structured before going into the details. 
2. I don't know that much about Kmonad yet so the documentation is quite bare boned right now. I'll try to fill it in as I learn
3. I wasn't sure how to write documentation over the functions in markdown. Right now I just put the function name in headline but this makes it quite hard to read and it makes it really have to put examples and put the arguments needed for the function
4. As I said this is just a very rough draft of the documentation because its easier for you to correct my documentation than write your own from scratch

The documentation 
# Kmonad 

## Getting started
%The defsrc really shouldn't be called 'start section', but couldn't think of a better name at the time
The layout file should consist of three things, the start section, the layout of your physical keyboard 
aswell as one or more keyboard layouts. 

The start section contains information kmonad needs to start aswell as
common settings. An example start section is 
```
(defcfg
  input  (device-file "/dev/input/by-id/usb-04d9_daskeyboard-event-kbd")
  output (uinput-sink "My KMonad output"
  cmp-seq ralt    ;; Set the compose key to `RightAlt'
  cmp-seq-delay 5 ;; 5ms delay between each compose-key sequence press

  fallthrough false
  allow-cmd true
)
```
Next the layout of your phyiscal keyboard, this should match your keyboard layout exactly, 
```
(defsrc
  grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab  q    w    e    r    t    y    u    i    o    p    [    ]    \
  caps a    s    d    f    g    h    j    k    l    ;    '    ret
  lsft z    x    c    v    b    n    m    ,    .    /    rsft
  lctl lmet lalt           spc            ralt rmet cmp  rctl
)
```
Now you can enter your own custom layout. The first layer you write will be the default layout, 
```
(deflayer myLayout
	grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab  q    w    f    p    g    j    l    u    y    ;    [    ]    \
  caps a    r    s    t    d    h    n    e    i    o    '    ret
  lsft z    x    c    v    b    k    m    ,    .    /    rsft
  lctl lmet lalt           spc            ralt rmet cmp  rctl
```
The essential parts of your kmonad.kbd file are now finished and it can be used exactly like this.
However kmonad becomes truely powerful when using multiple layers, aliases and functions. 
Aliases extend the functionality of keys and is written like
```
(defalias 
	Num (layer-switch numberLayer)
)
```
This specific alias switch layer to the numberLayer.
For more examples of functions see the functions section. 
These aliases are then accessed in the layout with "@".

```
(deflayer customColemak
	grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab  q    w    f    p    g    j    l    u    y    ;    [    ]    \
  caps a    r    s    t    d    h    n    e    i    o    '    ret
  lsft z    x    c    v    b    k    m    ,    .    /    rsft
  @num lmet lalt           spc            ralt rmet cmp  rctl
```

Example complete layout file,  (@@This should be a simple but still useful layout)
```
(defcfg
  input  (device-file "/dev/input/by-id/usb-04d9_USB-HID_Keyboard-event-kbd")
  output (uinput-sink "KMonad output")

  fallthrough true
)

(defsrc
  esc     f1   f2   f3   f4   f5   f6   f7   f8   f9   f10  f11  f12
  grv     1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab     q    w    e    r    t    y    u    i    o    p    [    ]    \
  caps    a    s    d    f    g    h    j    k    l    ;    '    ret
  lsft      z    x    c    v    b    n    m    ,    .    /    rsft
  lctl    lmet lalt           spc            ralt rmet cmp  rctl
)
 
(defalias
  ext  (layer-toggle extend) ;; Bind 'ext' to the Extend Layer
  sym  (layer-toggle symbols) ;; Bind 'sym' to Symbols Layer
)

(defalias
  cpy C-c
  pst C-v
  cut C-x
  udo C-z
  all C-a
  fnd C-f
  bk Back
  fw Forward
  £ S-3  ;;UK pound sign
)

(deflayer colemak-dh
  esc     f1   f2   f3   f4   f5   f6   f7   f8   f9   f10  f11  f12
  grv      1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab      q    w    f    p    b    j    l    u    y    ;    [    ]    \\
  @ext     a    r    s    t    g    k    n    e    i    o    '    ret
  lsft       x    c    d    v    z    m    h    ,    .    /    rsft
  lctl     lmet lalt           spc            @sym rmet _    _
)

(deflayer extend
  _        play rewind previoussong nextsong ejectcd refresh brdn brup www mail prog1 prog2
  _        f1   f2   f3   f4   f5   f6   f7   f8   f9  f10   f11  f12  ret
  _        esc  @bk  @fnd @fw  ins  pgup home up   end  menu prnt slck _
  _        @all tab  lsft lctl lalt pgdn lft  down rght del  caps _
  _          @cut @cpy @pst @pst @udo pgdn bks  f13  f14  comp _
  _        _    _              ret            _    _    _    _
)

(deflayer symbols
  _        _    _    _    _    _    _    _    _    _    _    _    _    
  _        _    _    _    _    _    _    _    _    _    _    _    _    _
  _        S-1  S-2  S-3  S-4  S-5  =    7    8    9    +    «    »    _
  _        \_   [    {    \(   S-6  *    4    5    6    -    _    _
  _          ]    }    \)   S-7  `    0    1    2    3    /    _
  _        _    _              _              _    _    _    _
)

(deflayer empty
  _        _    _    _    _    _    _    _    _    _    _    _    _    
  _        _    _    _    _    _    _    _    _    _    _    _    _    _
  _        _    _    _    _    _    _    _    _    _    _    _    _    _
  _        _    _    _    _    _    _    _    _    _    _    _    _ 
  _          _    _    _    _    _    _    _    _    _    _    _ 
  _        _    _              _              _    _    _    _
)
```

this is probably not the best way of creating a table of functions as it takes alot of space 
and its hard to make examples and show arguments

#### layer-toggle
	Activates layer while holding button

#### layer-switch
	Permanently activates layer until switching to another

#### layer-next
	Activate next button in layer

#### layer-add and layer-del
	These functions should be avoided?

### 

## Tips and tricks

Functions can be combined in dynamic ways.

For example:
```
layerSwitch (tap-hold 300 (layer-next myLayer) (layer-toggle myLayer))
```
Activates layer for next button, or when holding down, toggles a layer for multiple buttonclicks

```
dynamicCommand (tap-hold 300 a (cmd-button "echo "Hello World""))
```
Normally acts like the "a" button, but executes command when held down

%I am not sure what KMonad: X220 does
```
output (uinput-sink 
				"KMonad: X220"
        "sleep 0.2s; xset r rate 230 70; sleep 0.2s;" 
```
Set the repeat rate for your keyboard

## Special characters

In order to add special characters to Kmonad, Compose keys have to be used. 
If you're on linux and use X11:
	1. Create an .XCompose file in your home directory
	2. Add 
```
include "%L"
```
to the .XCompose file
	3. Add in the keys you want to enable in Kmonad with 
```
<Multi_key> <a> <o> : "å"
```
Where the first two letters are any combination that are currently unused and the last letter
is the one you want to enable
	4. In your kmonad file add 
%I am not sure what KMonad: X220 does
```
output (uinput-sink 
      "KMonad: X220"
      "sleep 0.5s; setxkbmap -option compose:ralt")
cmp-seq ralt
```
to your defcfg. And then you can reach the desired special key with aliases

```
(defalias
    å #(ralt a o a)
    ä #(ralt " a)
    ö #(ralt " o)
)
```
Then you can simply reach them through your layout with 

```
... @å ... 
```

**Comment by molleweide** [comment]
awesome!

**Comment by david-janssen** [comment]
> Special characters

Actually, I think the content under this heading comes mostly from an issue we're working on now, right? We have inbuilt support for tons of special characters, some of which can be found in the `tutorial.kbd`.

I do the the documentation could be loads better. I put it all in a heavily commented configuration file, but it would probably be much better in a wiki, that we we can gradually update it and collaborate more easily. Do you know if I need to take steps to make the github wiki for KMonad 'activated' or something, or can you just start putting documentation there?

**Comment by premell** [comment]
> I do the the documentation could be loads better. I put it all in a heavily commented configuration file, but it would probably be much better in a wiki, that we we can gradually update it and collaborate more easily. Do you know if I need to take steps to make the github wiki for KMonad 'activated' or something, or can you just start putting documentation there?

I think you have to activate it somehow. On the wiki page for alacritty there is an "Add page" button 
![image](https://user-images.githubusercontent.com/65544203/118377252-7244cf00-b5cc-11eb-9d60-bd2892b20522.png)
but there isn't one on Kmonad
![image](https://user-images.githubusercontent.com/65544203/118377279-986a6f00-b5cc-11eb-933f-0c4ededca637.png)
I am not sure how to fix it though. 

>Actually, I think the content under this heading comes mostly from an issue we're working on now, right? We have inbuilt support for tons of special characters, some of which can be found in the tutorial.kbd.

Yes I had problems with getting a few special characters to work so I thought I would document the solution. Which characters have you built in? Maybe I should narrow my language to emphesise that it regards to the few special characters that Kmonad do not support? 

Anyway as I said in the commit I mostly wrote down whatever came to mind. My logic was that it is way easier to remove the section of special characters than it is to write it in. And even if we dont want the section like it is, atleast we know what we dont want and can narrow down how the documentation should be written.

**Comment by david-janssen** [comment]
Figured it out, there was a setting I had to change. Wiki should now be open to anyone with a github account.
