### ISSUE TITLE
Regexp for Window name similarly to Karabiner.

### ISSUE THREAD

**Issue by cjh9** [kmonad/kmonad#249]
Is it possible to send different key outputs depending on what is the active window?

For example map alt+q => ctrl + shfit + v if in terminal, but ctrl + v in any other window.

**Comment by thoelze1** [comment]
It's not currently possible, but #136 proposes using signals as input to kmonad in order to achieve what you describe

**Comment by david-janssen** [comment]
Closing because answered correctly. Would like this to be a feature someday, but for now we are focused on tidying up what we already have.

**Comment by cjh9** [comment]
@david-janssen Understandable!
