### ISSUE TITLE
idea: how to achieve ortho feel on regular keyb

### ISSUE THREAD

**Issue by molleweide** [kmonad/kmonad#253]
edit:  I forgot to write this is not an issue but a tip. 

Shifting all keys from `b` and all the way left to `z`, one step left makes the staggered laptop keyboard feel just like an orthogonal keyboard. This also renders the old `b` key as a placeholder for whatever you want. At first this felt a bit like heresy but it is really nice.

```
;; APPLE MACBOOK KEYBOARD

`(b)` indicates where the old `b` key was.

;; (deflayer starter
;;   _    _    _    _    _    _    _    _    _    _    _    _    _
;;        XX   XX   XX   XX   XX   XX   XX   XX   XX   XX   XX   XX   XX
;;   XX   q    _    _    _    t         y    _    _    _    p    XX   XX   XX
;;   XX   _    _    _    _    _         _    _    _    _    _    XX   XX
;;   XX   z    _    _    _    b    (b)  n    _    _    _    /    XX   XX
;;   XX   XX   _    tab            spc            ret  _    XX   XX   XX
;; )
```

**Comment by vherrmann** [comment]
What exactly is the issue about?

**Comment by 6gk** [comment]
@vherrmann It seems to be about them telling other people how to change their keyboard layout, provided they have 2 keys instead of 1 long shift key (like the ISO layout).

So not an issue/request/etc, but trying to share information.

**Comment by molleweide** [comment]
yeah I edited. I forgot to write first it this is more of a tip or idea. It would be interesting to know if anyone else is doing this.

**Comment by david-janssen** [comment]
So then that does bring up the issue: Where do we put ideas like this?

I really would like to keep 'Issues' for issues, otherwise development is going to get very disorganized. I think I will look into opening up the wiki, and then people can put ideas or tips in there. Maybe we can start moving documentation there too. 

Going to close this, because not really an issue.

**Comment by vherrmann** [comment]
I don't now if somebody does it in the kmonad community, but there a few websites about it:
https://colemakmods.github.io/ergonomic-mods/angle.html
https://kennetchaz.github.io/symmetric-typing/soul.html

**Comment by david-janssen** [comment]
The wiki is now open, btw. Please do try and make it organized and structured.

**Comment by molleweide** [comment]
yeah, i should have closed it immediately myself. I have to get into that habbit. 

> I don't now if somebody does it in the kmonad community, but there a few websites about it:
> https://colemakmods.github.io/ergonomic-mods/angle.html
> https://kennetchaz.github.io/symmetric-typing/soul.html

cool, it seems I am pretty much using the angle mod then. bc I use colemakdh inside vim.

**Comment by david-janssen** [comment]
@molleweide 

Then here is a chance to practice ;)

**Comment by molleweide** [comment]
:D
