### ISSUE TITLE
Mapping met keys (windows/super) key doesn't work quite right

### ISSUE THREAD

**Issue by Jacfger** [kmonad/kmonad#254]
```
(deflayer qwerty
  grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab  q    w    e    r    t    y    u    i    o    p    [    ]    \
  @nav a    s    d    f    g    h    j    k    l    ;    '    ret
  lsft z    x    c    v    b    n    m    ,    .    /    rsft
  lctl lmet lalt           spc            ralt rmet cmp  rctl
)
(deflayer capslockmods
  _    _    _    _    _    _    _    _    _    _    _    _    _    _
  _    f17  f18  f19  f20  _    f13  f14  f15  f16  _    _    _    _
  _    lmet lalt lctl lsft _    left down up   rght _    _    @csp
  _    f21  f22  f23  f24  _    home pgdn pgup end  _    _
  _    _    _              lctl           _    _    _    _
)
```
This is my configuration. What I wanted to do is that Cap-a-f-j in pop os which would switch the workspace or something. However, for some reason the system doesn't seem to register the key press. In fact, any key binding that needs involve using the super key doesn't work very well in kmonad when switching layer is needed. (but it works when the layer isn't switched.)

**Comment by slotThe** [comment]
What do you mean "the system doesn't seem to register the key press"?  Is `xev` not showing you anything?

**Comment by Jacfger** [comment]
I actually didn't test it in ```xev``` lol. But I just did.
```
FocusOut event, serial 37, synthetic NO, window 0x3e00001,
    mode NotifyGrab, detail NotifyAncestor

FocusIn event, serial 37, synthetic NO, window 0x3e00001,
    mode NotifyUngrab, detail NotifyAncestor

KeymapNotify event, serial 37, synthetic NO, window 0x0,
    keys:  2   0   0   0   32  0   0   0   0   0   0   0   0   0   0   0
           32  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

KeyPress event, serial 37, synthetic NO, window 0x3e00001,
    root 0x283, subw 0x0, time 5047838, (1095,344), root:(1095,408),
    state 0x40, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x3e00001,
    root 0x283, subw 0x0, time 5050428, (1095,344), root:(1095,408),
    state 0x44, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x3e00001,
    root 0x283, subw 0x0, time 5050449, (1095,344), root:(1095,408),
    state 0x40, keycode 133 (keysym 0xffeb, Super_L), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False
```
Normally, this should be what happen if I hold ```super``` then press ```ctrl``` then release both of them.

However, this is what happen if I hold capslock, then hold ```A``` then ```F``` then release together.
```
FocusOut event, serial 37, synthetic NO, window 0x3e00001,
    mode NotifyGrab, detail NotifyAncestor

FocusIn event, serial 37, synthetic NO, window 0x3e00001,
    mode NotifyUngrab, detail NotifyAncestor

KeymapNotify event, serial 37, synthetic NO, window 0x0,
    keys:  4294967256 0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

FocusOut event, serial 37, synthetic NO, window 0x3e00001,
    mode NotifyGrab, detail NotifyNonlinear

FocusIn event, serial 37, synthetic NO, window 0x3e00001,
    mode NotifyUngrab, detail NotifyNonlinear

KeymapNotify event, serial 37, synthetic NO, window 0x0,
    keys:  2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

FocusOut event, serial 37, synthetic NO, window 0x3e00001,
    mode NotifyNormal, detail NotifyNonlinear

PropertyNotify event, serial 37, synthetic NO, window 0x3e00001,
    atom 0x190 (_NET_WM_STATE), time 5187019, state PropertyNewValue

PropertyNotify event, serial 37, synthetic NO, window 0x3e00001,
    atom 0x1d8 (_GTK_EDGE_CONSTRAINTS), time 5187019, state PropertyNewValue
```
The last two showed probably because the super key got trigger (as the ctrl wasn't registered) and the windows just exit and showed another UI probably. (but this is only my educated guess)

**Comment by david-janssen** [comment]
Actually, instead of xev, could you show us the evtest output for the keyboard? It's much clearer, without the added complications of X11's interpretation of things.

**Comment by slotThe** [comment]
Oh indeed!  Further, pasting the log of `kmonad -ldebug` (when pressing the keys) may also be helpful.

To cover all of the bases:  In your given configuration, `Caps-a-f` should emit `M-S` and not `M-C` (`Caps-a-d` would do that)

**Comment by Jacfger** [comment]
Em.. I'm sorry but I don't know how to use ```evtest```. I tried to switch to a virtual terminal using ctrl+alt+f2 but somehow it said the device is captured. I checked and it said logind or something like that. (don't really remember). 

Do you perhaps know how I can do evtest lol

**Comment by Jacfger** [comment]
Anyway, this time I tried to do kmonad -ldebug.

```
--------------------------------------------------------------------------------
Received event: Press <caps>
Running hooks
Pushed layer to stack: capslockmods
 1. capslockmods
Base-layer: qwerty

Registering untimed hook: 32

--------------------------------------------------------------------------------
Received event: Press <d>
Running hooks
Registering untimed hook: 33
Registering untimed hook: 34
Emitting: Press <ctl>

--------------------------------------------------------------------------------
Received event: Release <caps>
Running hooks
Popped layer from stack: capslockmods
Base-layer: qwerty

Registering untimed hook: 35

--------------------------------------------------------------------------------
Received event: Release <d>
Running hooks
Emitting: Release <ctl>
```
Here I actually did, 
```caps down -> d down-> a down-> a up-> d up-> caps up```

If I do release d before release a, it looks like this,
```
--------------------------------------------------------------------------------
Received event: Press <caps>
Running hooks
Pushed layer to stack: capslockmods
 1. capslockmods
Base-layer: qwerty

Registering untimed hook: 906

--------------------------------------------------------------------------------
Received event: Press <d>
Running hooks
Registering untimed hook: 907
Registering untimed hook: 908
Emitting: Press <ctl>

--------------------------------------------------------------------------------
Received event: Press <a>
Running hooks
Registering untimed hook: 909
Registering untimed hook: 910
Registering untimed hook: 911
Emitting: Press <met>

--------------------------------------------------------------------------------
Received event: Release <d>
Running hooks
Registering untimed hook: 912
Registering untimed hook: 913
Emitting: Release <ctl>

--------------------------------------------------------------------------------
Received event: Release <caps>
Running hooks
Popped layer from stack: capslockmods
Base-layer: qwerty

Registering untimed hook: 914

--------------------------------------------------------------------------------
Received event: Release <a>
Running hooks
Emitting: Release <met>
```

**Comment by slotThe** [comment]
1. Just executing `evtest` without any argumenst should give you a list of devices.  One of them should have the name that you gave as the first argument to the `uinput-sink`.  Select that device and things should work.
2. Maybe it's rollover that's biting you here?  What happens if you press caps, a, and d in the above combinations without running kmonad at all?

**Comment by Jacfger** [comment]
1. I selected the device and it is still captured by other device. It's a laptop keyboard, not sure if that matters.
2. Also for the second question... I think my keyboard was implemented weirdly cause I can't really press caps a with sdf together. So I guess the problem was due to laptop keyboard I guess. yikes

**Comment by david-janssen** [comment]
> I selected the device and it is still captured by other device. It's a laptop keyboard, not sure if that matters.

If kmonad is currently running, maybe it's kmonad that has captured your device? :)

**Comment by Jacfger** [comment]
But what would be the reason to use evtest if I can't see the output of kmonad

**Comment by david-janssen** [comment]
You could use evtest to see what events your input keyboard is generating. If KMonad is not picking up certain key-inputs, my first step would be to investigate exactly what keys are being sent to KMonad. The output of evtest of a particular keyboard is *exactly* the input KMonad receives when capturing that keyboard.

**Comment by Jacfger** [comment]
Ahh ic. That's sound reasonable. 👍🏼
