### ISSUE TITLE
ARM build

### ISSUE THREAD

**Issue by Kabouik** [kmonad/kmonad#261]
I can't seem to build `kmonad` on my ARM device:

```
~/Projects/kmonad$ stack build
Unable to find installation URLs for OS key: linux-aarch64-tinfo6
```

Is there any plans to provide ARM builds, or would it be difficult to allow users to compile on ARM from sources? I'm not familiar with `stack` and the error message above so I am not sure this is something I could fix myself.

ARM CPUs are now quite widespread including in devices that can be used as real computers like some ultralight laptops, SBCs (my case), recent Macs, or even mobile phones with mainline or Android kernel and running desktop distros with LXC, with external or builtin keyboard (my case too, though admittedly not widespread yet). I'd love to be able to use `kmonad` and synchronize the way I alter keyboards and keybindings across all devices.

**Comment by david-janssen** [comment]
Hey there,

I'd really like to. At the moment, however, I don't think I have a way to test and develop support for this. Also, not sure if GHC is even ready: https://www.haskell.org/ghc/blog/20200515-ghc-on-arm.html

Can you actually run a `stack repl` and do something like `3 + 1`?

**Comment by Kabouik** [comment]
Hey, thanks for the quick answer. Actually I realize now that the error I posted is not specific to `kmonad`, as I get the same if I just run `stack repl`. However I was able to run the `Hello.hs` example with no issue in the article you posted, and my `ghc` version is `The Glorious Glasgow Haskell Compilation System, version 8.8.4` (I might not be completely up to date, I want to do a backup before I upgrade because it's been a long time, never too cautious).

**Comment by david-janssen** [comment]
I was looking through stack this morning for this issue. I'm not sure if stack supports ARM at the moment (it's commented out of their releases file). That might line up with GHC working, but stack not. It should be possible to compile with cabal, but it might be a bit finicky. Haven't done that myself in ages, and it's not really something I am planning to get into anytime soon. If you do give it a shot, let me know how it goes?

**Comment by Kabouik** [comment]
I can try, no problem. Before I get into it, is there something I should be careful about to avoid cluttering my system with compilation files? I have no experience at all with cabal but will look if I can set a prefix in a given directory instead of my system.

**Comment by david-janssen** [comment]
I don't think so, in my experience cabal is very good at keeping all the dependencies in 1 place. Worst case scenario, you might have to go looking for the `.cabal` directory where cabal puts all its libraries. The only issue with cabal is that can become difficult to manage dependency versions. I've never had too much of a struggle with that, but it's supposed to be this big issue for large projects (see: https://stackoverflow.com/questions/25869041/whats-the-reason-behind-cabal-dependency-hell for more info.)

**Comment by Kabouik** [comment]
This seems to have gone pretty well on my phone with `cd ~/Projects/kmonad && cabal configure && cabal build`:

![Screenshot_20210522_001](https://user-images.githubusercontent.com/7107523/119222898-dc8ecf80-baf6-11eb-9201-f53cdac7ea8d.png)
![Screenshot_20210522_002](https://user-images.githubusercontent.com/7107523/119222901-def12980-baf6-11eb-8ecf-3384f4e21de8.png)

Now I need to learn how to use it!

**Comment by slotThe** [comment]
> The only issue with cabal is that can become difficult to manage dependency versions. I've never had too much of a struggle with that, but it's supposed to be this big issue for large projects (see: https://stackoverflow.com/questions/25869041/whats-the-reason-behind-cabal-dependency-hell for more info.)

This is still talking about cabal `v1` commands.  Cabal hell is not really a thing anymore with `v3-` style commands.

**Comment by david-janssen** [comment]
Aaaahhh cool. Is there an upside to using `stack` then? Maybe I'll go back to just using my `nix-env` and `cabal`.

**Comment by david-janssen** [comment]
> This seems to have gone pretty well on my phone with cd ~/Projects/kmonad && cabal configure && cabal build:

Wait, am I correct in reading this as: build on ARM succeeded, just don't use `stack`? In which case, Issue Resolved? Also, you run `debian-sid` on a phone?

**Comment by david-janssen** [comment]
Actually, you inspired me to give it a shot myself, and you're right, `cabal configure` >> `cabal build` just works. Also, I fould the binary, but it's *really* well hidden. For me it was in:

`~/prj/kmonad/dist-newstyle/build/x86_64-linux/ghc-8.10.4/kmonad-0.4.1/x/kmonad/build/kmonad`

Where `~/prj/kmonad` is the root of my kmonad project directory.

This was using cabal-version `3.2.0.0`.

**Comment by Kabouik** [comment]
> Wait, am I correct in reading this as: build on ARM succeeded, just don't use `stack`? In which case, Issue Resolved?

Absolutely, it looks like it just worked! It took me quite some time to find the executable under the `x` subfolder too, but I guess it makes sense.

![Screenshot_20210522_003](https://user-images.githubusercontent.com/7107523/119233913-6a84ad80-bb2b-11eb-8434-83a4daafe129.png)

I was waiting to see if I could use Kmonad on all my devices before getting into it so I don't really know yet how to use/configure it, but apparently it's a success so I'm going to dig further now!

Maybe we could update the Readme to report that compilation is possible (and relatively easy) on ARM using `cabal`?

> Also, you run `debian-sid` on a phone?

Yes, makes a lovely ultraportable ARM computer: https://www.youtube.com/watch?v=-dgD5jci8Dk&t=520s However Debian runs in a LXC container within SailfishOS, and not with the mainline kernel (but [this has been done already](https://twitter.com/kholk/status/1353762359534374923), I just don't know enough to do it too without documentation). The advantage is it runs alongside my mobile OS and I can multitask with both, so I didn't compromise Telephony, and performance is good enough for me.

**Comment by david-janssen** [comment]
> Absolutely, it looks like it just worked!

Wahay! When we cleanup the docs I shall be sure to include this.

**Comment by slotThe** [comment]
> Aaaahhh cool. Is there an upside to using `stack` then? Maybe I'll go back to just using my `nix-env` and `cabal`.

Stackage is pretty convenient, but other than that not really (especially with `cabal 3.4` and on).  At this point I think people are just going to use what they have always used, because obviously their tool of choice is much better than the other one :)

**Comment by pataquets** [comment]
@Kabouik : Does recently added [building with Docker](https://github.com/kmonad/kmonad/blob/master/doc/installation.md#using-docker) help? It would be great to get feedback for non-x86 archs!

**Comment by sandric** [comment]
Hope its not very rude to bump closed issue, but does anyone has compiled kmonad binary executable for ARM? I want to use kmonad with raspberry pi zero w I have, I tried to compile as described here using cabal installation, but for some reason it takes hours and just hangs in process. I guess it could be cross-compiled like I did for some kernel modules for my rpi, but I'm lacking of Haskell knowledge to do so unfortunately.

**Comment by pataquets** [comment]
@sandric You might be interested in #479 which might address ARM builds under Docker.

**Comment by Kabouik** [comment]
I redid the whole thing again, this time on [Droidian](https://droidian.org) instead of SailfishOS and a Debian LXC container, and again it worked nicely with `cabal update && cabal configure && cabal install`. I did it with commit ad69e1be793e61dce2d586481c0f6dda7d978c25.

I couldn't test the docker alternative because docker kernel requirements are not currently enabled on this system, but to be honest I prefer using cabal than docker which I haven't really mastered yet. 

If anyone needs the aarch64 binary for the above commit, I am uploading it here, but of course I fully understand that some won't be comfortable using it : [kmonad_aarch64.tar.gz](https://github.com/kmonad/kmonad/files/12270012/kmonad_aarch64.tar.gz)

Checksum :  `4d54f5155a1f7bc570bd1e12774e44b32aee60bee6fe9c55b9f4275611425d20 kmonad`
