### ISSUE TITLE
The Logo Ballot! DEADLINE: Wednesday 26th May @ 23:59:59

### ISSUE THREAD

**Issue by david-janssen** [kmonad/kmonad#263]
The issue where logos can be placed to be eligible for voting.

For an overview of the rules/system, see: https://github.com/kmonad/kmonad/issues/239#issuecomment-846367651

**Comment by vherrmann** [comment]
Gradient K:
![bitmap](https://user-images.githubusercontent.com/50072577/119227845-44054900-bb10-11eb-8060-e15c3ff790ef.png)

**Comment by 6gk** [comment]
Haskell Double-K

![Haskell Double-K.png](https://user-images.githubusercontent.com/40295114/119228666-6a9aa280-bb57-11eb-957d-b817c774020f.png)

[Source SVG](https://github.com/kmonad/kmonad/files/6526511/kmonad-submission.zip)

**Comment by MaxGyver83** [comment]
### Haskell meets QMK

<img alt="kmonad" width="300" src="https://user-images.githubusercontent.com/18474102/118656551-86fab000-b7e2-11eb-898d-71fd80e5b43a.png">

(Created by @thoelze1, please decide about a license.)

**Comment by david-janssen** [comment]
Poll closed.
Ballot box open: #269

**Comment by david-janssen** [comment]
By the grace of @slotThe:

Haskell meets QMK: light-mode

![119723220-81017080-be6d-11eb-9355-a3ec4909d995](https://user-images.githubusercontent.com/3296759/119779581-21d14980-bec9-11eb-9a9e-d2083b2e7075.png)
