### ISSUE TITLE
The ballot-box: Closing on Wednesday 06-02 at 23:59:59

### ISSUE THREAD

**Issue by david-janssen** [kmonad/kmonad#269]
Please vote here on your ranking of the three ballots found in: #263 

Just a post with something like (used foods as an example):
1. Apple-pie
2. Gumbo
3. Punta de anca

All of the submissions were well within the realms of respectability, I won't be using my veto powers. 

The ballot-box closes exactly 7 days after the submission thread, at which point the winner will be the logo until the next logo competition, which I'm hoping to hold towards the end of the year. 

EDIT: 1 last logo squeeked in, by the grace of @slotThe, now there is a choice of 4. In which case I might have to use my tiebreak powers.

**Comment by vherrmann** [comment]
Gradient K

**Comment by david-janssen** [comment]
@vherrmann 

Note: if you don't give a ranked list, then there exists the opportunity that Gradient K doesn't win, but since you provided no ranking for 2nd or 3d, your further preferences will not be able to be considered. You don't *have* to give a list-of-3, so if you have no preference between the other 2 this is fine. I hope I make myself clear.

**Comment by elkowar** [comment]
1. Gradient K
2. Haskell Double-K
3. actually nothing, but if i really _have_ to provide a third vote then "Haskell meets QMK" - not really a fan of it though 👀

**Comment by slotThe** [comment]
1. Haskell Double-K
2. Haskell meets QMK: light-mode
3. Haskell meets QMK

**Comment by Vermoot** [comment]
1. Gradient K
2. Haskell meets QM}K (light mode)
3. Haskell double k

**Comment by MaxGyver83** [comment]
1. Haskell meets QMK: light-mode
2. Haskell meets QMK
3. Haskell Double-K
4. Gradient K

(Technically, I have submitted "Haskell meets QMK". But only because my version with a lighter background did not yet exist at this time. If you insist that "Haskell meets QMK" (with dark background) has to be my first choice, I'll swap 1 and 2.)

**Comment by david-janssen** [comment]
> (Technically, I have submitted "Haskell meets QMK". But only because my version with a lighter background did not yet exist at this time. If you insist that "Haskell meets QMK" (with dark background) has to be my first choice, I'll swap 1 and 2.)

Nah, this makes perfect sense.

**Comment by 6gk** [comment]
1. Haskell Double-K
2. Gradient K


I'd choose the dark QMK as a third if it had more contrast, but I'm not too big of a fan of it or the light version to be honest

**Comment by jchtt** [comment]
1. Haskell Double-K
2. Haskell meets QMK: light-mode

**Comment by salahdin-ahmed** [comment]
1. Haskell meets QMK
2. Haskell meets QMK: light-mode
3. Haskell Double-K

**Comment by Nooo37** [comment]
1. Gradient K
2. Haskell Double-K
3. Haskell meets QMK

**Comment by Baseng0815** [comment]
1. Gradient K
2. Haskell Double-K
3. Haskell meets QMK

**Comment by arcticlimer** [comment]
1. Haskell Double-K
2. Gradient K

**Comment by miffi** [comment]
1. Haskell Double-K
2. Gradient K

**Comment by wismill** [comment]
1. Haskell Double-K
2. Haskell meets QMK: light-mode
3. Haskell meets QMK

**Comment by gwimm** [comment]
Gradient K

**Comment by 6gk** [comment]
~~fuck, you broke what i was using to get the numbers by not using a list~~

**Comment by AtomToast** [comment]
1. Haskell meets QMK
2. Gradient K
3. Haskell Double-K

**Comment by thoelze1** [comment]
1. Haskell Double-K
2. Haskell meets QMK
3. Haskell meets QMK: light-mode

**Comment by 6gk** [comment]
:eyes: is the voting period over?

16 voters

votes: https://0x0.st/-_1D.txt

least popular 1st vote removed, with everyone who voted for it having the subsequent ones moved up (ie in the example above, assuming apple-pie is the least popular first vote, then gumbo would be moved to their first vote, and punta-de-anca moved to second - apologies if I misunderstood the voting method, also I'm counting thoelze1 even though he commented 8h after the listed deadline)

In this case, that was qmk light mode with **one** 1st vote: https://0x0.st/-_1k.txt

And then the normal qmk one with **three** 1st votes: http://0x0.st/-_1d.txt

(Assuming that I didn't do it wrong) I think that means Haskell Double-K wins?

Good job to everyone who submitted a logo!  It was a fun ride, and they all had their own charm.  🙂

CC: @david-janssen, @vherrmann, @MaxGyver83, @slotThe

**Comment by slotThe** [comment]
> (Assuming that I didn't do it wrong) I think that means Haskell Double-K wins?

Looks right to me!  I don't think I have the rights to set it as the picture of the kmonad org, but if you want to open a PR to add it to the README in a nice way then feel free to :+1: 

I will close this for now and unpin the other issues regarding voting.  Thanks to all who participated!

**Comment by david-janssen** [comment]
Hey everyone. Thanks for wrapping this up for me! I ended up getting really ill again on the monday before the vote closed. The problem with really bad allergies is that, when the weather changes, *everything* changes.

Starting to see through the haze again, hope to be coming back to kmonad on Monday, even if only for an hour here or there. It is *amazing* for me that I can just fall away and be sick for a bit, and things end up taking care of themselves. Thank you, thank you, thank you. You all are more amazing than I can express in words.
