### ISSUE TITLE
key isn't detected

### ISSUE THREAD

**Issue by Ultrahalf** [kmonad/kmonad#273]
config
```
(defsrc
  esc
  grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab  q    w    e    r    t    y    u    i    o    p    [    ]    \
  caps a    s    d    f    g    h    j    k    l    ;    '    ret
  lsft z    x    c    v    b    n    m    ,    .    /    rsft
  lctl lmet lalt           spc            ralt cmp  rctl
)
(defalias
	spc (tap-next-release spc (layer-toggle num))
)
(deflayer num
  _
  _    _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    _    _    _    _    =    7    8    9    _    _    _    _
  del  _    _    _    lsft _    `    4    5    6    0    _    _
  _    _    _    _    _    _    -    1    2    3    _    _
  _    _    _           _            _    _    _
)

```
every number and symbol is detected except @(or 2 with left shift)
even the xev doesn't detect it

**Comment by david-janssen** [comment]
So, are you telling me that when you press the `2` button on your keyboard, nothing happens? Does it work when `kmonad` is off? Maybe your keyboard is broken?

**Comment by Ultrahalf** [comment]
keyboard works fine

![image](https://user-images.githubusercontent.com/41832211/120754213-f7ffce80-c529-11eb-98eb-1e1aa67b545b.png)
my problem is when I press ```space + (remapped shift keys i.e f or a) + ,``` output should be @ but i get no character.

```space + f + ,```
![image](https://user-images.githubusercontent.com/41832211/120755121-31850980-c52b-11eb-9ad0-27165822d887.png)
no character 

but when default shift is pressed ```space + (shift below caps lock key or shift below enter key) + ,``` gives me @ 
![image](https://user-images.githubusercontent.com/41832211/120754948-f8e53000-c52a-11eb-9315-33a02914133e.png)

**Comment by Ultrahalf** [comment]
config
```
(defcfg
  ;; For Linux
  input  (device-file "/dev/input/by-path/platform-i8042-serio-0-event-kbd")
  output (uinput-sink "My KMonad output")
  fallthrough true
)

(defsrc
  esc
  grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab  q    w    e    r    t    y    u    i    o    p    [    ]    \
  caps a    s    d    f    g    h    j    k    l    ;    '    ret
  lsft z    x    c    v    b    n    m    ,    .    /    rsft
  lctl lmet lalt           spc            ralt cmp  rctl
)

(defalias
;; Default layout aliases
	spc (tap-next-release spc (layer-toggle num))
    evl (tap-hold 200 esc (layer-toggle vi))

;; Control backspace
    cbs C-bspc

;; Homerow mods
    M_a (tap-hold-next-release 200 a lmet)
    A_s (tap-hold-next-release 200 s lalt)
    C_d (tap-hold-next-release 200 d lctl)
    S_f (tap-hold-next-release 200 f lsft)
    S_j (tap-hold-next-release 200 j rsft)
    C_k (tap-hold-next-release 200 k rctl)
    A_l (tap-hold-next-release 200 l lalt)
    M_; (tap-hold-next-release 200 ; rmet)

;; VI-like-mode-aliases
	b (around rctl lft) ;; move by word
	w (around rctl rght) ;; ^^ backwards
	v (layer-add sel) ;; set visual mode

;; VI-selection-like-mode-aliases
	vb (around rctl S-lft) ;; select by word
	vw (around rctl S-rght) ;; ^ backwards
    vsh (around rctl S-home) ;; select everything  from current position to beginning
    vse (around rctl S-end)  ;; select everything  from current position till end
	vlf S-lft
	vrg S-rght
	vup S-up
	vdo S-down
	vho S-home ;; select till beginning of the line
	ven S-end ;; select to the end of the line
	ves (layer-rem sel) ;; exit visual mode

;; Tab as Tab/meh
;;  tab (tap-hold 200 tab C-A-S)
)

(deflayer default
  esc
  grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab q    w    e    r    t    y    u    i    o    p    [    ]    \
  @evl @M_a @A_s @C_d @S_f g   h    @S_j @C_k @A_l @M_; '    ret
  lsft z    x    c    v    b    n    m    ,    .    /    rsft
  lctl lmet lalt           @spc            ralt rmet rctl
)

(deflayer vi
  _
  _    _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    @w   _    _    _    _    _    home _    _    _    _    _
  _    end  _    _    _    _    lft  down up   rght _    _    _
  _    _    _    _    @v   @b   _    _    _    _    _    _
  _    _    _           _            _    _    _
)

(deflayer sel
  _
  _    _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    @vw  _    _    @vse _    _    _    @vho _    _    _    _
  @ves @ven _    _    _    @vsh _    @vlf @vdo @vup @vrg _    _
  _    _    _    _    _    @vb    _    _    _    _    _    _
  _    _    _           _              _    _    _
)
(deflayer num
  _
  _    _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    _    _    _    _    =    7    8    9    _    _    _    _
  del  lsft _  @cbs   rsft [    `    4    5    6    0    ]    _
  _    _    _    \\   _    _    -    1    2    3    _    _
  _    _    _           _            _    _    _
)

#|
(deflayer num
  _
  _    _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    _    _    _    _    =    7    8    9    \\   _    _    _
  del  lsft @fn  @cbs rsft _    `    4    5    6    0    ]    _
  _    _    _    _    _    _    -    1    2    3    _    _
  _    _    _           _            _    _    _
)

(deflayer fn
  _
  _    _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    _    _    _    _    _    _    f11  f12  \\   _    _    _
  @fne f1   f2   f3   f4   f5   f6   f7   f8   f9   f10  _    _
  _    _    _    _    _    _    _    _    _    _    _    _
  _    _    _           _            _    _    _
)
|#
```

**Comment by david-janssen** [comment]
Sorry for the late reply, I often get sick for weeks at a time and have to disappear for a bit.

I am having trouble grokking the issue very clearly, so I'm going to ask you to confirm a few things for me.

1. This happens only for keys that you have remapped to home-row. I.e. When you use shift-keys mapped to A or F, then the keyboard refuses to register anything.
2. This happens regardless of wether you're using normal shifts mapped to A or F, or the fancy `tap-next-release` stuff.
3. This breaks *only* for the `2`,  (i.e., the `,` button mapped to 2), not for `1`, or `3`
4. If you turn KMonad off, when you press `space-f-comma` you *do* get a comma from the OS?

What happens if you map a `1` to the `,` button?
What happens if you map a `2` to the `m` button?

I am suspecting this might be an NKRO issue, but I'll need you to check the things I mentioned above.

**Comment by Ultrahalf** [comment]
> 1. This happens only for keys that you have remapped to home-row. I.e. When you use shift-keys mapped to A or F, then the keyboard refuses to register anything.

correct.
it registers @ when  `space-shift-comma` is pressed but not with remapped shift 

> 3. This breaks _only_ for the `2`,  (i.e., the `,` button mapped to 2), not for `1`, or `3`

correct it only break for `2`

> 4. If you turn KMonad off, when you press `space-f-comma` you _do_ get a comma from the OS?

looks like its not kmonad's issue, os wont detect when those 3 keys are pressed together.

> What happens if you map a `1` to the `,` button?
nothing

> What happens if you map a `2` to the `m` button?
@ 

> I am suspecting this might be an NKRO issue, but I'll need you to check the things I mentioned above.

Im going to close the issue because my os itself doesn't detect it. @david-janssen

**Comment by david-janssen** [comment]
Yep, NKRO issue. Happy we got it diagnosed :-)
