### ISSUE TITLE
Mapping accents on a layer with `alt`, but keeping the basic `alt` functionality as well

### ISSUE THREAD

**Issue by Vermoot** [kmonad/kmonad#279]
This is from a Discord discussion. In the next few replies, everything in a quote is from user "Simon E." on Discord, non-quote comments are my replies.

**Comment by Vermoot** [comment]
> I am trying to map some German characters like umlauts/sharp-s to alt+a/o/u/s to mimic the behavior I get with Karabiner on my work macbook. Is this possible without breaking other combinations with alt?
> 
> I attached the config I have tried, but Alt+Tab, Alt+F4 etc. don't seem to work anymore:
> 
> Any help would be appreciated!

> 
> ```
> (defcfg
>   input  (device-file "/dev/input/event2")
>   output (uinput-sink "My KMonad output"
>     "/usr/bin/sleep 1 && /usr/bin/setxkbmap -option compose:ralt")
>   fallthrough true
>   allow-cmd false
> )
> 
> (defsrc
>   grv   1    2    3    4    5    6    7    8    9    0    -    =    bspc
>   tab   q    w    e    r    t    y    u    i    o    p    [    ]    ret
>   caps  a    s    d    f    g    h    j    k    l    ;    '    \
>   lsft lsgt  z    x    c    v    b    n    m    ,    .    /    rsft
>   lctl lmet lalt            spc                 ralt cmp  rctl
> )
> 
> (defalias
>   alt (tap-hold-next-release 150 (layer-next umlauts) ralt)
>   cap (layer-next umlautscaps)
> )
> 
> (deflayer lv1
>   _     _    _    _    _    _    _    _    _    _    _    _    _    _
>   _     _    _    _    _    _    _    _    _    _    _    _    _    _
>   esc   _    _    _    _    _    _    _    _    _    _    _    _
>   _     grv  _    _    _    _    _    _    _    _    _    _    _
>   _     _    @alt           _              @alt _    _
> )
> 
> (deflayer umlauts
>   _     _    _    _    _    _    _    _    _    _    _    _    _    _
>   _     _    _    _    _    _    _    ü    _    ö    _    _    _    _
>   _     ä    ß    _    _    _    _    _    _    _    _    _    _
>   @cap  _    _    _    _    _    _    _    _    _    _    _    @cap
>   _     _    _    _              _    _    _
> )
> 
> (deflayer umlautscaps
>   _     _    _    _    _    _    _    _    _    _    _    _    _    _
>   _     _    _    _    _    _    _    Ü    _    Ö    _    _    _    _
>   _     Ä    ß    _    _    _    _    _    _    _    _    _    _
>   _     _    _    _    _    _    _    _    _    _    _    _    _
>   _     _    _    _              _    _    _
> )
> ```

> [This](https://cdn.discordapp.com/attachments/843041623566188554/852180458754015242/linux-desired.jpg) is the layout I am trying to achieve

**Comment by Vermoot** [comment]
Thing is, if you make alt a layer key, it doesn't do alt anymore, just the layer change. You might have issues with shift as well.

What you *could* do is `(defalias alt (around alt (layer-toggle alt)))`, making your alt key both a layer-toggle and an alt key, so all of your transparent (`_`) keys result in `alt-key`, like before. The problem with that, though, is then that your keycodes like `ü` `ö` etc will get `alt`ed as well, which will be problematic.

For this reason I can't recommend you make `shift` and `alt` layers like you did, it's just asking for trouble :smile:

This is a similar problem as described in #111, although I haven't read through that in a while and I can't say if you'll find a solution there.

For now what I'd suggest is one of two solutions:
- Make another, non-modifier key into your umlauts layer-toggle (possibly `M`, as you'll still be able to use that with your thumb, albeit not as comfortably). This might be a bit tricky as you'll have to tune your timings to avoid accidental triggering if you type too quickly (think typing `more`, if you type too quickly and don't release `M` in time you might type `öre`). This is definitely doable, though, since it's the exact same thing as using home row mods (shift on `A`, ctrl on `R`, etc), which many people (myself included) do daily, without any issues.
This solution would look like so: `(defalias M (tap-hold-next-release 150 m (layer-toggle umlauts)))` (provided you rename your `alt` layer `umlauts`).
For more info on how `tap-hold-next-release` works, you can check out the tutorial, it's very well explained there.

**Comment by Vermoot** [comment]
I think your solution is great. Making a "shift" layer in another layer like you did works great, and it won't cause any problems with the real shift key, so that works great, especially with the one shot layer!

**Comment by slotThe** [comment]
I'm starting to think that for these kinds of things, perhaps GitHub discussions would be a better place?

**Comment by Vermoot** [comment]
For those discussions or to copy them afterwards?

**Comment by 6gk** [comment]
@Vermoot I assume copying.

@slotThe I've never used github's discussions feature, how do they work? ​ Also, this repo doesn't seem to have them enabled.

**Comment by david-janssen** [comment]
I'm really happy that this was copied here, it very much fits in the 'the books belong in the library' philosophy. I'm gonna drop a link to it in my 'add to docs' issue. And then perhaps someday someone will get to it.

**Comment by slotThe** [comment]
Fair enough, let's keep these things as issues then.  Maybe that's more
searchable anyways

**Comment by david-janssen** [comment]
Ideally we'd centralize all of this in a proper documentation platform at some point. But there are many things to do, and only so much time :)
