### ISSUE TITLE
Shift Key Doesn't Release When Used With Layer-Toggle

### ISSUE THREAD

**Issue by austinliuigi** [kmonad/kmonad#280]
I have an extend layer that is toggled with caps lock. In the layer, I have defined the arrow keys to be on I, J, K, and L and shift to be on D.

I recently tried to highlight some text using the arrow keys in tandem with the shift key in my layer and noticed a bug where the shift stays toggled on even after releasing everything.

For instance, if I try to highlight the letter to the left of my cursor using CAPS+D+J, it works fine. But if I then try to copy that letter using ctrl+C in my base layer, it instead executes the ctrl+shift+C shortcut. In fact, anything I type after that initial highlight is shifted, so if press the number 2, the @ symbol shows up, and if I type out a lowercase word, it comes out capitalized.

It isn't until I press shift again manually, either on my base layer using the shift key or the extend layer using CAPS+D, that the shift gets toggled off.

This seems to only occur if I press shift in the extend layer along with a key that is _defined_ in the extend layer. So if I press CAPS+D+Y and there is no key assigned to Y in my extend layer, the bug is not triggered, whereas if Y was assigned to something in the layer, the shift key would unexpectedly toggle on.

Edit: This actually doesn't have to do with the extend layer at all. Using the regular shift key with the standard arrow keys triggers the same issue as long as Kmonad is running.

**Comment by Vermoot** [comment]
Could you show us your config, and tell us what system you're running on?

**Comment by austinliuigi** [comment]
Yeah, I'm running on Windows 10.
```
(defcfg
  ;; For Windows
  input  (low-level-hook)
  output (send-event-sink)

  ;; Comment this if you want unhandled events not to be emitted
  fallthrough true

  ;; Set this to false to disable any command-execution in KMonad
  allow-cmd false
)



(defsrc
  esc  f1   f2   f3   f4   f5   f6   f7   f8   f9   f10  f11  f12  prnt del  home end  pgup pgdn
  grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc      nlck kp/  kp*  kp-  
  tab  q    w    e    r    t    y    u    i    o    p    [    ]    \         kp7  kp8  kp9  kp+
  caps a    s    d    f    g    h    j    k    l    ;    '    ret            kp4  kp5  kp6     
  lsft z    x    c    v    b    n    m    ,    .    /    rsft up             kp1  kp2  kp3  kprt
  lctl lmet lalt           spc            ralt      rctl left down rght           kp0  kp.
)



(defalias  ext  (tap-hold-next 300 caps (layer-toggle extend))) ;; Bind ext to a button that acts as caps on tap, activate extend layer on hold
(defalias  cus  (tap-next-release ; rctl))						;; Bind cus to a buttom that acts as semicolon on tap, control on hold
(defalias  sl   (sticky-key 300 lsft))
(defalias  sr   (sticky-key 300 rsft))


(deflayer standard
  esc  f1   f2   f3   f4   f5   f6   f7   f8   f9   f10  f11  f12  prnt del  home end  pgup pgdn
  grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc      nlck kp/  kp*  kp-  
  tab  q    w    e    r    t    y    u    i    o    p    [    ]    \\        kp7  kp8  kp9  kp+
  @ext a    s    d    f    g    h    j    k    l    @cus '    ret            kp4  kp5  kp6     
  @sl  z    x    c    v    b    n    m    ,    .    /    @sr  up             kp1  kp2  kp3  kprt
  lctl lmet lalt           spc            ralt      rctl left down rght           kp0  kp.
)



(deflayer extend
  _    _    _    _    _    _    _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    _    _    _    _    _    _    _    _    _    _    _    del       _    _    _    _
  _    _    lalt vold volu pp   _    home up   end  _    _    _    _         _    _    _    _
  _    _    lmet shft ctl  _    _    left down rght _    _    _              _    _    _
  _    _    _    _    prev next pgup pgdn _    _    _    _    _              _    _    _    _
  _    _    _              _              _         _    _    _    _              _    _
)
```

**Comment by david-janssen** [comment]
This looks to be an issue with `sticky-key` right? Everything else works well?

**Comment by austinliuigi** [comment]
Don't think so. The shift in my extend layer isn't a sticky but it still triggers the bug.

**Comment by austinliuigi** [comment]
Never mind, you're right. I just edited my config and changed the stickies to normal shifts and I'm unable to reproduce the bug with that config. 

I was curious why the non-sticky was triggering the bug before so I changed only one shift back to a sticky and I was able to trigger the bug not just with the sticky shift, but with any shift. So as long as you have at least one shift set as a sticky, any shift is prone to producing this bug.

**Comment by david-janssen** [comment]
Happy to hear we managed to narrow down the issue to the sticky keys.

I'm not entirely sure I understand your issue exactly. Is your sticky key giving actually buggy behavior, or is it behaving as a sticky key should?

**Comment by austinliuigi** [comment]
There's actually buggy behavior. The shift stays pressed indefinitely after being used with the arrow keys.

**Comment by david-janssen** [comment]
Pinging @slotThe, I think you implemented sticky-key behavior, right? I have never used them myself so it's a bit hard for me to grok exactly what is intentional and unintentional behavior. Would you mind having a look at this?

**Comment by slotThe** [comment]
> Pinging @slotThe, I think you implemented sticky-key behavior, right? I have never used them myself so it's a bit hard for me to grok exactly what is intentional and unintentional behavior. Would you mind having a look at this?

Indeed I did yes.  This definitely sounds like a bug (if I understand correctly) but I also can't seem to reproduce it.

#### What I did 

With the config given in [this comment](https://github.com/kmonad/kmonad/issues/280#issuecomment-859917054) I executed

    PCaps Pd Tj Rd RCaps 

to highlight the character to the left of the cursor in some window.  Upon release of caps, I can press `2` or `C-c` and everything works correctly; no extra shift seems to be pressed.  @austinliuigi did I perhaps misunderstand you with regards to how to reproduce this?

Another thing to note is that I tried this on GNU/Linux, as I have not used Windows in a few years and have no access to a Windows machine at this point—perhaps it's a weird OS interaction?

**Comment by austinliuigi** [comment]
@slotThe 
You understood perfectly the issue I was having. I just tested it on my laptop which is also running on Windows 10 to see if it would produce the bug but it works just fine. Perhaps it is an issue with my computer or the keyboard I am using. 

Nevertheless, it seems to be a problem that is unique to my situation so I'll make do without the sticky key functionality; sorry for the bother and thanks for the help.
