### ISSUE TITLE
Tutorial config fails to run on arch linux

### ISSUE THREAD

**Issue by destroyer449** [kmonad/kmonad#283]
When I install the `kmonad-bin` package from the AUR, and then run the default kmonad config with `kmonad ~/.config/kmonad/tutorial.kbd`, I get the following error:

```
kmonad: Parse error at 158:3:
    |
158 | cmp-seq-delay 5 ;; 5ms delay between each compose-key sequence press
    | ^
unexpected 'c'
expecting ')'
```

I have added myself to all of the neccessary groups, and I am currently running and xorg server (xmonad window manager in case this is in any way relevant), so I don't get why the tutorial config doesn't run...

**Comment by slotThe** [comment]
On Tue, Jun 15 2021 17:17, destroyer449 wrote:
> ```
> kmonad: Parse error at 158:3:
>     |
> 158 | cmp-seq-delay 5 ;; 5ms delay between each compose-key sequence press
>     | ^
> unexpected 'c'
> expecting ')'
> ```

The `cmp-seq-delay` field was added in
0e0df929a8b12c4dc000c54597835052ece98880, which is not in any released
version yet.  You will need to run the git version if you want that
functionality.

**Comment by slotThe** [comment]
I will close this for now, as I think this was your issue.  @destroyer449 feel free to chime in if you still have questions

**Comment by destroyer449** [comment]
Sorry for not responding earlier, but installing `kmonad-git` did fix this issue, so it was indeed my problem.
