### ISSUE TITLE
Kmonad not available in Windows

### ISSUE THREAD

**Issue by zac-ng** [kmonad/kmonad#284]
Hi, I'm trying to install kmonad in Windows.  When I run kmonad.exe, I get the message: 

kmonad.exe: Not available under this OS: DeviceSource. 

Is windows no longer supported?

**Comment by salahdin-ahmed** [comment]
Maybe this is related to #139.

**Comment by slotThe** [comment]
Indeed it seems like it.  @zac-ng does this solve your issue?  If yes, would you care to add it to the FAQ, so other people can find it more easily?

**Comment by zac-ng** [comment]
Yup that fixes it.  I think @salahdin-ahmed made a pull request to add it to the faq, but I can add one if that is denied.

**Comment by salahdin-ahmed** [comment]
> I can add one if that is denied.

Maybe you can make *code review* for the parts that you would change in the PR if it does not change what is written fundamentally.

**Comment by zac-ng** [comment]
> 
> 
> 
> @zac-ng, maybe you can make _code review_ for the parts that you would change in the PR #285 if it does not change what is written fundamentally.

@salahdin-ahmed I made a code review for some small typos.  Not sure if typos matter all that much, but feel free to disregard them.
