### ISSUE TITLE
Allow logging to be set from config

### ISSUE THREAD

**Issue by dit7ya** [kmonad/kmonad#288]
I am planning to build a widget in AwesomeWM which would show me the currently activated KMonad layer (and maybe some more info in future). However AFAIU there is no easy way to get the current layer status programmatically. So my second thought is to just use `kmonad -l debug` so that I can just parse the output and look for something like `base-layer: ...`.

However it turns out to do that I have to modify the systemd files and add the `-l` flag that way. This seems inconvenient cause I have to now maintain two things (the systemd scripts are otherwise managed by the vanilla AUR installation itself).

It would be nice to have the ability to set up a logfile location in the config file itself.

**Comment by dit7ya** [comment]
Sorry, I forgot that I wrote the the systemd script myself, but my request remains otherwise - logging to a separate file would be really helpful.

**Comment by thoelze1** [comment]
Why not invoke kmonad under a script/alias that starts kmonad with the desired flags and redirects output?

**Comment by slotThe** [comment]
Yeah I think redirecting output is definitely the easier solution here
