### ISSUE TITLE
Kmonad package on nixpkgs is broken

### ISSUE THREAD

**Issue by arcticlimer** [kmonad/kmonad#294]
When I try to install kmonad using nixpkgs, with the package `haskellPackages.kmonad`, it shows a warning saying that the package is broken:

```
error: Package ‘kmonad-0.4.1’ in /nix/store/nanws06l7r1avkvjjga5vlv01y2v4n8d-source/pkgs/development/haskell-modules/hackage-packages.nix:156052 is marked as broken, refusing to evaluate.

       a) To temporarily allow broken packages, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_BROKEN=1

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowBroken = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowBroken = true; }
       to ~/.config/nixpkgs/config.nix.
```

Even though if I try allowing nix to download and build broken packages, I get this build error:

```
error: builder for '/nix/store/qijz9m2yfbzpm8fvhs07ll7s1vsac04a-kmonad-0.4.1.drv' failed with exit code 1;
       last 10 log lines:
       >   configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:180:19 in Cabal-3.2.1.0:Distribution.Simple
       >   defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:116:27 in Cabal-3.2.1.0:Distribution.Simple
       >   defaultMain, called at /nix/store/4mdp8nhyfddh7bllbi7xszz7k9955n79-Setup.hs:2:8 in main:Main
       > Setup: Encountered missing or private dependencies:
       > base >=4.12.0.0 && <4.13,
       > lens >=4.17.1 && <4.18,
       > megaparsec >=7.0.5 && <7.1,
       > optparse-applicative >=0.14.3.0 && <0.15,
       > time >=1.8.0.2 && <1.9
       >
       For full logs, run 'nix log /nix/store/qijz9m2yfbzpm8fvhs07ll7s1vsac04a-kmonad-0.4.1.drv'.
error: 1 dependencies of derivation '/nix/store/m986n5k0029gmz3m3jyms167m1qg3xbz-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/fh0wm3dpl7h2fy4ppd21mjz9qklw7fg8-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/vrbqk40biw1isf9xbajkacp9j0s8d8q6-activate-vini.drv' failed to build
error: 1 dependencies of derivation '/nix/store/2vfm4b7aqz0x2dfkb2yrk36vsdkr6rry-unit-home-manager-vini.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/m22ymsh8xj9s05pkblrbbjq63p60nxxq-system-units.drv' failed to build
error: 1 dependencies of derivation '/nix/store/xcy291pjky5qlgibrapnkxnlzxv4cqvb-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/5ssmg847ckinq4l1wiykjwig4jqvjmhi-nixos-system-nixos-21.11.20210625.e1f8852.drv' failed to build
```

I would really like to be able to setup kmonad declaratively on my config.

**Comment by flexagoon** [comment]
You can still use kmonad on NixOS declaratively via a module

https://github.com/kmonad/kmonad/blob/master/doc/installation.md#the-nixos-module

**Comment by arcticlimer** [comment]
Thanks, I've had to make some adaptations in order for it to work in a pure nixos + home-manager config. But it's working now (fetching the binary from releases).
I'll leave the issue open, since would be cool have default nixpkgs support to installation, and I think the precompiled binary may fail in some systems.

**Comment by WhatisRT** [comment]
Maybe it would be nice to look into how to get the module into NixOS itself as well. It seems like a bunch of people are using it now, so maybe it's mature enough? Then, using Kmonad on NixOS would be pretty streamlined. If I find the time, maybe I'll look at it

**Comment by vherrmann** [comment]
I don't think the time has come to put in on nixpkgs, since kmonad is still very unstable (e.g. the config language will probably change).

**Comment by slotThe** [comment]
On Tue, Jul 06 2021 12:41, Valentin Herrmann wrote:
> I don't think the time has come to put in on nixpkgs, since kmonad is
> still very unstable (e.g. the config language will probably change).

It's not like Nix doesn't update their packages ;) From an outsiders
perspective, I think the whole nix stuff seems mature enough that
whoever wants to take the initiative and submit it to nixpkgs should
feel free to (perhaps only waiting until the flake PR is merged)

**Comment by vherrmann** [comment]
My concern isn't that nixpkgs won't update their package. It's just that since kmonad will change a lot, imo nobody should expect their config to continue working with the next versions of kmonad. That's why I think there should be a small obstacle to using it.

**Comment by arcticlimer** [comment]
If one is worried about that, he can easily pin its kmonad package version in nix.

**Comment by slotThe** [comment]
I will close this, since the original issue seems fixed.  If people want to push for kmonad to be part of nixpkgs, feel free to open a new issue for that!  (though I would advise everyone to wait at least until after the `keycode-refactor` branch has been merged)

**Comment by IT-Luka** [comment]
I think the same issue started happening again:

kmonad is installed through home-manager on debian, 
no new version of kmonad was released,
kmonad fails to build due to mostly the same missing dependencies

both nixpkgs packages are failing to build

<details>
  <summary>log</summary>

```
@nix { "action": "setPhase", "phase": "setupCompilerEnvironmentPhase" }
Running phase: setupCompilerEnvironmentPhase
Build with /nix/store/pzcm7f77z4agljk87pjdjway224hgi3m-ghc-9.6.4.
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/ipis901z2icg6z3i3j56ixywv4588s2b-kmonad-0.4.2.tar.gz
source root is kmonad-0.4.2
setting SOURCE_DATE_EPOCH to timestamp 1696666228 of file kmonad-0.4.2/kmonad.cabal
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "compileBuildDriverPhase" }
Running phase: compileBuildDriverPhase
setupCompileFlags: -package-db=/build/tmp.lWLsT0Ht3x/setup-package.conf.d -j8 +RTS -A64M -RTS -threaded -rtsopts
[1 of 2] Compiling Main             ( /nix/store/4mdp8nhyfddh7bllbi7xszz7k9955n79-Setup.hs, /build/tmp.lWLsT0Ht3x/Main.o )
[2 of 2] Linking Setup
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
configureFlags: --verbose --prefix=/nix/store/9381c7l9zyl6hzjj28g5sji5qyly3rb9-kmonad-0.4.2 --libdir=$prefix/lib/$compiler/lib --libsubdir=$abi/$libname --docdir=/nix/store/b9n8r9kkpdfghv7vz9cm9rh5ak3rwx37-kmonad-0.4.2-doc/share/doc/kmonad-0.4.2 --with-gcc=gcc --package-db=/build/tmp.lWLsT0Ht3x/package.conf.d --ghc-options=-j8 +RTS -A64M -RTS --enable-library-profiling --profiling-detail=exported-functions --disable-profiling --enable-shared --disable-coverage --enable-static --disable-executable-dynamic --enable-tests --disable-benchmarks --enable-library-vanilla --disable-library-for-ghci --enable-split-sections --enable-library-stripping --enable-executable-stripping --ghc-options=-haddock --extra-lib-dirs=/nix/store/1n8dg5f4435qm73m4b9m0479igx7iq7l-ncurses-6.4/lib --extra-lib-dirs=/nix/store/wb7d5iw5f08qbm6p72pz1mdd4qgcb7gs-libffi-3.4.6/lib --extra-lib-dirs=/nix/store/s2d4y6k2lanq8v8vg3skaxhmdflv12px-elfutils-0.190/lib --extra-lib-dirs=/nix/store/bhfwvw0h09nvkaj4vr2pcrfm9i758c54-gmp-with-cxx-6.3.0/lib
Using Parsec parser
Configuring kmonad-0.4.2...
CallStack (from HasCallStack):
  withMetadata, called at libraries/Cabal/Cabal/src/Distribution/Simple/Utils.hs:368:14 in Cabal-3.10.1.0:Distribution.Simple.Utils
Error: Setup: Encountered missing or private dependencies:
base <4.18,
hspec <2.11,
megaparsec <9.4,
mtl <2.3,
optparse-applicative <0.18,
resourcet <1.3,
template-haskell <2.20,
unix <2.8
```

</details>

**Comment by slotThe** [comment]
Thanks for the report! It seems like I forgot to enter myself as a maintainer in nixpkgs and so did not get pinged. I've pushed a revision on Hackage just now and will unbreak kmonad later

**Comment by slotThe** [comment]
@IT-Luka This landed in `haskell-updates` in https://github.com/NixOS/nixpkgs/pull/300746 and should trickle down to `master` (and then eventually to `{nixpkgs,nixos}-unstable` in a few weeks; thanks for reporting this! I also added myself as a maintainer, so that going forward I will be pinged about any incompatibilities and they can be resolved *before* the package is marked as broken again.
