### ISSUE TITLE
Add --version switch

### ISSUE THREAD

**Issue by pataquets** [kmonad/kmonad#296]
While tinkering with building both `master` and `keycode-refactor` branches in #295, I've missed some kind of `--version` switch to check the binary version, ideally with the build commit short hash.
No idea on how easy this could be, just dropping the idea.

**Comment by slotThe** [comment]
On Tue, Jun 29 2021 08:10, Alfonso Montero wrote:
> While tinkering with building both `master` and `keycode-refactor`
> branches in #295, I've missed some kind of `--version` switch to check
> the binary version, ideally with the build commit short hash.
>
> No idea on how easy this could be, just dropping the idea.

I like this idea :+1:

The version itself would be trivial, as cabal knows this and we can
query it through the generated `Paths_kmonad` module.

The git hash would be a little bit more complicated.  We'd probably need
to query that from git at compile via TemplateHaskell.  I can see that
TemplateHaskell is already in our `default-extensions` (although I do
not know where it is used), so perhaps that approach isn't even so
far-fetched.

**Comment by pataquets** [comment]
@slotThe : If you have handy the info to easily do this, I would love to add it to #295, if it can be done at build time. Also, any other feedback on the issue is welcome :grin: .

**Comment by slotThe** [comment]
> @slotThe : If you have handy the info to easily do this, I would love to add it to #295, if it can be done at build time.

This solution would be entirely Haskell-based, so the docker image woudn't have to change at all!
