### ISSUE TITLE
neovim: remapped `return` not working with sudo passw in :term emulator

### ISSUE THREAD

**Issue by molleweide** [kmonad/kmonad#298]
Hi,

Inside neovim's terminal emulator, I cannot use remapped return keys when prompted for password.

## workaround 

luckilly `<C-j>` works 😃 (Ctrl-j)

### os
currently i am using neovim nightly on macos mojave.

**Comment by slotThe** [comment]
What exactly do you mean by "remapped"?  Could you post a minimal config example?  And perhaps also a step-by-step on how to reproduce this issue for the Emacs heathens among us? :)

**Comment by slotThe** [comment]
I will close this for now; if there's still any problem feel free to comment
