### ISSUE TITLE
neovim secondary layer ctrl-<symbol> not working.

### ISSUE THREAD

**Issue by molleweide** [kmonad/kmonad#299]
(I post about this previously but after kmonad switch to organization I cannot find the issue...)

Holding down eg. ctrl and accessing a symbol in a secondary layer does not register in neovim.
It only registers the number (unshifted character).

In my own layout, which is attached below, it is when I try to hold down ctrl in the base layer
and then access the symbols layer where I, on the left hand side, have all of the capitalized
symbols, eg. `^%[]#$()!@{}~\`. However, I haven't tried all of the combinations but it seems that
none of the symbols that are capitalized from numbers 1-9 work for me in neovim.

## workaround

I bind these types of commands to leader keys instead, eg. `Ctrl-^` -> `<leader>6` etc.

I don't know how to debug this issue but I am putting it here again since it isn't working.

## my personal keymap below

```
;;#| ---------------------------------------------------------------
;;
;; BASE LAYER
;;
;;--------------------------------------------------------------- |#

(defalias

  ;; back to base layer (base)
  bz  (layer-switch base)

  ;; fn (around (layer-toggle spacelayer) fn)
  off (layer-switch off)
  num (layer-toggle symbols)
  Lspace (layer-toggle layerspace)

  ;; TOP ROW
  lnT (tap-hold-next-release 500 e @num)
  rnT (tap-hold-next-release 500 i @num)

  ;; HOME ROW
  a (tap-hold-next-release 500 a lctl)
  s (tap-hold-next-release 500 s lsft)
  d (tap-hold-next-release 500 d lalt)
  f (tap-hold-next-release 500 f lmet)
  j (tap-hold-next-release 500 j lmet)
  k (tap-hold-next-release 500 k lalt)
  l (tap-hold-next-release 500 l lsft)
  ; (tap-hold-next-release 500 ; lctl)

  ;; BOTTOM ROW
  lnu (tap-hold-next-release 500 x @num)
  rnu (tap-hold-next-release 500 . @num)

  ;; THUMBS
  tb  (tap-hold-next-release 500 tab lmet)
  spc (tap-hold-next-release 500 spc @Lspace)
  rt  (tap-hold-next-release 500 ret lmet)
)

(deflayer base
  _    brdn brup lp   mctl bldn blup prev pp   next mute vold volu
       XX   XX   XX   XX   XX   XX   XX   XX   XX   XX   XX   XX   XX
  XX   _    _    @lnT _    _         _    _    @rnT _    _    XX   XX   XX
  XX   @a   @s   @d   @f   _         _    @j   @k   @l   @;   XX   XX
  XX   z    @lnu c    v    b    XX   _    _    _    @rnu _    XX   XX
  XX   XX   @num @tb            @spc           @rt  @num XX   XX   XX
)


;;#| ---------------------------------------------------------------
;;
;; SYMBOLS LAYER
;;
;;--------------------------------------------------------------- |#

(defalias
  syP (tap-hold-next-release 500 \) lsft)
  sy4 (tap-hold-next-release 500 4 lsft)
)

(deflayer symbols
  _    _    _    _    _    _    _    _    _    _    _    _    _
       _    _    _    _    _    @bz  _    _    _    _    _    _    _
  _    !    @    {    }    \         *    7    8    9    &    _    _    _
  _    #    $    \(   @syP `         0    @sy4 5    6    =    _    _
  _    ^    %    [    ]    ~    @bz  '    1    2    3    -    _    _
  _    _    _    lctl           lsft           lctl _    _    _    _
)
```

**Comment by vherrmann** [comment]
Please provide an example config.

**Comment by molleweide** [comment]
yes, i updated the original post.

**Comment by vherrmann** [comment]
Please make your problem clearer by explaining it in the TPR language (that's what i just called it :p) like [here](https://github.com/kmonad/kmonad/blob/98f9b10888e1fbe0fba9d5066a50d8178e31b8da/keymap/tutorial.kbd#L687).
I would also appreciate it if you could shorten your config to the essential parts.

**Comment by molleweide** [comment]
Yes I will do that later. I also need to read through all the new docs

**Comment by MuhammedZakir** [comment]
Works for me in both vim and neovim.

OS: Linux X11
VIM: 8.2
NVIM: 0.6.0-dev+29-g9132b76da

---

1. Can you please post your `defsrc`?
2. Which OS are you using?
3. Have you tried running vim/nvim with no config - `vim -u NONE`?
3. What does KMonad show when debugging ouput is enabled - `kmonad -l debug <config_file>`?
    * see if there is any difference between outputs when using vim and when not using it.
