### ISSUE TITLE
Cancel multi-tap when pressing another key

### ISSUE THREAD

**Issue by adegorre** [kmonad/kmonad#304]
Hi. First, thanks for this nice piece of software.

I am still in the process of trying to find the best configuration to suit my needs.
Doing so i experimented with multi-tap and found something that might be improved.

So I tried something like:
```lisp
(defalias
    mymulti (multi-tap 180 1 2)
)
```
When the daemon is started with this configuration, if you type key 1 then key 3 in less than 180 ms, then the output is "3, 1" when I would expect "1, 3".

I understand why kmonad is doing this: it is still waiting for another tap on 1 before deciding whether it's a 1 or a 2. But if another key is pressed just after 1, it is clear the intent of the typist was not to repeat a tap on 1.

So my suggestion: wouldn't it make sense to cancel the multi-tap behavior as soon as anything happens between the two taps?

**Comment by dmgr** [comment]
Exactly a problem I faced recently with my symbols layer that utilize: `(multi-tap 100 ó Ó)`
