### ISSUE TITLE
Execute action if two keys are pressed together

### ISSUE THREAD

**Issue by qwuy1290** [kmonad/kmonad#313]
Is it possible to press a button if other are pressed at the same time?
I would like to toggle "caps lock" by pressing both "shift" together.
Would also be very helpful to avoid losing keys. I would want to keep both right alt and right ctrl, but now one is mapped to toggle a symbol layer. Would be better to toggle that layer by pressing both alt and control together, preserving their native function.

**Comment by slotThe** [comment]
Right now, not with a lot of different layer shenanigans.  This is basically the key-combo feature as detailed in #157, if I understood you correctly, right?

**Comment by slotThe** [comment]
Closing as a duplicate then
