### ISSUE TITLE
Kmonad not grabbing keyboard

### ISSUE THREAD

**Issue by destroyer449** [kmonad/kmonad#314]
I've started trying to use kmonad, and I've ran into a problem that I don't know how to solve. I wrote a fairly basic config for kmonad:
```(defcfg
  input  (device-file "/dev/input/event4")
  output (uinput-sink "Kmonad"
    "/usr/bin/sleep 1 && /usr/bin/setxkbmap -option compose:ralt")
  cmp-seq ralt    ;; Set the compose key to `RightAlt'
  cmp-seq-delay 5 ;; 5ms delay between each compose-key sequence press

  ;; Comment this is you want unhandled events not to be emitted
  fallthrough true

  ;; Set this to false to disable any command-execution in KMonad
  allow-cmd true
)

;;Default layer
(defsrc
    esc  f1   f2   f3   f4   f5   f6   f7   f8   f9   f10  f11  f12  ssrq ins del home end pgup pgdn
    grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc         nlck kp/ kp*  kp-
    tab  q    w    e    r    t    y    u    i    o    p    [    ]    \            kp7  kp8 kp9  kp+
    esc  a    s    d    f    g    h    j    k    l    ;    '         ret          kp4  kp5 kp6
    lsft z    x    c    v    b    n    n    m    ,    .    /    rsft  up          kp1  kp2 kp3  kprt
    lctl lmet lalt          spc                  ralt rmet rctl left down  right  kp0  kp.)

#| Blank layer template
(deflayer name
    _    _    _    _    _    _    _    _    _    _    _    _    _    _    _   _   _    _   _    _
    _    _    _    _    _    _    _    _    _    _    _    _    _    _            _    _   _    _
    _    _    _    _    _    _    _    _    _    _    _    _    _    _            _    _   _    _
    _    _    _    _    _    _    _    _    _    _    _    _         _            _    _   _
    _    _    _    _    _    _    _    _    _    _    _    _    _    _            _    _   _    _
    _    _    _             _                    _    _    _    _    _     _      _    _  )
|#

(defalias cesc (tap-next esc lctl)
)

(deflayer default
    esc   f1   f2   f3   f4   f5   f6   f7   f8   f9   f10  f11  f12  ssrq ins del home end pgup pgdn
    grv   1    2    3    4    5    6    7    8    9    0    -    =    bspc         nlck kp/ kp*  kp-
    tab   q    w    e    r    t    y    u    i    o    p    [    ]    \            kp7  kp8 kp9  kp+
    @cesc a    s    d    f    g    h    j    k    l    ;    '         ret          kp4  kp5 kp6
    lsft  z    x    c    v    b    n    n    m    ,    .    /    rsft  up          kp1  kp2 kp3  kprt
    lctl  lmet lalt          spc                  ralt rmet rctl left down  right  kp0  kp.)
```
When I start kmonad as a regular user, I get the error `kmonad: /dev/uinput: openFd: permission denied (Permission denied)` even though I am part of the input group and have added the needed lines to /lib/udev/rules.d. When I run kmonad as root, I sometimes get the error: `kmonad: waitForProcess: does not exist (No child processes)`, and sometimes don't. Either way, kmonad does not actually change the functionality of my caps lock key like it should, as if it is not properly intercepting the events from my keyboard.

I'm running artix linux (functionally arch without systemd), and kmonad via the AUR kmonad-git package on a Lenovo Ideapad Z580 in case any of this information is needed.

**Comment by MuhammedZakir** [comment]
In `defsrc`, for caps lock, you used `esc` instead of `caps`. Correcting it will work.

**Comment by destroyer449** [comment]
Okay, I made the change from `esc` to `caps`, and that functionality is working now. However, I would still like to figure out the cause of the error messages above. The first error is some issue with permissions, and the second seems to be brought on by a race condition. Any thoughts on how to fix these?

**Comment by MuhammedZakir** [comment]
> However, I would still like to figure out the cause of the error messages above. The first error is some issue with permissions, [...]

You may also have to add your user to `uinput` ground. See https://github.com/kmonad/kmonad/blob/master/doc/faq.md#q-how-do-i-get-uinput-permissions. If it still doesn't work, see https://github.com/kmonad/kmonad/issues/160#issuecomment-766121884. Note that, you may have to reboot your computer after you do it. Logging out may not be enough.

> [...] the second seems to be brought on by a race condition. Any thoughts on how to fix these?

I also get it (run as normal user). But, I don't know what causes it, and currently it works, so haven't bothered to check it. I'm busy atm.

**Comment by MuhammedZakir** [comment]
> [...] second seems to be brought on by a race condition. Any thoughts on how to fix these?

After a quick test, I found this error is happening when executing the command given in `output` in `defsrc`. As a temporary workaround, you can run those commands after KMonad is started.

In `usOpen` function in `src/KMonad/Keyboard/IO/Linux/UinputSink.hs`, changing `callCommand` to `spawnComand` fixes this problem. I am not sure whether this is the right solution though.

**Comment by slotThe** [comment]
> P.S. I think the issue is with `callCommand`. If someone can confirm this, I will open a PR with above solution and also open an issue in the corresponding repo. :-)

It probably is with `callCommand`, since that one calls `waitForProcess`.  However, we're ignoring SIGCHLD to avoid zombie processes, so issueing what's essentially a `wait()` doesn't do us any good.  The fix is either to use something dhat doesn't wait, like `spawnCommand`, or to disable SIGCHLD handling for the duration of that command; I woul strongly prefer the former if it doesn't break anything, so fire ahead with that PR! :)

**Comment by MuhammedZakir** [comment]
> > P.S. I think the issue is with `callCommand`. If someone can confirm this, I will open a PR with above solution and also open an issue in the corresponding repo. :-)
> 
> It probably is with `callCommand`, since that one calls `waitForProcess`.

That's what I thought.

> However, we're ignoring SIGCHLD to avoid zombie processes, so issuing what's essentially a `wait()` doesn't do us any good. The fix is either to use something dhat doesn't wait, like `spawnCommand`, or to disable SIGCHLD handling for the duration of that command;

I didn't know that. Thanks for the info!

> I woul strongly prefer the former if it doesn't break anything, so fire ahead with that PR! :)

Done. :-)

**Comment by slotThe** [comment]
@destroyer449 I lost track of exactly what's been fixed in this issue and what hasn't;  care to bring me up to speed? :)
