### ISSUE TITLE
Around next not working with tap-hold-next-release

### ISSUE THREAD

**Issue by Swoogan** [kmonad/kmonad#316]
I am trying to make a leader key style shift key, but it's not working with other mods I have. For example:

    lsh (around-next sft)
    cts (tap-hold-next-release 200 s lctl)

If I press the leader shift, I will get a capitalized version of every key I press, except the `s` key (when tapped). It seems that the `tap-hold-next-release` is somehow interfering.

**Comment by MuhammedZakir** [comment]
I tried using `tap-next`, but it didn't work\*. It looks like a bug with compising `around-next` and muli-tap buttons.

\* It sometimes works if your release the very fast (~1 in 15 times) .

---

Even if bug is fixed, yours may not work. You will probably have to use `tap-hold-next`. See second example (`Pa Pesc Ra Resc -> ax`) of `tap-next-release`.

From `tutorial.kdb`:

>   The `tap-hold-next-release` **is just like `tap-next-release`**,
>   but it comes with an additional timeout that, just like `tap-hold-next` will
>   jump into holding-mode after a timeout.

->

> The `tap-next-release` is like `tap-next`, except it decides whether to tap or
> hold based on the next release of a key that was **not pressed before us**. This
> also performs rollback like `tap-hold`.So, using the minilanguage and foo as:
> - `(tap-next-release x lsft)`
> Then:
>     ```
>     Tesc Ta         -> xa
>     Pa Pesc Ra Resc -> ax (because 'a' was already pressed when we started, so
>                            foo decides it is tapping)
>     Pesc Ta Resc    -> A (because a was pressed *and* released after we started,
>                           so foo decides it is holding)
>     ```
