### ISSUE TITLE
How to do a one shot layer key

### ISSUE THREAD

**Issue by dlip** [kmonad/kmonad#318]
I was wondering is there a way to create a key like QMKs OSL key where you can hold it like a normal layer key or tap it to activate the layer for a single key press?

**Comment by MaxGyver83** [comment]
Yes, it is! I use it like that in [my configuration](https://github.com/MaxGyver83/dotfiles/blob/master/kmonad/.config/kmonad/vou-linux-de-rctrl.kbd#L134).

The CapsLock acts like a layer 2 modifier when held down and like a One Shot Layer key (also for layer 2) when tapped.

**Comment by dlip** [comment]
@MaxGyver83 awesome, thanks for that! Here is the one liner:

```lisp
(defalias osl (tap-hold-next-release 500 (layer-next mylayer) (layer-toggle mylayer)))
```

**Comment by dlip** [comment]
Another way to achieve this seems to be with a sticky key which has the added benefit of a timeout if nothing is pressed

```lisp
(defalias osl (sticky-key 1500 (layer-toggle mylayer)))
```

**Comment by molleweide** [comment]
lol i didn't know this was possible
