### ISSUE TITLE
False pressing of "physical" right-shift, even if it is remap in deflayer 

### ISSUE THREAD

**Issue by Veanvi** [kmonad/kmonad#327]
OS: Windows 10, ver. 20H2

If you use the config file written by me, when you hold on the left-shift on the SpaceFn layer (key F) and pressing the up arrow or home/end is triggered by pressing the Enter, which is assigned to the right shift. That is, if you try to highlight the text string in a text editor using shift + home, it will delete the selection and insert of an empty line.

![gif1](https://drive.google.com/uc?export=download&confirm=no_antivirus&id=1-gH7XDPZRLKElvaXbP-ZpiceV0Af9fR1)
![gif2](https://drive.google.com/uc?export=download&confirm=no_antivirus&id=1_bdsRR6R4dT_cb-jv4Rtt7_qtLZzLzbl)

```
(defcfg
    ;; For Windows
    input  (low-level-hook)
    output (send-event-sink)

    ;; This option tells KMonad to let non-configured keys act normal
    fallthrough true
)

(defsrc
    esc   f1   f2   f3   f4   f5   f6   f7   f8   f9   f10  f11  f12
    grv   1    2    3    4    5    6    7    8    9    0    -    =    f13
    tab   q    w    e    r    t    y    u    i    o    p    [    ]    ret
    bspc  a    s    d    f    g    h    j    k    l    ;    '    \
    lsft  z    x    c    v    b    n    m    ,    .    /    rsft
    lctl lmet lalt            spc            ralt rmet cmp  rctl
)

(defalias
    ;; Псевдонимы для слоя main ------------------------------------------------
    swf (layer-switch main)

    Sf (tap-hold-next-release 200 f lsft)
    Cd (tap-hold-next-release 200 d lctl)
    As (tap-hold-next-release 200 s lalt)
    Ma (tap-hold-next-release 200 a lmet)

    Sj (tap-hold-next-release 200 j rsft)
    Ck (tap-hold-next-release 200 k lctl)
    Al (tap-hold-next-release 200 l lalt)
    M; (tap-hold-next-release 200 ; lmet)

    sfn (tap-hold-next-release 200 spc (layer-toggle spacefn))

    ;; Псевдонимы для слоя spacefn ---------------------------------------------

    Slf (tap-hold-next-release 200 left rsft)
    Cdw (tap-hold-next-release 200 down lctl)
    Art (tap-hold-next-release 200 rght ralt)
    Min (tap-hold-next-release 200 ins lmet)

    f6 (tap-hold-next-release 200 f6 rsft)
    f5 (tap-hold-next-release 200 f5 lctl)
    f4 (tap-hold-next-release 200 f4 lalt)
    f11 (tap-hold-next-release 200 f11 lmet)

)

(deflayer main
    XX   XX   XX   XX   XX   XX   XX   XX   XX   XX   XX   XX   XX
    grv  1    2    3    4    5    6    7    8    9    0    -    =    XX
    tab  q    w    e    r    t    y    u    i    o    p    [    ]    XX
    bspc @Ma  @As  @Cd  @Sf  g    h    @Sj  @Ck  @Al  @M;  '    \
    ret  z    x    c    v    b    n    m    ,    .    /    esc
    XX   XX   XX           @sfn           XX   XX   XX   XX
)

(deflayer spacefn
    XX   XX   XX   XX   XX   XX   XX   XX   XX   XX   XX    XX   XX
    XX   XX   XX   XX   XX   XX   XX   XX   XX   XX   XX    XX   XX   XX
    tab  f12  f7   f8   f9   next volu home up   pgup caps  slck nlck XX
    del  @f11 @f4  @f5  @f6  pp   mute @Slf @Cdw @Art @Min  cmp  XX
    esc  f10  f1   f2   f3   prev vold end  prnt pgdn pause ret
    XX   XX   XX             XX             XX   XX   XX    XX
)

```

**Comment by MuhammedZakir** [comment]
> [...] when you hold on the left-shift on the SpaceFn layer (key F) [...]

In your config, `F` in `spaceFn` layer is mapped to `right shift` when held down.

```
f6 (tap-hold-next-release 200 f6 rsft)
```

I guess this problem is due to a mistake in your conifg? If not, can you give a step-by-step instruction on how to reproduce the problem?

**Comment by Veanvi** [comment]
> I guess this problem is due to a mistake in your conifg? If not, can you give a step-by-step instruction on how to reproduce the problem?

1. Run kmonad with my config
2. Open a text editor with any code.
3. Try to highlight the code string with the SHIFT + END keys. (hold Space, hold F, press M).

The string is not only selected, after the selection several times pressed enter.

Physically, the rshift key is not pressed, I do not think that sending Enter is a normal behavior.

**Comment by david-janssen** [comment]
Hey @Veanvi,

Just noticed you closed this issue: is it because we didn't respond promptly or because you solved it? Sorry for my slow responses, I get sick for long periods of time and miss a lot of notifications that way.

If you haven't managed to solve your problem: could you please explain very slowly exactly what keypresses cause the problem, I'm having trouble parsing your issue.

If you have managed to solve your problem: Wahay!
