### ISSUE TITLE
Looking For: Additional MacOS Maintainers

### ISSUE THREAD

**Issue by slotThe** [kmonad/kmonad#330]
Been using kmonad on MacOS?  Want to contribute to the project but don't know how?  Then we want _you_ to... maintain everything for us :)

Jokes aside, @thoelze1—who has been solely responsible for MacOS maintenance up until now—has become quite busy in these last few weeks and so we are looking for additional MacOS maintainers to help out.  This does involve writing a bit of Haskell code, but a lot of the work has also been done in C/C++. 

The first goal would be to actually get #259 (which is a vast simplification of keycode handling) done in order to move forward with improving other parts of kmonad and perhaps even prepare for a new release.  I will look over the Linux parts and David said he'd try to find time for the Windows side of things soon, but neither of us owns a Mac.  

If push comes to shove, there is always the option of just merging #259 with broken MacOS support and waiting for someone to come along and get annoyed enough to fix this, but this is a situation I imagine everyone would like to avoid.  So if you, dear reader, feel up to the task, feel free to contact me or David here or directly.

**Comment by MuhammedZakir** [comment]
I only have a very little Haskell and C++ experience. So I won't even say "I will give it a try" as I am not sure I would be able to do it. But still, what do I need to do? Specifically, what has changed in `keycode-refactor` branch? Any, and all details would make my work a little bit easier. :-)

P.S. If anyone else is interseted, feel free to take this.

**Comment by Vermoot** [comment]
I'd love to be of any help, but every time I look at anything Haskell I feel like I'm having a seizure. I might try to learn some basic Haskell to be able to at least understand KMonad's code, but it'll be a while before I can do anything productive, I fear :/

**Comment by molleweide** [comment]
I am in the same boat as Vermoot. I have been studying haskell during the summer but I am nowhere near
a state of being productive with haskell.

**Comment by slotThe** [comment]
> I only have a very little Haskell and C++ experience. So I won't even say "I will give it a try" as I am not sure I would be able to do it. But still, what do I need to do? Specifically, what has changed in `keycode-refactor` branch? Any, and all details would make my work a little bit easier. :-)
> 
> P.S. If anyone else is interseted, feel free to take this.

Well, the tl;dr is "look what the PR did with regards to [these modules](https://github.com/kmonad/kmonad/pull/259/files#diff-521ee437c2df35fe0cfccfad53bd038644d038b4c79401adfb996f56f9e96cc5L99-R144) and do the same thing for MacOS" :)

Essentially, we now have a unified interface for all of the operating systems we support, with OS-specific code safely hidden away in these new modules, instead of the "messy" approach we used to take.  In this sense I would answer "everything" to "what has changed?", even though I reallize how useless of an answer this is.  Maybe I will write something more enlightening here once I look more deeply into the PR myself

**Comment by molleweide** [comment]
I am going to try to read through the commits from #259 and see how much i can understand.

**Comment by molleweide** [comment]
Question: Does the C++ part here mean having to work in xcode or can most of the development be done from commandline?

**Comment by MuhammedZakir** [comment]
> Question: Does the C++ part here mean having to work in xcode or can most of the development be done from commandline?

I think we don't need to change C++ code, and AFAIK, even if we need to change C++ code, XCode is not needed as long you use the pre-built dext.

**Comment by molleweide** [comment]
Nice!

Are these files:
```
./c_src/mac/*
```
excluding the Karabiner dirs the only files that are used in kmonad on macos when it comes
to C?

**Comment by MuhammedZakir** [comment]
Yes.

> Also is there any scenario where we'd need to build a custom dext for kmonad?

Only when we want to mess with the dext code. For example, if there is a (critical) bug, and upstream is taking a long time to fix it. Or if there is a feature we want that upstream won't implement. The problem, however, is that if want to distribute dext, we will need a provisioning profile with DriverKit entitlements [1]. The whole process is very cumbersome. Only other method is to disable SIP. I don't mind. but some may dislike this.

[1] https://developer.apple.com/documentation/driverkit/requesting_entitlements_for_driverkit_development

**Comment by molleweide** [comment]
Thanks for giving such detailed nice replies Muhammed!

It's too bad that apple dev is like that.
