### ISSUE TITLE
Macos: `IOServiceGetMatchingService error: (ipc/send) invalid destination port`

### ISSUE THREAD

**Issue by molleweide** [kmonad/kmonad#332]
Hi guys,

After having used kmonad for weeks without a single problem all of a sudden my keyboard froze. After computer reboot, when I start kmonad I am presented with this error message for all of my .kbd files:
```
IOServiceGetMatchingService error
^Creset_virtual_hid_keyboard error: (ipc/send) invalid destination port
```
Has this happened to anybody else and is there a way to fix this?

I am on a macbook pro with MacOS 10.15.7 (Catalina)

What other info would be of help in order to solve this? Looking into sys prefs, input monitoring privileges are all set since I have been using kmo succesfully throughout the summer. I am also not using any launch daemons should anyone wonder.

!!

I realize that this pertains to the dext, I believe, so maybe it is best to ask for help under the Karabiner relates
repos here on github. I have been grepping the source and this error only appears under c_src.

**Comment by molleweide** [comment]
i have been googlin around for a bit but i haven't found much info or I don't understand. I am going to try and rebuild kmonad. Could that be it?

**Comment by molleweide** [comment]
Hey guys! 
I know that you have lots of  stuff to do on your own but if you have time could somebody please just point me in the right direction. I am ofc doing a lot of research on my own also. @thoelze1

**Comment by nightscape** [comment]
I think I saw that one on my machine as well, but it either didn't negatively impact the functioning, or it went away after restarting kmonad. I'm on Big Sur 11.5.2.

**Comment by molleweide** [comment]
Thanks for replying. I am going to double check when I come home later today.

**Comment by molleweide** [comment]
Allright, so now I have:

1. rebooted my computer a couple of times.
2. restarted kmonad many times.
    > multiple kbd files
3. reinstalled karabiner.
    > i built kmonad with karabiners dext if i recall?
4. toggle kmonad input monitoring.
    regardless if on/off I get the same error `IOServiceGetMatchingService error: (ipc/send...`
    should I even be able to run the command if toggled off. I was expecting something else..
5. Should I rebuild kmonad maybe?
    > but why would this make any difference?
6. I have also been searching around the web but either the discussions I find are way beyond my
    level of comprehension or it is like a thousand year old post wihtout any resolution.
    Also there are very few search hits on this error. I might have used bad search terms..

I'm probably going to by a new laptop now LOL because I just can't live without kmonad working.

**Comment by molleweide** [comment]
i have now been able to succesfully be able to build again and so i close this now. i don't know what this was.
