### ISSUE TITLE
Seems to fall back to hardware locale

### ISSUE THREAD

**Issue by TheSmallTeaBoi** [kmonad/kmonad#339]
I use a LATAM keyboard, and I'm trying to remap it to use colemak with an extend layer, but it seems like some keys are just mapped to LATAM keys.

[Here's my config](https://pastebin.com/dX0NhVkk)

I'm using linux and I have set the us layout with 
```
setxkbmap -model -layout us -option caps:none
```
but still all keys that aren't letters just default to their LATAM counterpart.

Edit: I think I should mention that I'm using a ps/2 keyboard, in case that's relevant.

**Comment by slotThe** [comment]
> I'm using linux and I have set the us layout with
> 
> ```
> setxkbmap -model -layout us -option caps:none
> ```
> 
> but still all keys that aren't letters just default to their LATAM counterpart.

This is not a fallback at all; kmonad reads the input directly from the `uinput` subsystem, which is way before X11 can apply any kind of layout to the interpreted keys.

You can try running `evtest` on your keyboard; these are basically the keys that kmonad reads and then acts upon.

**Comment by TheSmallTeaBoi** [comment]
I'm not sure what that means to me, should I change the `defsrc` block to match my keyboard's?

**Comment by MuhammedZakir** [comment]
When did you execute `setxkbmap` command? You must execute them _after_ running KMonad.

**Comment by TheSmallTeaBoi** [comment]
It seems to work fine if I do `setxkbmap` _after_ I run kmonad, but this kinda feels like a hack, I wonder what the "correct" or intended way of doing it is.

**Comment by MaxGyver83** [comment]
I run `setxkbmap` in KMonad, like this:

```clojure
(defcfg
  ;; For Linux
  input  (device-file "/dev/input/by-path/platform-i8042-serio-0-event-kbd")
  output (uinput-sink "KMonad output"
    "/bin/sleep 1 && setxkbmap de -option compose:rctrl && xset r rate 300 50")
...
)
```

Maybe this feels less like a hack for you.

**Comment by TheSmallTeaBoi** [comment]
That's actually perfect, thank you so much!

**Comment by TheSmallTeaBoi** [comment]
Oh I forgot to close this, my bad (>~<)
