### ISSUE TITLE
cmd_button notify-send error

### ISSUE THREAD

**Issue by CSpencerND** [kmonad/kmonad#341]
OS: ArcoLinux
WM: Qtile

Issue:
I have a couple of layers that I toggle between with `layer-add` and `layer-rem`. I'd like to have an indication for it, since I sometimes forget that I switched, so I tried this for example
`(cmd-button "notify-send Kmonad layer-changed")`

It doesn't work and I get this error
```(notify-send:49917): GLib-WARNING **: 15:37:21.324: In call to g_spawn_sync(), exit status of a child process was requested but ECHILD was received by waitpid(). See the documentation of g_child_watch_source_new() for possible causes.```

The notify-send works if I type it in the terminal. Just not from Kmonad.

I thought maybe the problem was Kmonad running as root and the notify-send being sent to root instead of my user so I tried prepending `su` to make sure it sends to my user. The error no longer occurs with this but I still don't get the notification.

**Comment by CSpencerND** [comment]
I different solution would be to make a status bar widget that shows which layout I'm on, but I'm unsure how I would go about doing that. Is there somewhere Kmonad stores the layout so I read from it and echo it?

**Comment by slotThe** [comment]
Have you enabled running commands by specicying `allow-cmd true` in the `defcfg` portion of the config?  Which notification daemon are you running?  I just installed and tested it with `dunst` and I'm not having any troubles with invoking `notify-send`.

**Comment by CSpencerND** [comment]
> Have you enabled running commands by specicying `allow-cmd true` in the `defcfg` portion of the config?  Which notification daemon are you running?  I just installed and tested it with `dunst` and I'm not having any troubles with invoking `notify-send`.

`allow-cmd` is `true` and I'm using `dunst`.

I used the exact same config on Ubuntu and it worked as expected. I recently switched to Arco and now I have this problem.

**Comment by slotThe** [comment]
On Sat, Aug 21 2021 15:00, CSpencerND wrote:
> I used the exact same config on Ubuntu and it worked as expected. I
> recently switched to Arco and now I have this problem.

Which version of dunst is present on each system?

This sounds more of a dunst/system problem than a kmonad problem to me
at this point

**Comment by CSpencerND** [comment]
Both systems have the latest version 1.6.1

**Comment by MuhammedZakir** [comment]
1. Can you execute other shell commands?
2. What if you use `dunstify` instead of `notify_send`?

**Comment by CSpencerND** [comment]
Other commands work. I just tried with `dunstify` (didn't know that was a thing), and here's what I got:
```
(dunstify:144348): GLib-WARNING **: 00:39:11.901: In call to g_spawn_sync(), exit status of a child process was requested but ECHILD was received by waitpid(). See the documentation of g_child_watch_source_new() for possible causes.
Unable to send notification: Error spawning command line “dbus-launch --autolaunch=bb1318e4bd0540a588696afd911edc96 --binary-syntax --close-stderr”: Child process killed by signal 48
```

**Comment by CSpencerND** [comment]
I read the documentation of `g_child_watch_source_new()` but it doesn't seem to give me any information I can use.

**Comment by MuhammedZakir** [comment]
Maybe try asking in `dunst` repo? They may know possible causes of this error.

**Comment by CSpencerND** [comment]
> Maybe try asking in `dunst` repo? They may know possible causes of this error.

Gotcha. I was thinking I should. I'll do that. Thanks.

**Comment by vikdotdev** [comment]
@CSpencerND had the same issue, running kmonad without sudo did the trick for me - https://github.com/kmonad/kmonad/issues/160#issuecomment-766121884

**Comment by CSpencerND** [comment]
> @CSpencerND had the same issue, running kmonad without sudo did the trick for me - https://github.com/kmonad/kmonad/issues/160#issuecomment-766121884
> 
> Edit: this is already in the FAQ - https://github.com/kmonad/kmonad/blob/master/doc/faq.md#q-how-do-i-get-uinput-permissions

Holy moly :facepalm: I completely forgot about this. Thank you.
