### ISSUE TITLE
Custom Key Creation

### ISSUE THREAD

**Issue by austinliuigi** [kmonad/kmonad#352]
I'm not entirely sure if this is possible or if there is a current workaround to do this, but I was thinking that a cool feature could be the ability to create a custom key. For example, one could define a key named "mykey" that acts as `a` when pressed, `$` when pressed with `shift`, and `esc` when pressed with `control`.

**Comment by Ultrahalf** [comment]
#313 sounds similar

**Comment by slotThe** [comment]
Indeed this basically sounds like #157, just specified to shift and caps; @austinliuigi is that what you meant?

**Comment by austinliuigi** [comment]
> Indeed this basically sounds like #157, just specified to shift and caps; @austinliuigi is that what you meant?

That’s pretty much what I meant. If #157 gets implemented, then it will cover this issue as well.

**Comment by david-janssen** [comment]
> That’s pretty much what I meant. If #157 gets implemented, then it will cover this issue as well.

Very good :-) In that case: closing for reasons of duplication.

**Comment by david-janssen** [comment]
Apparently I can officially mark it as such by saying:

Duplicate of: #157

**Comment by david-janssen** [comment]
Duplicate of #157
