### ISSUE TITLE
Tap hold-on feature doesn't work

### ISSUE THREAD

**Issue by zim0369** [kmonad/kmonad#353]
I'm using Arch linux on an Asus Vivobook 14 laptop and installed built Kmonad using stack. I've mapped an alias to toggle a layer but as soon as I run 'kmonad config.kbd', the layer becomes active without having to press the alias. There's no way to go back to the base layer even after smashing or holding onto the alias key. The layer becomes the final & only working layout no matter what.
Here's my config
EDIT -> After adding multiple layers, I've observed that whatever layer comes first after the base layer is set as my default keyboard layout. Everything else is just ignored.
```

(defcfg
  input  (device-file "/dev/input/by-path/platform-i8042-serio-0-event-kbd")
  output (uinput-sink "KMonad output")
  fallthrough true
  allow-cmd true
)

(defsrc
  esc   f1   f2   f3   f4   f5   f6   f7   f8   f9   f10  f11  f12
  `     1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab   q    w    e    r    t    y    u    i    o    p    [    ]    \
  caps  a    s    d    f    g    h    j    k    l    ;    '    ret
  lsft  z    x    c    v    b    n    m    ,    .    /    rsft up
  lctl  lalt lmet           spc            rmet ralt left down rght
)

(defalias num (layer-toggle nums))

(deflayer nums
  _    _    _    _    _    _    _    _    _    _    _    _    _    
  _    _    _    _    _    _    _    _    _    _    _    _    _    _
  @num _    _    _    _    _    _    2    4    6    8    _    _    _
  _    _    _    _    _    _    0    1    3    5    7    _    _
  _    _    _    _    _    _    _    9    _    _    _    _    _
  _    _    _              _              _    _    _    _    _
)
```

**Comment by ram535** [comment]
> After adding multiple layers, I've observed that whatever layer comes first after the base layer is set as my default keyboard layout. Everything else is just ignored.

That is the normal behavior.

`defsrc` is like the blueprint the other layer will be based on. And the first layer define (deflayer) in your config will be your base layer.

**Comment by Ultrahalf** [comment]
ya the first deflayer is considered as base layer

**Comment by zim0369** [comment]
> ya the first deflayer is considered as base layer

Hey, can you help me with configuring some things? 
[Here is my config.kbd](https://github.com/zim0369/dotfiles/blob/main/config.kbd) 
I've got things working now & I've made my caps key act as esc but I want to also use it as ctrl key when held on. What should I do? And please share a link to your configs as well.

**Comment by Ultrahalf** [comment]
[quick reference](https://github.com/kmonad/kmonad/blob/master/doc/quick-reference.md)
[tutorial](https://github.com/kmonad/kmonad/blob/master/keymap/tutorial.kbd)
[user config](https://github.com/kmonad/kmonad/tree/master/keymap/user)
there is nothing interesting in my [config](https://github.com/Ultrahalf/dotfiles/blob/main/.config/kmonad/config.kbd)

**Comment by zim0369** [comment]
That reference guide you made is awesome. Probably way better than the tutorial.

**Comment by Ultrahalf** [comment]
> That reference guide you made is awesome. Probably way better than the tutorial.

its in /doc of this repo i didn't write that
