### ISSUE TITLE
Problem with keys held when KMonad is started 

### ISSUE THREAD

**Issue by MuhammedZakir** [kmonad/kmonad#356]
To reprodue:
1. Held down a modifier key on the keyboad KMonad grabs.
2. Start KMonad.
3. Relelase modifier key.
3. Now, the modifier key you held will still be in a "pressed" state.

This is not a "bug", but it would be nice if this can be fixed.

**Comment by slotThe** [comment]
There's already the easy fix of adding startup time available as a config and command line option.  Since we ignore double releases anyways, I suppose we could just send a release event for some keys upon startup?  This sounds a bit like a hack, and I'm not sure if it would break anything

**Comment by MuhammedZakir** [comment]
Is it possible to detect what keys are pressed atm? If not, adding startup time is probably the way to go. Blindly sending release events could be problematic if there are "higher-level" remappings.

I forgot to mention that the OS I tested this in is Linux. I suspect the behavior might be different in macOS. Don't know about Windows.

**Comment by slotThe** [comment]
> Is it possible to detect what keys are pressed atm? 

I doubt it, somehow.  Definitely not from the Haskell code, anyways, as we are creating a new keyboard.  This means that before doing that, we would somehow have to get all pressed keys and either immediately release them, or thread them through to some point where we do that.

> Blindly sending release events could be problematic if there are "higher-level" remappings.

Indeed, you are probably right

> Edit: Now that I think about it, instead of sending release events for _predefined_ keys, users can give an optional list of keys for which a release event will be send at the start. This can solve the problem (to some extent). 

Mh...  This should probably be possible, but it almost sounds like more manual work than one would like to put up with

> IIRC, there is no option to send only press or release event, right? 

Yeah I don't think this has propagated to users yet (though internally it's done for e.g. the tap-style buttons).

**Comment by david-janssen** [comment]
> Is it possible to detect what keys are pressed atm?

Very, very, very hard. And worse: different per platform.

> There's already the easy fix of adding startup time available as a config and command line option. 

This seems by far the easiest solution, and one that we implemented for exactly this reason.


Can we close this issue?
