### ISSUE TITLE
Using Trackpoint Bauttons to activate @ext layer

### ISSUE THREAD

**Issue by jacklumber** [kmonad/kmonad#357]
Hi, loving kmonad on my Thinkpad X1 Yoga laptop so far. The Trackpad has 3 mouse click buttons on top I would like to map to activate the @ext layer. I've tried installing key-mapper to map the left mouse button to L-ALT, which is what I use to activate the ext layer. Is what I'm trying to do even possible, and if so directions would be appreciated. Thanks!

**Comment by MuhammedZakir** [comment]
Currently, there is no support for mouse event in KMonad. Also, what you want to do is not possible.
