### ISSUE TITLE
Holding Modifier? Map Holding+Key to another Holding+Key

### ISSUE THREAD

**Issue by chikko80** [kmonad/kmonad#359]
Hello,

I have been using karabiner elements for a few years now and i would love to switch to a cross platform solution.

Sorry that i have to ask, but i really don't get it out of the tutorial, i've already read it 2 times now and i see this tons of combinations the lisp language is providing, but i think one of my most used feature is missing, or am i wrong?

Is there any feature in kmonad with that i can map a holding + keypress to another holding + keypress?
So for example mapping Left_Control + C --> Left_Control + K

I would love to hear an opinion from someone who is used to kmonad.

Thanks guys and keep up the good work!

**Comment by Ultrahalf** [comment]
combos? are not a feature right now #157 

> Sorry that i have to ask, but i really don't get it out of the tutorial, i've already read it 2 times now and i see this tons of combinations the lisp language is providing, but i think one of my most used feature is missing, or am i wrong?

Give this a read [quick reference](https://github.com/kmonad/kmonad/blob/master/doc/quick-reference.md) its a short version of all the things in tutorial

**Comment by chikko80** [comment]
Oh yeah thanks, combos was the term i was looking for. But a pity that it is not yet implemented
