### ISSUE TITLE
HP Pavillion Keyboard 600 remapping help

### ISSUE THREAD

**Issue by dazzng** [kmonad/kmonad#362]
I have a question. I own HP pavillion 600 keyboard. There is a small print button just above the backspace button (as in the picture). I usually inadvertently press the Print button instead of pressing Backspace.

I want to change this. My request is when I press the Print button, I want it to type another key such as Ctrl or Insert button, something which won't have any effect when pressed not on purpose.

I tried Wİndows Power toys for this, the keyboard manager. But, the problem is when the program asks me to press the key which I want to change, I press the Print button but it sees it only as a "P" letter, not as a Print button. That is so annoying. I also tried other keyboard mapping softwares such as sharpkeys or auto hotkeys but they also see the print button as the "P" letter when I press the Print button to change it. Sİnce they all see it as "P" letter, when I type the normal "P" in my keyboard, it does not work. But it does not make any sense at all. I want to change only my Print button to be something else such as a Ctrl or Insert button so I don't want my "P" letter to change.

IS there any work around this?

Pleaese help.

Thanks.

**Comment by mauedu** [comment]
I'm new to kmonad but it looks like this `print` key is a hardware specific function key.  I don't think kmonad can remap function keys. Might be related to this FAQ question: https://github.com/kmonad/kmonad/blob/master/doc/faq.md#q-why-cant-i-remap-the-fn-key-on-my-laptop.
Here is a shot in the dark, try checking if QMK configurator can recognize that keycode: https://config.qmk.fm/#/test

**Comment by dazzng** [comment]
It did it and it came up with this.  Keycode is 80. Key is KeyP.

KEY-DOWN - QMK: KC_LCTL Event key: Control     Code: ControlLeft   KeyCode: 17
KEY-DOWN - QMK: KC_P    Event key: p           Code: KeyP          KeyCode: 80
KEY-UP   - QMK: KC_LCTL Event key: Control     Code: ControlLeft   KeyCode: 17 in 93.200ms
KEY-UP   - QMK: KC_P    Event key: p           Code: KeyP          KeyCode: 80 in 80.600ms

**Comment by MuhammedZakir** [comment]
Unfotunately, that key can't be remapped.

> KEY-DOWN - QMK: KC_LCTL Event key: Control Code: ControlLeft KeyCode: 17
> KEY-DOWN - QMK: KC_P Event key: p Code: KeyP KeyCode: 80
> KEY-UP - QMK: KC_LCTL Event key: Control Code: ControlLeft KeyCode: 17 in 93.200ms
> KEY-UP - QMK: KC_P Event key: p Code: KeyP KeyCode: 80 in 80.600ms

As you can see here, when you press the print button, your keyboard is actually sending `Control+P`. As there is no way to distinguish between `Control+P` send when print button is pressed, and the one send when you press `p` while `control` is held down.

**Comment by david-janssen** [comment]
Closing this issue because @MuhammedZakir is spot on.
