### ISSUE TITLE
Press button if no other button pressed within delay, is this possible? 

### ISSUE THREAD

**Issue by elfalem** [kmonad/kmonad#363]
I'm attempting to have a setup where the tap of a button has a delay. If **another** button gets tapped within that delay, button A gets pressed (this part seems doable). If no buttons are pressed by the end of the delay, button B gets pressed (having difficulty with this part).

In TPR notation, it would be as follows: (assuming a delay of 100):
```
Tx 50 Ty -> @a
Tx 150   -> @b
```

I think the `around-next` and `layer-delay` functions get close to this but not quite there. Is there a way to achieve this or is it not possible?

Thanks for this great project.

**Comment by david-janssen** [comment]
Have you looked at the `tap-hold-next` and `tap-hold-next-release` buttons? I think that's probably what you're looking for.

https://github.com/kmonad/kmonad/blob/master/keymap/tutorial.kbd#L723

**Comment by elfalem** [comment]
@david-janssen I did look at those buttons. However, in my testing, those buttons would require the hold button to be a modifier. Is it possible to construct the scenario I described above for cases where `x` and `y` are "regular" (i.e. non-modifier) buttons?

For background, I'm attempting to configure a transliteration system for languages that use an [abugida](https://en.wikipedia.org/wiki/Abugida) writing system. The intended usage pattern is the tapping of a Latin consonant letter followed by a Latin vowel key (e.g. "m" then "a") to represent a single letter in the target writing system. However if the consonant is not followed by any key presses within a delay period (or another consonant is pressed), then the vowel would be assumed and a letter in the target writing system would be generated.

**Comment by david-janssen** [comment]
Hehe, I've just typed out a whole section on how to set this up with `tap-hold` style buttons until I realized you want to *tap* your `m`, and then if some other button is tapped within some interval, do `a`, otherwise do `b`.

You are right: that button is currently missing. I think I'll try and give it a shot now, because it looks straightforward to implement given the underlying abstractions in the code. On the other hand, I think "That should probably be easy" are 'famous last words'. I'll keep you updated :-).

**Comment by david-janssen** [comment]
So, I've just added an `around-next-timeout` button that should get you most of the way there.

It takes 3 arguments, a timeout, a button used to 'surround' the next button press, and a fallback button to tap in case the timeout is exceeded.

So now I think you could define a layer with all of the '2-tap' characters, and then access that layer through an `around-next-timeout`, like this: `(around-next-timeout 200 (layer-toggle my-surround-layer) a)` If you bind this button to "m", then if you tap "m" and then some other button within 200 ms, you will trigger the binding in `my-surround-layer`, however, if you outwait the 200 ms, you will simply get the tap of an `a`.

The only wart you still have is that we don't categorize buttons like 'consonant' etc. So you'll have to define a very complicated layer where you bind "n" in that layer to a tap macro that first taps "m" and then "n", which is ugly but fuctional.

I hope the quick fix at least makes things workeable, and I hope to be expanding the expressivity of the input-matching and button-creation language in the future.

**Comment by elfalem** [comment]
Thank you so so much for the quick fix! It works perfectly. I immensely appreciate it.

**Comment by david-janssen** [comment]
Happy to help :)
