### ISSUE TITLE
Is there a way to emulate QMK-style autoshift?

### ISSUE THREAD

**Issue by harshasrisri** [kmonad/kmonad#367]
Hi,

Thank you for this tool. It has been a great discovery! 

I read the tutorial and couldn't figure out if there is a way to emulate QMK-style autoshift. 

Autoshift is nothing but simulating a key longpress as a shifted-key. For instance, long pressing `1` for a configured duration of time emits `!` 

Is there a way to configure this in kmonad already?

**Comment by david-janssen** [comment]
At the moment, I think not. However, I hope to be adding this soonish. I need to wrap up a big refactor we were doing, after that, it should be a breeze to add this.

**Comment by harshasrisri** [comment]
Thank you for confirming and the update on upcoming refactor. Will look forward to it!

**Comment by Ultrahalf** [comment]
1 (tap-hold 250 1 !)
like this? @harshasrisri

**Comment by harshasrisri** [comment]
In theory, yes. But is this possible? I was under the impression that only hold keys like ctrl, shift, meta. I even have configured an alias for (tap-hold 250 esc rctl).

**Comment by david-janssen** [comment]
> 1 (tap-hold 250 1 !)

Um.... How in the.. how did I just blank out on the first button I ever implemented? Yeah, this is completely possible. People shouldn't trust what I say when I'm tired...
