### ISSUE TITLE
NixOS module is broken

### ISSUE THREAD

**Issue by flexagoon** [kmonad/kmonad#373]
After the commit https://github.com/kmonad/kmonad/commit/f49a41c6ed6b871874ba1beee953fc8e0377a932, the nixos module basically doesn't work at all. The PR #364 did not fix this.

Error message:
```
error: A definition for option `services.kmonad.package' is not of type `package'. Definition values:
- In `/nix/store/81a6x3631x0fyd5mhdm5anikg3cqpp7a-source/nix/module-base.nix': <function, args: {pkgs?, sources?}>
```

**Comment by david-janssen** [comment]
I was thinking of moving kmonad to my nixos configuration myself (I use nixos too, just didn't make use of the kmonad integration just yet). I'll try it myself sometime soonish and see what breaks and if I can fix it. My `nix-fu` isn't that good, but improving.

**Comment by david-janssen** [comment]
Oh, I should say: over the course of the next few weeks. Not sure if I have the time to get to this quickly.

**Comment by flexagoon** [comment]
Okay, guess I'll have to use the latest working commit until then. Thanks!

**Comment by dlip** [comment]
I'm not having any issues using flakes either, what's your setup @flexagoon ?

**Comment by flexagoon** [comment]
> I'm not having any issues using flakes either, what's your setup @flexagoon ?

I am not using flakes.

**Comment by dlip** [comment]
@flexagoon I think what is happening is that the overlay in nixos-module.nix isn't taking effect. 

in your `configuration.nix` can you add:

```
imports =
[
  ...
  /PATH/TO/kmonad/nix/module-base.nix
];

nixpkgs.overlays = [ (final: prev: { kmonad = final.haskellPackages.callPackage /PATH/TO/kmonad/nix/default.nix { }; });
```

See more https://nixos.wiki/wiki/Overlays#Using_overlays

**Comment by slotThe** [comment]
I will close this for now as it seems solved @flexagoon feel free to report back in case something's still off

**Comment by flexagoon** [comment]
@slotThe I can't report if it's fixed or not since I've already switched to a flake-based configuration

**Comment by fedoranvar** [comment]
@flexagoon 

Dobrogo tebe zdraviya!

I've copied your way of installing kmonad by flake, but i have an error

![image](https://user-images.githubusercontent.com/52028706/152082469-dfde0854-358f-4931-b60c-08a36b1e28b5.png)

have you encountered this before?

Thank you!
