### ISSUE TITLE
connect_failed asio.system:2

### ISSUE THREAD

**Issue by robbienohra** [kmonad/kmonad#375]
I managed to successfully build `kmonad`

I execute the following:

```
sudo /Users/robbienohra/Documents/kmonad/.stack-work/install/x86_64-osx/755a4d462cf166b356af50df5f15dcecc15717687ee2d008bc3c5133603406de/8.10.4/bin/kmonad ~/Documents/mod-dh/kmonad/colemak-dh-extend-ansi.kbd --log-level debug
```

And I get these connect failure messages.

I've granted the `kmonad` binary input monitoring permissions so not sure why there would be a connectivity issue.

```
Received event: Release <ctl>
Running hooks
Emitting: Release <ctl>
connect_failed asio.system:2
connect_failed asio.system:2
connect_failed asio.system:2
connect_failed asio.system:2
connect_failed asio.system:2
connect_failed asio.system:2
connect_failed asio.system:2
connect_failed asio.system:2
connect_failed asio.system:2
connect_failed asio.system:2

--------------------------------------------------------------------------------
Received event: Press <f>
Running hooks
Registering untimed hook: 18
Emitting: Press <t>

--------------------------------------------------------------------------------
Received event: Release <f>
Running hooks
Emitting: Release <t>
connect_failed asio.system:2
connect_failed asio.system:2
connect_failed asio.system:2
```

The underlying kbd config is pointing at the internal keyboard

```
input  (iokit-name "Apple Internal Keyboard / Trackpad")
output (kext)
```

The keys seem to be getting registered in the debug logs when I type but no characters are actually omitted if I try typing any text anywhere.

I'm on Big Sur and running this Alacritty (Alacritty also has input monitoring permissions)

**Comment by MuhammedZakir** [comment]
Your dext's version? The command to find that and the needed dext version (which is `1.15.0`) is documented in `doc/installation.md` [1].

[1] https://github.com/kmonad/kmonad/blob/master/doc/installation.md#installing-the-dext
