### ISSUE TITLE
Disable release event for modifier keys

### ISSUE THREAD

**Issue by JohannesNE** [kmonad/kmonad#383]
Using home row mods with tap-hold-next-release, i will sometimes regret holding meta (a-key) and release it, causing an accidental opening of the system launcher. 

Is there any way to only have the hold-keys work in combination with an other key?

My key is defined like this:
Ma (tap-hold-next-release 200 a lmet)

I want this behaviour:
Ta -> 'a'
Pa 300 Ra -> Nothing

**Comment by Ultrahalf** [comment]
ah
