### ISSUE TITLE
Solution for using kmonad with bluetooth keyboard

### ISSUE THREAD

**Issue by SalmanFarooqShiekh** [kmonad/kmonad#384]
Solved: https://github.com/kmonad/kmonad/issues/384#issuecomment-975864397

I read [#178](https://github.com/kmonad/kmonad/issues/178#issue-796928466) and decided that I need to write my own udev rule and a small script to relaunch kmonad with the correct device file everytime my bluetooth keyboard is connected.

So far, I have been able to write the following udev rule:
```
ACTION=="add",  \
ATTRS{name}=="AnnePro2 Keyboard", \
RUN+="/home/salman/.config/kmonad/annepro2/launch.fish"
```
Which runs `launch.fish` on successful bluetooth connection but only the "simple" commands in it are run e.g. the `sed` and and I think also the`kill` command: 
```
#!/usr/bin/fish

# update the kmonad config file to use the new device file
# that AnnePro2 got assigned on bluetooth connection
set dev_file /dev/input/(grep -B 1 -A 9 "AnnePro2 Keyboard" /proc/bus/input/devices | grep -o -E 'event[0-9]+')
sed -i -e "s:/dev/input/event[0-9]*:$dev_file:g" (dirname (status --current-file))/config.kbd

# kill existing relevant kmonad instance if it didn't die on its own when AnnePro2 was disconnected
sudo kill (pgrep -f annepro2/config.kbd)[1]

# start new kmonad instance with the updated config file
sudo kmonad (dirname (status --current-file))/config.kbd
```
The `kmonad` command seems to have no effect and it doesn't start. I searched around for this issue and found out that this script to be run by udev doesn't inherit all the environment variables which might be stopping the `kmonad` command from running correctly. `launch.fish` works fine and kmonad works when I run it manually from command line.

Can anybody tell me why the last line of the `launch.fish` script is not running correctly when the script is run by udev?

EDIT: Okay miraculously udev is running `launch.fish` correctly after last night without any changes and kmonad is correctly starting from `launch.fish` but now, the keyboard hangs up after sometime until dis/reconnected.

**Comment by mkraemer** [comment]
I'm using a udev rule to create a symlink for my bluetooth keyboard:

```
 ~ cat /etc/udev/rules.d/keychron-k7.rules
ATTRS{name}=="Keychron K7", SYMLINK+="keychron-k7"
```

This will create the symlink `/dev/keychron-k7`:


```
 ~ ls /dev/keychron-k7
lrwxrwxrwx 1 root root 13 Nov 22 20:38 /dev/keychron-k7 -> input/event19
```

I can then reference the symlink in my kmonad config:

```
 ~ head ~/.config/kmonad/keychron-k7.kbd 
(defcfg
  input (device-file "/dev/keychron-k7")
  output (uinput-sink "Kmonad: Keychron K7")

  fallthrough true

  allow-cmd true
)
```


I've also combined this with a systemd path unit which starts kmonad with the appropriate config file when the keyboard is connected:

```
 ~ cat ~/.config/systemd/user/kmonad@.service 
[Unit]
Description=kmonad

[Service]
ExecStart=/usr/bin/kmonad %h/.config/kmonad/%i.kbd
Restart=always
RestartSec=5
StandardOutput=null
StandardError=null

[Install]
WantedBy=sway-session.target

```

```
 ~ cat ~/.config/systemd/user/kmonad@keychron-k7.path 
[Unit]
Description=start kmonad for keychron k7
StartLimitIntervalSec=400
StartLimitBurst=3

[Path]
PathExists=/dev/keychron-k7

[Install]
WantedBy=sway-session.target%    
```

**Comment by daraul** [comment]
Following @mkraemer's example I managed to get udev to create a device at a reliable path for my kinesis. I don't understand which of those files automatically restarts the kmonad service when the keyboard pops up, though. `~/.config/systemd/user/kmonad@keychron-k7.path`?

**Comment by MuhammedZakir** [comment]
After trying to understand @mkraemer's example, I found that you only need one systemd unit file (correct me if I am wrong).

```service
# ~/.config/systemd/user/kmonad@.service

[Unit]
Description=Start KMonad for %i
StartLimitIntervalSec=1 min
StartLimitBurst=3

[Path]
PathExists=/dev/%i

[Service]
ExecStart=/usr/bin/kmonad %h/.config/kmonad/%i.kbd
Restart=always
RestartSec=5
StandardOutput=null
StandardError=null

[Install]
WantedBy=sway-session.target
```

Then, start it using `systemd --user start kmonad@keychron-k7`. For more details, search `template` in `systemd.unit` manpage.

**Comment by xxxserxxx** [comment]
For people looking for another solution that doesn't require editing udev rules, I wrote [an entirely userspace solution](https://hg.sr.ht/~ser/kbplug) a while ago. What it *can't* do is process complex workflows; for example, `setxkbmap -device` requires a device ID that isn't available through udev, which requires calling `xinput` to find from the udev name. This necessitates another script, which (in my case) I have `kbplug` run when it matches a udev rule:

```sh
#!/bin/bash

setxkbmap -device $(xinput -list | grep -Po 'Shine\s+id=\K\d+(?=.*keyboard)') us -option compose:ralt
if [[ $? -ne 0 ]]; then
	printf "Error!\n"
	printf "xinput -list | grep -Po 'Shine\s+id=\K\d+(?=.*keyboard)' => %s\n" $(xinput -list | grep -Po 'Shine\s+id=\K\d+(?=.*keyboard)')
	printf "All shines:\n"
	xinput -list | grep 'Shine'
fi
```

My `kbplug` rule for this keyboard looks like this:

```json
{ "rules": [ {
                        "action": "add",
                        "env": {
                                "ACTION": "add",
                                "SUBSYSTEM": "input",
                                "ID_INPUT_KEYBOARD": "1",
                                "NAME": "ZSA Technology Labs Inc ErgoDox EZ Shine"
                        },
                        "run": [
                                ["/bin/bash", "/home/ser/.local/bin/ergoplug"],
                                ["/usr/bin/bluetoothctl", "power", "on"]
                        ]
                }
        ]
}
```

The bluetooth rule is because some rule I set up years ago keeps powering down my bluetooth chip if there's nothing connected; when this keyboard is plugged in, I know I'm on the dock so I turn bluetooth back on. I have a couple of keyboards I use in different situations, which is why I wrote this in the first place.

Anyway, I'd have loved to have solved this differently, but every solution required changing something at root, which I generally try to avoid; maybe it'll be useful for someone else.

**Comment by haferburg** [comment]
Could someone delete the comment by @MuhammedZakir above? It's wrong and completely missed the point of mkraemer's post. I don't know why they would write it without even testing it themselves.
https://github.com/kmonad/kmonad/issues/384#issuecomment-1051066481

**Comment by SalmanFarooqShiekh** [comment]
@slotThe I can open a PR in kmonad-contrib for the solution by @mkraemer, 

I re-did something similar on my own with a wired external keyboard today,  totally forgetting I had posted this all this time ago.
