### ISSUE TITLE
[FEATURE REQUEST] Query kmonad for the layer currently being used

### ISSUE THREAD

**Issue by zim0369** [kmonad/kmonad#392]
Can we have something similar to `kmonad -c` which outputs the name of the current layer. I want to write a script that integrates with an applet to tell me what layer I'm currently using. 

I only use the hold-on a key feature to switch to a layer but in some cases switching to the next layer on a single keypress would only be useful when there's an indicator.

**Comment by slotThe** [comment]
You can use `cmd-button` to execute an arbitrary shell-script before pressing the key or after releasing it.  Depending on how you interact with that applet, that might already be enough

**Comment by zim0369** [comment]
Oh. I certainly did not know about that. Thank you!
