### ISSUE TITLE
cmd-button wouldn't work

### ISSUE THREAD

**Issue by zim0369** [kmonad/kmonad#401]
```
ins  (tap-macro (cmd-button "stalonetray") (layer-switch qwerty))
cmd  (cmd-button "./home/zim/launch.sh")
cmds (cmd-button "chromium")
```
Wouldn't work

**Comment by slotThe** [comment]
As advised in the [tutorial](https://github.com/kmonad/kmonad/blob/master/keymap/tutorial.kbd#L67) or the [quick-reference](https://github.com/kmonad/kmonad/blob/master/doc/quick-reference.md#other-configuration-options), you probably have to enable `allow-cmd`

**Comment by zim0369** [comment]
It is enabled.

**Comment by slotThe** [comment]
What does `kmonad -ldebug` output?  Perhaps there is some PATH/permissions issue

**Comment by zim0369** [comment]
kmonad: /dev/uinput: openFd: permission denied (Permission denied)

**Comment by slotThe** [comment]
So, uh, kmonad is not even running then; can't really react to command buttons :P

See [here](https://github.com/kmonad/kmonad/blob/master/doc/faq.md#q-how-do-i-get-uinput-permissions) for all of the uinput permisions stuff

**Comment by zim0369** [comment]
After following the steps I get a new error:
```
Opening KeySink
Registering Uinput device
Opening KeySource
Initiating ioctl grab
Closing KeySink
Unregistering Uinput device
Closing Uinput device file
kmonad: Could not perform IOCTL grab on: /dev/input/by-path/platform-i8042-serio-0-event-kbd
```

**Comment by slotThe** [comment]
Check that the file actually exists

> And btw I was able to use kmonad just fine the entire time, even now. I was just unable to use cmd-button except for the echo command.

Do you perhaps have kmonad already running?  That would explain the errors, at least (the keyboard is already grabbed so we can't do that ourselves)

**Comment by zim0369** [comment]
Yes, kmonad is running the entire time.

**Comment by MuhammedZakir** [comment]
> Yes, kmonad is running the entire time.

You can only run 1 KMonad for a device at a time [1]. Before starting KMonad, kill any running KMonad process for that keybaord.

[1] Some keyboards show up in `/dev/input` as 2 devices - one for normal keys and one for multimedia/application keys (`browser`, `mail`, `search`, etc.).

**Comment by zim0369** [comment]
After turing off kmonad I was able to run `kmonad -ldebug` just fine.

**Comment by slotThe** [comment]
So... where are we standing here?  @zim0369 did this fix your issue?

**Comment by zim0369** [comment]
No. It isn't fixed yet. I'm using a turnaround rn. 

I don't know what to do as `kmonad -ldebug` runs successfully after turning kmonad off and wouldn't when it's on. What to do further? 

I'm sorry that I haven't been responsive in this thread due to exams. Now I'm free.

**Comment by zim0369** [comment]
[](https://imgur.com/gVOCZQT)

**Comment by slotThe** [comment]
Seems like the issue is fixed?

**Comment by zim0369** [comment]
> Seems like the issue is fixed?
no

**Comment by MuhammedZakir** [comment]
> the cmd-button worked only when `kmonad -ldebug /path/to/file` was running.

When you start KMonad for real, how do I run it? I think the issue is probably due to incorrect `PATH` env var.

**Comment by zim0369** [comment]
> > the cmd-button worked only when `kmonad -ldebug /path/to/file` was running.
> 
> When you start KMonad for real, how do you run it? I think the issue is probably due to incorrect `PATH` env var.

```
[Unit]
Description=Kmonad keyboard utility

[Service]
Type=simple
ExecStart=/usr/bin/kmonad /home/zim/.kmonad.kbd

[Install]
WantedBy=multi-user.target
```

**Comment by MuhammedZakir** [comment]
And, is the commands you wanna run in `$PATH`?

Try:

```clojure
(cmd-button "{ which -a <cmd> || echo \"$PATH\"; } > ~/kmonad_cmd.txt }")
```

**Comment by zim0369** [comment]
> And, are the commands you want to run in `$PATH`? Try:
> 
> ```clojure
> (cmd-button "{ which -a <cmd> || echo \"$PATH\"; } > ~/kmonad_cmd.txt")
> ```

That did not write to any file.

Yes, the command I was trying to run is in $PATH.

/usr/bin/neovide

**Comment by MuhammedZakir** [comment]
Did you replace `<cmd>` with your command (`neovide`?)? Also, don't forget to restart the service for KMonad after changing the config.

**Comment by zim0369** [comment]
> Did you replace `<cmd>` with your command (`neovide`?)? Also, don't forget to restart the service for KMonad after changing the config.

Yes, I did replace it with neovide. And did restart the service.

**Comment by gerardbosch** [comment]
I see you're using systemd to start KMonad. Are you running it as "systemd user unit" (`systemctl --user`) or a "system-wide unit".

I've recently faced similar problems with `$PATH`. The snippet @MuhammedZakir gave you should write something. Try using a different path for the output, just in case: `> /tmp/kmonad_cmd.txt`.

---
So...
in my case I'm starting kmonad as systemd user (see the unit here [~/.config/systemd/user/kmonad.service](https://github.com/gerardbosch/dotfiles-linux/blob/3f3772591292109c2f3127f9f70515a706435293/home/.config/systemd/user/kmonad.service)):

```console
systemd --user enable kmonad; systemd --user start kmonad
```
And what happened to me is that when I manually started/restarted KMonad (via `systemctl --user`), all commands in user PATH were working. BUT, after reboot, despite KMonad being auto-started, user PATH was not set.

I guess that this happens as when systemd loads kmonad, user PATH is not set yet (I update user PATH in `~/.profile`, and I guess systemd does not load .profile). So, I solved it by doing `systemd --user restart kmonad` after desktop is loaded via [~/.config/autostart/kmonad.desktop](https://github.com/gerardbosch/dotfiles-linux/blob/f31329de931a7f05b117f64c47164990c4bd55fe/home/.config/autostart/kmonad.desktop), this way user PATH is properly set.

P.S. Maybe another way to do it is calling `systemctl --user import-environment PATH` in some place, so when systemd auto starts kmonad, the PATH is set, but I don't know where should I place this command so it works for auto-started services :-/ If anyone knows more on this, happy to listen :)

**Comment by MuhammedZakir** [comment]
@zim0369 : Try using `-l info` cli flag in your service to see what happens when you execute shell commands.

---

For setting env:

1. `systemctl --user import-environment PATH`: You can create a new service with a command like:
```sh
zsh -li -c 'systemctl --user import-environemnt PATH'
```

Then add this service as dependency in your other services.

2. Use `Environment` or `EnvironmentFile` in your service.

See other options: https://wiki.archlinux.org/title/Systemd/User#Environment_variables.

**Comment by zim0369** [comment]
> cat /etc/systemd/system/kmon.service
```
[Unit]
Description=Kmonad keyboard utility

[Service]
Type=simple
ExecStart=/usr/bin/kmonad /home/zim/.kmonad.kbd

[Install]
WantedBy=multi-user.target
```
This is my service file. 
I can enable/start the `kmon` by `systemctl enable/start kmon`. 
I disabled the service and then tried to enable it with:
```systemctl --user enable kmon```
but it gave me an error:
```
> systemctl --user enable kmon
Failed to enable unit: Unit file kmon.service does not exist.
```

**Comment by gerardbosch** [comment]
I think in your setup it is normal that the last command is failing, as your kmon service is stored in /etc/... so it is a "system service" not a "user service".

But I guess that system services (as well as user services) should both have /usr/bin already in the PATH. That's what looks strange, that /usr/bin/ isn't in the PATH. Try to debug the PATH writing it down to a file when kmonad started by systemd.

**Comment by zim0369** [comment]
but it is in path:
```
> which neovide
/usr/bin/neovide
> echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
```

**Comment by gerardbosch** [comment]
Hi @zim0369, I think this is the PATH you as a logged user see. But you should try to see which is the PATH systemd has when starting KMonad. I can show you my config in case it can help you. Notice the following:

- I'm starting KMonad via systemd as a user (`systemctl --user enable`),
- so units are stored in my homedir
- If I login with another user (or root), kmonad is not started (can't imagine how anyone else would feel with my keyboard setup)

Here the systemd unit:
https://github.com/gerardbosch/dotfiles-linux/blob/main/home/.config/systemd/user/kmonad.service

Here I restart the service upon desktop login so user PATH gets properly set (as I commented before, path is set OK when I do `systemctl --user start kmonad`, but after reboot it does not work):
https://github.com/gerardbosch/dotfiles-linux/blob/main/home/.config/autostart/kmonad.desktop

You can debug this changing
`Exec=systemctl --user restart kmonad`
by
`Exec=echo $PATH > /tmp/systemd-user-path`

You can see in my KMonad config that I'm using custom comands in user PATH, e.g. `run-detach` or `workspace-focus`. I would implement this scripts specifically for each platform in case I move to MacOS:
https://github.com/gerardbosch/dotfiles/blob/master/home/.config/kmonad/mi-keyboard.kbd

Hope that helps!

**Comment by zim0369** [comment]
> Hi @zim0369, I think this is the PATH you as a logged user see. But you should try to see which is the PATH systemd has when starting KMonad. I can show you my config in case it can help you. Notice the following:
> 
> * I'm starting KMonad via systemd as a user (`systemctl --user enable`),
> * so units are stored in my homedir
> * If I login with another user (or root), kmonad is not started (can't imagine how anyone else would feel with my keyboard setup)
> 
> Here the systemd unit: https://github.com/gerardbosch/dotfiles-linux/blob/main/home/.config/systemd/user/kmonad.service
> 
> Here I restart the service upon desktop login so user PATH gets properly set (as I commented before, path is set OK when I do `systemctl --user start kmonad`, but after reboot it does not work): https://github.com/gerardbosch/dotfiles-linux/blob/main/home/.config/autostart/kmonad.desktop
> 
> You can debug this changing `Exec=systemctl --user restart kmonad` by `Exec=echo $PATH > /tmp/systemd-user-path`
> 
> (point_up I'm assuming here that your desktop environment or window manager supports the Freedesktop XDG autostart)
> 
> You can see in my KMonad config that I'm using custom comands in user PATH, e.g. `run-detach` or `workspace-focus`. I would implement this scripts specifically for each platform in case I move to MacOS: https://github.com/gerardbosch/dotfiles/blob/master/home/.config/kmonad/mi-keyboard.kbd
> 
> Hope that helps!

Now I have successfully set it up as a `user` service but `cmd-button` still wouldn't work. The commands don't get executed. I tried different commands but they don't work. I tried commands for launching different applications but they wouldn't launch.

**Comment by zim0369** [comment]
I guess the issue was related to command helper but definitely not related to kmonad. Most of the tiling window managers are facing this issue for me. In dwm:
```
#define SHCMD(cmd)                                                             \
  {                                                                            \
    .v = (const char *[]) { "/bin/sh", "-c", cmd, NULL }                       \
  }

```

Ig here I need to change `/bin/sh` to something else. I don't know what exactly.
Closing this.

**Comment by jhonasn** [comment]
@zim0369 I'm having the same problem here on awesomewm, so if I understand it right, the `SHCMD` will be executed in every command executed by dwm, is that right? I'm looking how to do this in awesome but didn't find yet, the name of this action is command helper?

**Comment by jhonasn** [comment]
I tried as @gerardbosch suggested run kmonad service as user and it worked, but stopped working on login screen... I use void linux here so in case someone find this useful you need to change the last line of you service `run` fie to:
```
exec chpst -u jojo /usr/bin/kmonad /home/jojo/.config/kmonad/config.kbd || exit 1
```
I still couldn't find how to change the awesome wm command spawner for this, so if someone knows please let me know.

**Comment by BlueDuDe04** [comment]
I got it working on systemd root service. For anyone else coming here looking for a solution.

There are two problems when trying to run commands this way.

1) If you do get the app opening. It will be running as root which is not good for the security and safety of your system. Solution: sudo -u \<user\>

2) There are like 9 environment variables that kmonad.service will have access to. Just try:
```(defalias Env (cmd-button "env >> /tmp/kmonad_env.txt"))```
So important stuff like XDG_RUNTIME_DIR or DISPLAY or WAYLAND_DISPLAY is not there.
An app may not open if it knows nothing about your system.
Solution: Apply the necessary environment variable in the cmd.

Solution:

```cmd-button "sudo -u <user> <key[1]>=<value[1]> <key[n]>=<value[n]> <cmd>"```

Examples:

If you want system wide binding to change volume:
```cmd-button "sudo -u BlueDuDe XDG_RUNTIME_DIR=/run/user/1000 pamixer -i 10" ;; increase volume```
```cmd-button "sudo -u BlueDuDe XDG_RUNTIME_DIR=/run/user/1000 pamixer -d 10" ;; decrease volume```
```cmd-button "sudo -u BlueDuDe XDG_RUNTIME_DIR=/run/user/1000 pamixer -t" ;; mute volume```

If you would like a system wide binding for a terminal:
```cmd-button "sudo -u BlueDuDe DISPLAY=:0 XDG_RUNTIME_DIR=/run/user/1000 WAYLAND_DISPLAY=wayland-1 wezterm"```
Works in x11 and wayland natively

The Great thing about this approach is that all of this is system wide!
So your keyboard layout will remain in the login!
Best of all is you have a sxhkd like setup on boot up and will work with both x11 and wayland!
