### ISSUE TITLE
Please add some explanation to the user keymap

### ISSUE THREAD

**Issue by lhzw** [kmonad/kmonad#404]
It will much better to add a README.md to the user keymap, easily to read the keymap.
With this https://www.reddit.com/r/vim/comments/pmqj0x/kmonad_gives_you_superpowers_youll_end_up_using/, will be much easier to read this file:
https://github.com/kmonad/kmonad/blob/master/keymap/user/zim0369/kmonad.kbd

@zim0369 
Thank you very much.

**Comment by slotThe** [comment]
I'm not sure I understand; we already have a [quick-reference](https://github.com/kmonad/kmonad/blob/master/doc/quick-reference.md) (of sorts).  The tutorial being an executable keyboard file has a lot of advantages I think, like one being able to easily try out new stuff

What exactly do you feel is missing from the current tutorial (apart from it not being a markdown file)?

**Comment by lhzw** [comment]
Er, tutorial is good, but not that practical. We're talking about different things.
I'd like to learn from the users' keymaps, but I'm not a master yet, so I (the other beginners) cannot understand the keymap very quickly, I'd like to find some good ideas from others config. It will be wonderful if there's a explanation with the keymap.
