### ISSUE TITLE
Unable to use sticky-key

### ISSUE THREAD

**Issue by zim0369** [kmonad/kmonad#409]
```
ssf  (tap-hold-next-release 150 (sticky-key 500 lsft) (layer-toggle rshift))
mod  (tap-hold-next-release 150 (sticky-key 500 lmet) lmet)
```
This throws a debug error:
Unrecognized compose-char.

**Comment by slotThe** [comment]
I'm not trying to be rude, but how do you expect anyone to help you with this little information?  

  - What version of kmonad are you running?  
  - What's your config file?  
  - What's the exact parsing error you're getting?

My guess is that you're on a tagged release, in which case sticky keys aren't released yet.  You'll need to update to the git version

**Comment by zim0369** [comment]
Using the git version solved the issue. closing.
