### ISSUE TITLE
Simulating Cmd-Tab/Alt-Tab on a layer with other types of buttons also

### ISSUE THREAD

**Issue by canadaduane** [kmonad/kmonad#417]
So in every major operating system, there's this ability to switch applications via Cmd-Tab or Alt-Tab. The key sequence usually goes something like this (using the tutorial mini-language):

`Pcmd` `Ttab` `Ttab` `Tgrv` `Rcmd`

(This would pop open a visual screen overlay that shows the application switcher moving two spots over, then one back on the Mac).

On Linux (my system) it might be similar, but I might use Alt instead of Cmd (`Palt` `Ttab` `Ttab` `Tgrv` `Ralt`).

So the question is, how do we simulate this in kmonad, especially when the "alt" key can work differently with other keys (for example, if I also wanted to substitute A-c (alt-c) for S-ins (shift-insert))?

Specific example: say I want "alt" key to send "C-z" when I hit "A-z" but I want "alt" key to also do what it did before when A-tab is pressed? Currently allowing "tab" key to fall through would simulate a tab key press, with the held alt modifier missing.

Edited to add a note: What I'm *actually* trying to achieve is a Mac-like shortcut key experience on a Linux machine. This involves switching modifier keys, and a lot of versatility around what each key does in context, which seems a perfect match for kmonad's advanced capabilities.

**Comment by Ultrahalf** [comment]
> Specific example: say I want "alt" key to send "C-z" when I hit "A-z" but I want "alt" key to also do what it did before when A-tab is pressed? Currently allowing "tab" key to fall through would simulate a tab key press, with the held alt modifier missing.

you can make alt as a layer key 
and map z to C-z and A-tab respectively

**Comment by canadaduane** [comment]
> you can make alt as a layer key
> and map z to C-z and A-tab respectively

So this is what I tried first, but the effect is that A-tab switches to another application instantly, with subsequent "Ttab"s alternating being apps 1 and 2:

starting state is app 1 (of 3)
starting state -> Palt Ttab Ralt -> switches to app 2
starting state -> Palt Ttab Ttab Ralt -> switches to app1 (note also that the app switcher visual overlay does not show up)

What I want:
starting state -> Palt Ttab Ttab Ralt -> switches to app3 (with visual app switcher overlay shown while `alt` is pressed).

I think what's happening is each "Ttab" in between the "press" and "release" of `alt` is sending a fully "around" wrapped "Palt Ttab Ralt", and the "Ralt" is what's closing the visual app switcher.

**Comment by Ultrahalf** [comment]
try using debug flag
or 
`xev | awk -F'[ )]+' '/^KeyPress/ { a[NR+2] } NR in a { printf "%-3s %s\n", $5, $8 }'` <- this won't work bcz it requires the window to be in focus
so you can know whats happening

**Comment by canadaduane** [comment]
You're right that `xev` doesn't help much here, because app switching takes the focus away and I don't get to see all keypresses.

When I use `keyd -m` (monitor mode) and turn off any udev grabbing services, I can see the keypress sequence I *hope* to simulate ("AT Translated Set 2 keyboard" is the name of my laptop's built-in kb):

```
AT Translated Set 2 keyboard: alt down
AT Translated Set 2 keyboard: tab down
AT Translated Set 2 keyboard: tab up
AT Translated Set 2 keyboard: tab down
AT Translated Set 2 keyboard: tab up
AT Translated Set 2 keyboard: alt up
```

**Comment by Ultrahalf** [comment]
you can use kmonad  pathtoconfig -ldebug

**Comment by canadaduane** [comment]
For additional context, there's a [great thread over on keyd](https://github.com/rvaiya/keyd/issues/48) where the keyd author and I are discussing the core of the problem and potential ways to solve it. I'd love it if both kmonad and keyd could somehow support this Mac-to-Linux use case.

@Ultrahalf you've been very helpful, if you're up for it, I'd sure appreciate it if you could read [rvaiya's comment](https://github.com/rvaiya/keyd/issues/48#issuecomment-969940611) as it lays out the core of the problem I'm trying to overcome.

My current attempt in kmonad is to try something like this (doesn't work):

```
(defalias
  mac (tap-next (layout-switch mac-main) A-(layout-toggle mac-meta)))
```

Where I bind "@mac" to the Alt key. The `A-(layout-toggle mac-meta)` portion works for the App Switcher! However, tap-next never detects that one of the `mac-main` keys is pressed and so the tap-next doesn't call any of the A-* substitution key combos in `mac-main` (such as `A-c` mapping to `C-ins`).

The "missing piece" here is how to trigger a state change when *any* of the key combos in `mac-main` are pressed. `tap-next` seems really close to the task, but I haven't seen the "tapping" key parameter be anything but a concrete key in other kmonad examples, so I'm not sure if I'm using it correctly.

**Comment by Ultrahalf** [comment]
can you post the kmonad config here?

**Comment by Ultrahalf** [comment]
```clojure
  (defalias
  py C-c
  ps C-v
  tog A-(layer-toggle qwerty)
  )
  
 (deflayer something
 esc
 grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
 tab  q    w    e    r    t    y    u    i    o    p    [    ]    \
 caps a    s    d    f    g    h    j    k    l    ;    '    ret
 lsft z    x    c    v    b    n    m    ,    .    /    rsft
 lctl lmet @tog           spc            ralt rmet cmp  rctl
 )
 
   (deflayer qwerty
   esc
   `   1   2   3   4   5   6  7   8   9   0   -   =  bspc
   tab  q    w    e    r    t    y    u    i    o    p    [    ] \\
   caps a    s    d    f    g    h    j    k    l    ;    '    ret
   lsft z    x    @py    @ps    b    n    m    ,    .    /    rsft
   lctl lmet lalt           spc            ralt rmet cmp  rctl
  )
```
from logs

when `alt`+`c` is pressed gives me `ctrl`-`c`
```diff
--------------------------------------------------------------------------------
Received event: Press <alt>
Running hooks
Pushed layer to stack: qwerty
 1. qwerty
Base-layer: colemakdh

Registering untimed hook: 1
+ Emitting: Press <alt>

--------------------------------------------------------------------------------
+Received event: Press <c>
Running hooks
Registering untimed hook: 2
+Emitting: Press <ctl>
Registering untimed hook: 3
+Emitting: Press <c>
^CClosing process: emitter_proc
Closing KeySource
Releasing ioctl grab
Closing KeySink
Unregistering Uinput device
Closing Uinput device file
```
 when `alt`+`v` is pressed gives me `ctrl`+`v`
```diff
--------------------------------------------------------------------------------
+ Received event: Press <alt>
Running hooks
Pushed layer to stack: qwerty
 1. qwerty
Base-layer: colemakdh

Registering untimed hook: 1
+ Emitting: Press <alt>

--------------------------------------------------------------------------------
+ Received event: Press <v>
Running hooks
Registering untimed hook: 2
+ Emitting: Press <ctl>
Registering untimed hook: 3
+ Emitting: Press <v>
^[^
--------------------------------------------------------------------------------
Received event: Release <v>
Running hooks
Registering untimed hook: 4
Emitting: Release <v>
Emitting: Release <ctl>

--------------------------------------------------------------------------------
Received event: Release <alt>
Running hooks
Popped layer from stack: qwerty
Base-layer: colemakdh

Emitting: Release <alt>
```
this is sort of hard to explain because my window manager does not have the app switcher, 

when `alt`+`tab`+`tab` is pressed gives 
```diff
--------------------------------------------------------------------------------
Received event: Press <alt>
Running hooks
Pushed layer to stack: qwerty
 1. qwerty
Base-layer: colemakdh

+ Emitting: Press <alt>
Registering untimed hook: 1

--------------------------------------------------------------------------------
+ Received event: Press <tab>
Running hooks
Registering untimed hook: 2
Registering untimed hook: 3
+ Emitting: Press <tab>
^[	
--------------------------------------------------------------------------------
+ Received event: Release <tab>
Running hooks
Registering untimed hook: 4
Emitting: Release <tab>

--------------------------------------------------------------------------------
Received event: Press <tab>
Running hooks
Registering untimed hook: 5
Registering untimed hook: 6
Emitting: Press <tab>
^[	
--------------------------------------------------------------------------------
Received event: Release <tab>
Running hooks
Registering untimed hook: 7
Emitting: Release <tab>

--------------------------------------------------------------------------------
Received event: Press <tab>
Running hooks
Registering untimed hook: 8
Registering untimed hook: 9
Emitting: Press <tab>
^[	
--------------------------------------------------------------------------------
Received event: Release <tab>
Running hooks
Registering untimed hook: 10
Emitting: Release <tab>

--------------------------------------------------------------------------------
Received event: Press <tab>
Running hooks
Registering untimed hook: 11
Registering untimed hook: 12
Emitting: Press <tab>
^[	
--------------------------------------------------------------------------------
Received event: Release <tab>
Running hooks
Registering untimed hook: 13
Emitting: Release <tab>

--------------------------------------------------------------------------------
+ Received event: Press <tab>
Running hooks
Registering untimed hook: 14
Registering untimed hook: 15
Emitting: Press <tab>
^[	
--------------------------------------------------------------------------------
+ Received event: Release <tab>
Running hooks
Registering untimed hook: 16
Emitting: Release <tab>

--------------------------------------------------------------------------------
+ Received event: Release <alt>
Running hooks
+ Popped layer from stack: qwerty
Base-layer: colemakdh

+ Emitting: Release <alt>

--------------------------------------------------------------------------------
Received event: Press <ctl>
Running hooks
Registering untimed hook: 17
Emitting: Press <ctl>

--------------------------------------------------------------------------------
Received event: Press <c>
Running hooks
Registering untimed hook: 18
Registering untimed hook: 19
Emitting: Press <c>
^CClosing process: emitter_proc
Closing KeySource
Releasing ioctl grab
Closing KeySink
Unregistering Uinput device
Closing Uinput device file
```
highlighted few, not sure if this does what you wanted from what i saw in other commet alt was released on every tab
from log atleast that should not happen. You can copy the snippet and try it

**Comment by canadaduane** [comment]
Sorry for the delay, I was away from my Linux laptop for a few hours.

Here is my default.kbd file:
```
(defcfg
  input  (device-file "/dev/input/by-path/platform-i8042-serio-0-event-kbd")
  output (uinput-sink "kmonad virtual keyboard")
  fallthrough true
  allow-cmd true
)

(defsrc
  grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab  q    w    e    r    t    y    u    i    o    p    [    ]    \
  caps a    s    d    f    g    h    j    k    l    ;    '    ret
  lsft z    x    c    v    b    n    m    ,    .    /    rsft
  lctl lmet lalt           spc            ralt rctl left up down rght
)

(defalias
  cut S-del
  cpy C-ins
  pst S-ins
  xcp (tap-next esc lctl)
  mac A-(layer-toggle meta-mac)
  ;;mac (tap-next (layer-toggle main-mac) A-(layer-toggle meta-mac))
  grv S-tab
)


(deflayer initial
  grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab  q    w    e    r    t    y    u    i    o    p    [    ]    \
  @xcp a    s    d    f    g    h    j    k    l    ;    '    ret
  lsft z    x    c    v    b    n    m    ,    .    /    rsft
  lctl lmet @mac           spc            ralt rctl left up down rght
)

(deflayer main-mac
  _    1    A-2  A-3  A-4  A-5  A-6  A-7  A-8  A-9  A-0  C--  C-+  _
  _    C-q  C-w  C-e  C-r  C-t  C-y  C-u  C-i  C-o  C-p  C-[  C-]  _
  _    C-a  C-s  C-d  C-f  C-g  C-h  C-j  C-k  C-l  C-;  _    _
  _    C-z  @cut @cpy @pst C-b  C-n  C-m  C-,  _    _    _
  _    _    _              _              _    _       _    _  _   _
)

(deflayer meta-mac
  @grv _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    @cut @cpy @pst _    _    _    _    _    _    _
  _    _    _              _              _    _       _    _  _   _
)
```

I'm currently having a weird issue where kmonad, when started, presses "enter" repeatedly and steals my mouse (?) so that I can't test very well. I will search previous issues or file a new one separately to figure that out.

**Comment by canadaduane** [comment]
> from logs
> when alt+c is pressed gives me ctrl-c

@Ultrahalf This is close, but right above the `ctrl-c` is "Emitting: Press <alt>", which means the `ctrl-c` is *actually* emitting as `alt-ctrl-c`. I want to *only* send `ctrl-c` here.

This likely means not sending `alt` until we know which path we're in:
1. user pressed `alt` -> don't emit anything yet
2a. `alt down` followed by `tab down` means we're in the state where it's ok to send `alt down` (and to faithfully reproduce `tab down` / `tab up` events, followed by a final `alt up`).
2b. `alt down` followed by any of the keys in the `main-mac` layout means DON'T send `alt down`, send whatever the key sequence is in the `main-mac` layout.

**Comment by canadaduane** [comment]
We discovered an alternative in the keyd discussion that may be easier:

- use `meta` key instead of `alt` (because apps tend to ignore `meta down` `meta up` sequences--with the exception of the gnome-mutter overlay, which can be disabled; `alt down` and `alt up` sequences OTOH will tend to activate various unwanted side-effects such as menus, dropdowns, or focus flashes)
- send `meta up` as soon as we know we are in the `main-mac` layout, prior to sending any key combinations in that layer (this makes `ctrl-c` behave as `ctrl-c` instead of `meta-ctrl-c`.

So the question for kmonad is: is there a way to "escape" an (around ...) sequence--some kind of early terminate?

**Comment by Ultrahalf** [comment]
> So the question for kmonad is: is there a way to "escape" an (around ...) sequence--some kind of early terminate?

from this https://github.com/kmonad/kmonad/blob/master/doc/quick-reference.md maybe around-next-timeout? 

the idea of defining `A-(layer....)` was not to lose the alt and I thought making tab as a alias would result in `alt`+`tab`+`tab` 
as `alt` +`tab` + `alt` + `tab`

**Comment by Ultrahalf** [comment]
```clojure
  tog (tap-next (layer-next qwerty) sft)
``` 
this lets me to do:
tap `alt` release `alt` 
tap `c`  release `c` 
=> `ctl`+ `c`
__________________
tap `alt`
tap `c`  release `c` 
release `alt` 
=> `C`



 _________________________________________
so with this 
> My current attempt in kmonad is to try something like this (doesn't work):
(defalias
  mac (tap-next (layout-switch mac-main) A-(layout-toggle mac-meta)))
Where I bind "@mac" to the Alt key. The A-(layout-toggle mac-meta) portion works for the App Switcher! However, tap-next never detects that one of the mac-main keys is pressed and so the tap-next doesn't call any of the A-* substitution key combos in mac-main (such as A-c mapping to C-ins).
The "missing piece" here is how to trigger a state change when any of the key combos in mac-main are pressed. tap-next seems really close to the task, but I haven't seen the "tapping" button of tap-next be anything but a concrete key in other kmonad examples, so I'm not sure if I'm using it correctly.

```diff
- mac (tap-next (layout-switch mac-main) A-(layout-toggle mac-meta)))
+ mac (tap-next (layout-next mac-main) A-(layout-toggle mac-meta)))
```
you tap n release `alt` and press intended key in `mac-main layer`. If thats what you were trying to do?

**Comment by canadaduane** [comment]
> you tap n release alt and press intended key in mac-main layer. If thats what you were trying to do?

Thanks for hanging in there with me! This isn't quite what I was after. Here's a timing diagram with "actual key events" and "virtual key events" side by side.

I want the `alt` key to do BOTH of these, depending on which key is pressed after `alt` (`tab` vs `v` in this example):

![Scan 2](https://user-images.githubusercontent.com/129/142157996-b0844873-a8a7-4e43-ad6c-797cffbcc9b6.jpeg)

**Comment by Ultrahalf** [comment]
not sure how to do it in kmonad. But there is xdotool in which you can clearmodifiers emulate keydown/keyup keypress ...etc

**Comment by MuhammedZakir** [comment]
There is no way to send a key up or key down only event [1] in KMonad. So "releasing" a modifier key is not possible - which is what you want.

[1] They're not exposed to user.

---

If you are okay with a verbose way, remove `A-` from `@mac` button and move `A-` to inside layer. That is,
```clojure
;; alias
mac (layer-toggle meta-mac)


;; inside base layer
;;
;; lalt => @mac


;; inside `meta-mac` layer
;;
;; tab => A-tab
;; z => C-z
;; c => S-ins

;; add `A-` before every buttons that should work with `Alt`
;; like you did with `tab`
;; e.g. A-a , A-b , A-f , A-; , etc.
```

**Comment by canadaduane** [comment]
Thanks again for all the assistance. We were able to get state switching working in keyd here: https://github.com/rvaiya/keyd/issues/48

I hope this discussion has been helpful. I sure learned a lot about these two wonderful open source "keyboard freedom" services :)

**Comment by arkadiy-telegin** [comment]
Reopening since the functionality of separately pressing and releasing keys was implemented recently as `(press-only KEY)` and `(release-only KEY)` respectively.

Can we now realize the desired Alt-Tab behaviour with these new additions?
