### ISSUE TITLE
MacOS bluetooth keyboard reconnection support in Monterey, etc

### ISSUE THREAD

**Issue by chadbailey59** [kmonad/kmonad#418]
I'm hoping to be able to contribute a fix for this as time allows, but I wanted to publicly document the issue so that 1) someone might do it before me, and 2) it's searchable if others encounter this issue.

I'm running `0.4.1, commit 0eacad7a1a3bb5cf9b8569c477acf9f47a6a53e3` on MacOS Monterey 12.0.1 on a M1 MacBook Air. I'm currently running it in a terminal window with `sudo` to iron out these kinds of issues, but I eventually hope to run it in the background all the time.

It's working great after getting the correct dext installed, but every time my bluetooth keyboard (KeyChron K6, but others do it too) wakes from sleep, I get the following error that crashes kmonad:

```
Encountered error in KeySource: [Cannot interpret mac switch: 2,Cannot translate from mac keycode: (1,4294967295)]
kmonad: [Cannot interpret mac switch: 2,Cannot translate from mac keycode: (1,4294967295)]
```

When I run `kmonad` again, it works just fine. I'm guessing we need to just no-op whatever's sending that keycode, which is what I'm going to try, but I need to learn me a bit of Haskell first. :)

**Comment by MuhammedZakir** [comment]
If I am right, this should be fixed in `keycode-refactor` branch. Can you try building from that branch? Aliases for multi-media/application-specific keys such as volume buttons are missing and names maybe different [1]. You'll have to use `keynames` [2] for those.

[1] https://github.com/kmonad/kmonad/blob/1d2276069fd781c4518082f1b36f3b2880667e79/src/KMonad/App/Parser/Keycode.hs#L130-L146
[2] https://github.com/kmonad/kmonad/blob/1d2276069fd781c4518082f1b36f3b2880667e79/src/KMonad/Util/Keyboard/Mac.hs#L122

**Comment by chadbailey59** [comment]
Success! After a `stack clean --full` and a few build attempts, I've been running a binary on my Mac for ~18 hours now. It survived several bluetooth keyboard sleep/wake cycles, as well as a few sleeps and wakes of the computer itself. I'd consider this fixed. :)

I did end up removing these lines to work around a runtime issue: https://github.com/kmonad/kmonad/blob/1d2276069fd781c4518082f1b36f3b2880667e79/src/KMonad/App/Parser/Keycode.hs#L102-L104

When I would run the app, I would get `kmonad: NonExistentTarget ("documents","docs")`. When I removed line 102 I got the same error for line 103, and then for 104. I presume I'd just need to define those elsewhere, but since I don't plan on using a keyboard with those keys, deleting the lines fixed it for me.

Happy to help test when you're ready to merge this branch!

**Comment by MuhammedZakir** [comment]
Glad to know it's fixed. :-)

> I did end up removing these lines to work around a runtime issue:
> 
> `https://github.com/kmonad/kmonad/blob/1d2276069fd781c4518082f1b36f3b2880667e79/src/KMonad/App/Parser/Keycode.hs#L102-L104`
> 
> When I would run the app, I would get `kmonad: NonExistentTarget ("documents","docs")`. When I removed line 102 I got the same error for line 103, and then for 104. I presume I'd just need to define those elsewhere, but since I don't plan on using a keyboard with those keys, deleting the lines fixed it for me.

It's a cross-platform issue. For macOS, those keys are probably not defined or named differently.

In case someone want to use them, use Karabiner-EventViewer to find the keycode (usage & usage page) of those keys and check `kmonad/src/KMonad/Util/Keyboard/Mac.hs` for the names corresponding to those keycodes. Loading that file in GHCi and printing `keycodeNames` will make searching easier.

> Happy to help test when you're ready to merge this branch!

You can follow PR - "Keycode refactor" (#_372_).

**Comment by powelleric** [comment]
> When I run `kmonad` again, it works just fine. I'm guessing we need to just no-op whatever's sending that keycode, which is what I'm going to try, but I need to learn me a bit of Haskell first. :)

You may be interested in the issue I created which contains a script to restart kmonad after such errors: https://github.com/kmonad/kmonad/issues/432

**Comment by kevinstadler** [comment]
> Success! After a `stack clean --full` and a few build attempts, I've been running a binary on my Mac for ~18 hours now. It survived several bluetooth keyboard sleep/wake cycles, as well as a few sleeps and wakes of the computer itself. I'd consider this fixed. :)

Do you remember what changes you had to make to get the keycode-refactor branch to build? I can't get past the following linker error (which might have to do with me still running 10.14/Mojave).

```
kmonad> build (lib + exe)
Preprocessing library for kmonad-0.4.1..
Building library for kmonad-0.4.1..
Preprocessing executable 'kmonad' for kmonad-0.4.1..
Building executable 'kmonad' for kmonad-0.4.1..
Linking .stack-work/dist/x86_64-osx/Cabal-3.2.1.0/build/kmonad/kmonad ...
Undefined symbols for architecture x86_64:
  "_release_kb", referenced from:
      _Ls2EfU_info in libHSkmonad-0.4.1-9tuSAU8413hGcXbxTBSktN.a(IOKitSource.o)
  "_grab_kb", referenced from:
      _Lc2EgA_info in libHSkmonad-0.4.1-9tuSAU8413hGcXbxTBSktN.a(IOKitSource.o)
      _Lr2E4h_info in libHSkmonad-0.4.1-9tuSAU8413hGcXbxTBSktN.a(IOKitSource.o)
  "_wait_key", referenced from:
      _Lc2Ehp_info in libHSkmonad-0.4.1-9tuSAU8413hGcXbxTBSktN.a(IOKitSource.o)
  "_send_key", referenced from:
      _Lc2Gkd_info in libHSkmonad-0.4.1-9tuSAU8413hGcXbxTBSktN.a(Ext.o)
      _Lc2GjL_info in libHSkmonad-0.4.1-9tuSAU8413hGcXbxTBSktN.a(Ext.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`gcc' failed in phase `Linker'. (Exit code: 1)

--  While building package kmonad-0.4.1 (scroll up to its section to see the error) using:
      /Users/k/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.4 --builddir=.stack-work/dist/x86_64-osx/Cabal-3.2.1.0 build lib:kmonad exe:kmonad --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

**Comment by kevinstadler** [comment]
Nevermind, I forgot to add the appropriate build arguments for Mojave, all working now (after commenting out the 3 lines noted above):
```
stack install --flag kmonad:kext --extra-include-dirs=c_src/mac/Karabiner-VirtualHIDDevice/dist/include
```

@MuhammedZakir is there some documentation about the new keycode naming convention somewhere? I'm first getting the following error (presumably because according to the new convention `fn` is now called `Fn`):

```
kmonad: Parse error at 29:47:
   |
29 | (defalias fn (around (layer-toggle function) fn))
   |                                               ^
unexpected 'n'
expecting button
```

but after renaming it to `Fn` I just get lots of source+layer length mismatch errors instead of complaints about unknown keynames. Is it possible that f1 - f12 have been renamed as well?

**Comment by MuhammedZakir** [comment]
> @MuhammedZakir is there some documentation about the new keycode naming convention somewhere? I'm first getting the following error (presumably because according to the new convention `fn` is now called `Fn`):
> 
> ```
> kmonad: Parse error at 29:47:
>    |
> 29 | (defalias fn (around (layer-toggle function) fn))
>    |                                               ^
> unexpected 'n'
> expecting button
> ```

There is a wip doc about keynames and key codes. But I recommend you to look at the source code if possible. See https://github.com/kmonad/kmonad/issues/418#issuecomment-969106029.

> but after renaming it to `Fn` I just get lots of source+layer length mismatch errors instead of complaints about unknown keynames. Is it possible that f1 - f12 have been renamed as well?

Those length mismatch errors are most probably due to missing aliases. In `keycode-refactor` branch, lots of key aliases are not added. That is also why you're getting an error for `fn` (although it would've been better if I used `fn` as the keyname). For those keys, you will have to replace the aliases with their corresponding keynames. Click the above link -- it contains links to aliases and keynames.
