### ISSUE TITLE
Published vscode-kmonad

### ISSUE THREAD

**Issue by canadaduane** [kmonad/kmonad#419]
I couldn't find kmonad config file language support for vscode, so I created this extension:

https://github.com/canadaduane/vscode-kmonad
https://marketplace.visualstudio.com/items?itemName=canadaduane.vscode-kmonad

If it's useful, feel free to share around.

**Comment by slotThe** [comment]
This is neat, thanks!  If you want, you can open a PR to add add it to [this list](https://github.com/kmonad/kmonad#editor-support-for-the-configuration-language)

**Comment by slotThe** [comment]
Closed via  #454
