### ISSUE TITLE
cmd-button / what kind of string is used in cmd-button?

### ISSUE THREAD

**Issue by molleweide** [kmonad/kmonad#421]
Hi,

What does this mean:

```shell
kmonad: Parse error at 443:36:
    |
443 |   sleep (cmd-button "osascript -e 'tell application \"Finder\" to sleep'")
    |                                    ^
unexpected 't'
expecting button
```

**Comment by MuhammedZakir** [comment]
I think it is an issue with the parser. What happens if escape single quotes?

**Comment by molleweide** [comment]
yes escaping the single quotes fixe it!

**Comment by slotThe** [comment]
On Tue, Nov 16 2021 10:23, molleweide wrote:
> yes escaping the single quotes fixe it!

(This is fixed in latest HEAD)
