### ISSUE TITLE
Can around-next take multiple args?

### ISSUE THREAD

**Issue by canadaduane** [kmonad/kmonad#424]
In the [tutorial.kbd](https://github.com/kmonad/kmonad/blob/master/keymap/tutorial.kbd) it says that `layer-next` is equivalent to:

```
(around-next (layer-toggle layer-name) some-button)
```

But everywhere else that I see `around-next` in use, there is only one argument passed. For example, the [quick-reference](https://github.com/kmonad/kmonad/blob/master/doc/quick-reference.md) provides the following example:

```
(defalias ns  (around-next sft))  ;; Shift the next press
```

Should the tutorial instead say `(around (around-next (layer-toggle layer-name)) some-button)`?

**Comment by slotThe** [comment]
You're right, this seems to be a mistake in the tutorial.

On Tue, Nov 16 2021 21:18, Duane Johnson wrote:
> Should the tutorial instead say `(around (around-next (layer-toggle
> layer-name)) some-button)`?

I believe it should just be

    (around-next (layer-toggle layer-name))

because around-next already works around the next key, so specifying
more here is not necessary.
