### ISSUE TITLE
Compose sequences appear to open menu

### ISSUE THREAD

**Issue by sakuragasaki46** [kmonad/kmonad#427]
Hi, Linux user here (Ubuntu 20.04, I compiled kmonad via stack from master).

In my own layout, I have some accented characters (ä ü ö) and I would like to add more.  The point is:

* without `cmp-seq` at the beginning, the characters of the sequences are entered alone, such as  "a "u "o;
* with `cmp-seq compose`, a strange thing happens: 
![Schermata da 2021-11-18 14-52-13_cpy](https://user-images.githubusercontent.com/48103762/142428341-e65c2ece-45e9-40e0-b9cf-0701837accdf.png)

Boom, context menu gets open.

The underlying layout (XKB one) is a plain American one.

Changing the Menu key to Multi_key in the underlying layout ~~did not fix~~ actually fixed the issue 😊

Also, `;` in shifted layer returns `:` why???

**Comment by slotThe** [comment]
> Changing the Menu key to Multi_key in the underlying layout ~did not fix~ actually fixed the issue blush

Since this seems fixed, I'm closing

> Also, `;` in shifted layer returns `:` why???

This is the standard shift of `;` on a US layout
