### ISSUE TITLE
Mismatch between length of defsrc and deflayer, even if they are equal

### ISSUE THREAD

**Issue by harshasrisri** [kmonad/kmonad#429]
I'm running `kmonad` from the `keycode-refactor` branch (coming from #408). I have a [very similar config](https://github.com/harshasrisri/dotRC/blob/main/dot/config/kmonad/config.kbd) running just fine on Linux and I'm trying to get this config to work on macOS Catalina:
```
(defcfg
  input  (iokit-name "my-macos-keyboard")
  output (dext)
  fallthrough true
) 

(defsrc
   grv  1   2   3   4   5   6   7   8   9   0   -   =    del
   tab   q   w   e   r   t   y   u   i   o   p   [   ]   \
   caps   a   s   d   f   g   h   j   k   l   ;   '      ret
   lsft    z   x   c   v   b   n   m   ,   .   /        rsft
   fn lctl lmet lalt     spc     ralt rctl left down up rght
)

(defalias 
    xct (tap-next esc rctl)

    ` (tap-hold 222 ` ~)
    1 (tap-hold 222 1 !)
    2 (tap-hold 222 2 @)
    3 (tap-hold 222 3 #)
    4 (tap-hold 222 4 $)
    5 (tap-hold 222 5 %)
    6 (tap-hold 222 6 ^)
    7 (tap-hold 222 7 &)
    8 (tap-hold 222 8 *)
    9 (tap-hold 222 9 \()
    0 (tap-hold 222 0 \))
    - (tap-hold 222 - \_)
    = (tap-hold 222 = +)
    [ (tap-hold 222 [ {)
    ] (tap-hold 222 ] })
    ; (tap-hold 222 ; :)
    , (tap-hold 222 , <)
    . (tap-hold 222 . >)
    / (tap-hold 222 / ?)
    \ (tap-hold 222 \ |)
    ' (tap-hold 222 ' ")

    nvl (layer-toggle NaviLay)
)

(deflayer default
   @`  @1  @2  @3  @4  @5  @6  @7  @8  @9  @0  @-  @=   bspc
   tab  q   w   e   r   t   y   u   i   o   p   @[   @]   @\
   @nvl  a   s   d   f   g   h   j   k   l   @;   @'     ret
   lsft   z   x   c   v   b   n   m   @,   @.   @/      rsft
   fn lctl lalt lmet     spc     @xct rmet left down up rght
)

(deflayer NaviLay
   _  f1  f2  f3  f4  f5  f6  f7  f8  f9  f10  f11  f12  del
   _   _   _   _   _   _   home pgdn pgup end   _  _  _  _
   _    _   _   _   _   _   left down  up  right   _  _  _
   _     _   _   _   _   _   _   _   _   _   _       _
   _   _   _   _       _        _    _    _    _    _    _
)
```

However, I'm getting this error:
```
sudo .stack-work/install/x86_64-osx/e8c2a31e735785b5362526b6d69495d73d3dc8a62a582d65160a03efce6b76d4/8.10.4/bin/kmonad ~/.config-mac.kbd
kmonad: Mismatch between length of 'defsrc' and deflayer <NaviLay>
Source length: 65
Layer length: 64
```

I've counted the entries in all my layers and they are equal. Not sure how to proceed.

**Comment by slotThe** [comment]
>  fn lctl lmet lalt     spc     ralt rctl left down up rght

There is no `fn` key and so it parses this as `f` and `n`.  You're looking for `wkup`

**Comment by harshasrisri** [comment]
I know that is true for Linux. Didn't know it was the case with MacOS too. 

In any case, `wkup` seems to be disabled on the `keycode-refactor` branch and a comment notes that it needs to be cleaned up along with a few others. 🤷🏾‍♂️

**Comment by harshasrisri** [comment]
Tagging @thoelze1 for MacOS help. 🆘

**Comment by MuhammedZakir** [comment]
It is `Fn` (capital F). You can find all the names here -- https://github.com/kmonad/kmonad/blob/keycode-refactor/src/KMonad/Util/Keyboard/Mac.hs#L122-L197.

**Comment by MuhammedZakir** [comment]
> > fn lctl lmet lalt     spc     ralt rctl left down up rght
> 
> There is no `fn` key and so it parses this as `f` and `n`. You're looking for `wkup`

IMO, we should enforce whitespace between buttons in layers. This way we can avoid wrong parsings and throw a helpful error msg about wrong/unknown key names.

**Comment by slotThe** [comment]
> IMO, we should enforce whitespace between buttons in layers. This way we can avoid wrong parsings and throw a helpful error msg about wrong/unknown key names.

Probably; wanting to specify keys with no whitespace inbetween doesn't sound very ergonomic anyways
