### ISSUE TITLE
Action for sticky key double press

### ISSUE THREAD

**Issue by GuAlSe** [kmonad/kmonad#433]
I want to have an action for sticky key double press.
For example: `(defalias sls (sticky-key 2000 lsft caps))` is just sticky shift but sticky shift + sticky shift = caps.
Could you add something like this?

**Comment by slotThe** [comment]
It's on the roadmap! (well, on mine, anyways :)  

Already tracked in https://github.com/kmonad/kmonad/issues/319, so I'm closing this for now
