### ISSUE TITLE
Map to `KeyMenu` not working

### ISSUE THREAD

**Issue by NiloCK** [kmonad/kmonad#441]
Hi all - previous windows AHK user new to kmonad. Looks great but having an issue getting started. Ubuntu 20.04.3, Gnome 3.36.8, X11, 64 bit.

```
(defsrc
  caps
)

(deflayer myMap
  menu
)
```
Does not trigger context menus for me with the caps key. For reference,

```
(defsrc
  a
)

(deflayer myMap
  menu
)
```
also does **not** work, but

```
(defsrc
  caps
)

(deflayer myMap
  a
)
```

works fine.

Maybe noteworthy: my physical keyboard does not have a menu key, and my machine had a linux install from the manufacturer (Lenovo). Is it possible that my Ubuntu install itself is missing the key? Any ideas how I could test for this? (readers of this issue probably know a lot more than me about how Ubuntu interacts with keyboards than I do....)

**Comment by NiloCK** [comment]
I have partially resolved this by including 
```
(defalias
  men S-F10
)
```
as a go-between. It's not clear to me whether Ubuntu's Shift-F10 is 100% equivalent to the menu key press, but I guess experience will tell.

I'll leave this open in case the failure of the `menu` map is worth tracking, but persons can feel free to close.

**Comment by slotThe** [comment]
I would guess `menu` does not do what one thinks it does (at it sometimes happens with key names), so I'll close this

**Comment by MuhammedZakir** [comment]
IIRC, the key to trigger context menu is named compose key (`comp`, `cmps` or `cmp`).
