### ISSUE TITLE
Layer with Ú gives error

### ISSUE THREAD

**Issue by italovieira** [kmonad/kmonad#447]
KMonad: 0.4.1-2
OS: Arch Linux

------------------------------------------------------------------

I'm defining the following layer for use with compose key.

```
(deflayer upper-portuguese
  +~   _    _    _    _    _    +^   _    _    _    _    _    _    _
  _    _    _    É    _    _    _    Ú    Í    Ó    _    _    _    _
  _    Á    _    _    _    _    _    _    _    _    _    _    _
  _    _    _    Ç    _    _    _    _    _    _    _    _
  _    _    _              _              _    _    _    _
)
```

Unfortunately this throws a error:
```
kmonad: Parse error at 53:38:
   |
53 |   _    _    _    É    _    _    _    Ú    Í    Ó    _    _    _    _
   |                                      ^
unexpected 'Ú'
expecting ')'
```

All the other letters works. The only problem is with 'Ú'. Is this a bug or I missed something?

**Comment by slotThe** [comment]
This is missing in the released version, but is present in master (added in 216b56cb37507ee1c2b2e83b531df0d412e8486b)
