### ISSUE TITLE
Vim-inspired digraph support

### ISSUE THREAD

**Issue by fenuks** [kmonad/kmonad#472]
Vim has very neat and easy to use feature called [digraphs](https://vimhelp.org/digraph.txt.html). In short, it allows to insert unicode symbol by pressing two keys in insert mode, after pressing <c-k>, e.g. to insert `ü` user needs to press `<c-k>u:`. Key chords are pretty intuitive and easy to guess, they don't need to be memorized. It would be great to be able to do this on keyboard level. It's not impossible to achieve this functionality with current feature set of KMonad, but I believe it's not practical to define thousands of digraphs e.g. with layers.

Vim defines many of these, so KMonad would be probably best to have them built-in, and as well allowing defining new ones with 
```lisp
(defdigraph
  (u : ü)
)
```

**Comment by slotThe** [comment]
I think what you're decriping is the current state of our compose key support, no?  We already have [a lot](https://github.com/kmonad/kmonad/blob/master/src/KMonad/Keyboard/ComposeSeq.hs#L34) of these for usage with a set compose key, e.g. `cmps " u` would give you `ü`.

**Comment by fenuks** [comment]
Thank you, I misunderstood what compose is for. I read more on a subject, and indeed something similar can be achieved with compose.

For the posterity:
There is script to generate `~/.XCompose` from digraphs [here](https://github.com/mkoskar/xcompose-vim). Additionally, I mapped <c-k> in my vim layer into compose key, in my case it's `pause` to make it as close as possible to vim experience.

So, the issue can be closed, but I would like to ask one unrelated question, if you don't mind. It seems nobody files issue for this which is surprising, but if I am not mistaken, KMonad cannot record dynamic macros (i.e. not static macros that can be specified in .kbd config)? QMK has limited support for this, and vim has full-blown option to record key strokes into register with `q<a-z>`, where <a-z> is name of register (recording is stopped next time q pressed in normal mode), and replay it with `@<a-z>`.

**Comment by slotThe** [comment]
On Fri, Jan 21 2022 11:45, fenuks wrote:
> So, the issue can be closed, but I would like to ask one unrelated
> question, if you don't mind. It seems nobody files issue for this
> which is surprising, but if I am not mistaken, KMonad cannot record
> dynamic macros (i.e. not static macros that can be specified in .kbd
> config)?

Indeed, this is not something that we support right now...

> QMK has limited support for this, and vim has full-blown option to
> record key strokes into register with `q<a-z>`, where <a-z> is name of
> register (recording is stopped next time q pressed in normal mode),
> and replay it with `@<a-z>`.

...and this may be one of the reasons for it—I think most people just
use the keyboard macro facilities of their editor to do this

**Comment by fenuks** [comment]
> ...and this may be one of the reasons for it—I think most people just
use the keyboard macro facilities of their editor to do this

I think the issue there is size of memory in keyboards might be main factor. QMK supports only two predefined registers. Editor macros are fantastic, and surely work better than keyboard-level macros, because they are well-integrated into editor, but on the other hand, 99.99% of apps don't have this feature, and people have to use external utilities, like AutoKey.

Thank you for your help, and since I was able to emulate digraph support, I'm closing the issue.
