### ISSUE TITLE
Unable to use ctrl+(up/down/left/right) on remapped keys

### ISSUE THREAD

**Issue by minasouliman** [kmonad/kmonad#473]
With the help of [this response ](https://github.com/kmonad/kmonad/issues/82#issuecomment-1003761019) I've been able to compile the keycode-refactor branch on windows and everything I've tested so far works! With the exception of the ability to hit ctrl+(up/down/left/right) from my remapped keys. Here is the setup --

```lisp

(defalias
  cp   C-c
  pt   C-v
  cut  C-x
  all  C-a
  cwn  A-f4
  ctb  C-w
  un   C-z
  re   C-y
  mnu  S-f10

  num (tap-hold-next-release 100 esc (layer-toggle numbers))
  sym (layer-toggle symbols)
  arr (layer-toggle arrows)
)
(defalias
    m_a (tap-hold-next-release 250 a lmet)
    m_s (tap-hold-next-release 250 s lalt)
    m_d (tap-hold-next-release 160 d lsft)
    m_f (tap-hold-next-release 250 f rctl)
    m_j (tap-hold-next-release 250 j rctl)
    m_k (tap-hold-next-release 160 k rsft)
    m_l (tap-hold-next-release 250 l ralt)
    m_; (tap-hold-next-release 250 ; rmet)
    m_v (tap-hold-next-release 250 v @sym)
    m_n (tap-hold-next-release 250 n @sym)
    m_g (tap-hold-next-release 250 g @arr)

)
(deflayer qwerty
tab		q	w	e	r	t	y	u	i	o	p	[	]	\
@num		a	s	@m_d	@m_f	@m_g	h	@m_j	@m_k	@m_l	;	'
lsft		z	x	c	@m_v	b	@m_n	m	,	.	/	rsft
	lctl	lmet	lalt						lalt	ssrq	rctl
)


(deflayer numbers
_		_	_	_	_	_	-	7	8	9	+	_	_	_
_		_	_	_	_	_	*	4	5	6	=	_
_		_	_	_	_	_	0	1	2	3	_	_
	_	_	_						_	_	_
)

(deflayer symbols
_		<	>	{	}	_	-	&	*	\_	+	_	_	_
_		\(	\)	[	]	_	_	$	%	^	_	_
_		_	_	_	_	_	`	!	@	#	_	_
	_	_	_						_	_	_
)

(deflayer arrows
_		_	_	_	_	XX	XX	XX	pgup	XX	XX	_	_	_
_		_	_	_	_	_	left	down	up	rght	XX	_
_		_	_	_	_	_	XX	pgdn	XX	XX	XX	_
	_	_	_						_	_	_
)

```

So for example, holding down g will activate the arrows layer, at which point I can hold d which passes through to qwerty and presses down on shift, then I can use hjkl to select text. This works perfectly. But the same is not true for ctrl. So the following sequence --

```
hold g (arrow layer) -> hold f (ctrl) -> try hjkl to navigate word by word or line by line
```

In this case, nothing happens...tested it with multiple application and it never registers any presses. What makes it even weirder is that the following combination works just fine --

```
hold g (arrow layer) -> hold f (ctrl) -> press i or m for pgup or pgdn
```

this works perfectly for navigating tabs in a web browser.

So far, the remapped ctrl + arrow keys are the only combinations that do not work. I thought that maybe the issue is that jkl are also remapped as home row mods, but they work just fine when shift is the modifier, even repeat is working fine in that case. I also played around with rctl and lctl and got nothing (aside: had to remap the ralt to lalt because when pressing ralt + space to bring up ueli on windows, it would completely disable the keyboard within the application....noooo idea why that's the case, but the remapping to lalt works for now as a workaround).

Happy to share any additional debugging info :) Also wanted to say that I love this repo! Makes me want to pick up Haskell to help with dev and testing

**Comment by slotThe** [comment]
What happens when you try to hold g, hold f, and try to press any of
hjkl without kmonad?  Do the keys come out at all?

**Comment by minasouliman** [comment]
huh, never thought about trying that out, no keys register when I do that. hold g and hold f and then every other key on the keyboard works except the entire row with g/f on it. so hold g, hold f then qwertyuiop as well as the bottom letters row work just fine. but hold g, hold f and asdhjkl;' all do not register anything. But this doesn't generalize to any two letter combinations on that row. So for example hold a, hold s, press any other letter on the entire keyboard and it registers.

you think it's likely more of a windows quirk or possible a keyboard hardware issue?

**Comment by slotThe** [comment]
On Fri, Jan 21 2022 22:56, minasouliman wrote:
> you think it's likely more of a windows quirk or possible a keyboard
> hardware issue?

Yeah I think it's more like a hardware limitation on your keyboard; more
specifically, the lack of n-key rollover.  Lots of "cheap" (and some not
so cheap :) keyboards have this

**Comment by minasouliman** [comment]
gotcha, that makes a ton of sense (raises fists at lenovo). Oh well, I'll maybe see about moving around the homerow mods to get that key combo to work since it's fairly annoying to not be able to use it.

much appreciated! :)
