### ISSUE TITLE
Layout Visualization

### ISSUE THREAD

**Issue by mnesarco** [kmonad/kmonad#474]
Hi Friends,
Thank you for this amazing tool. 

I have created a small (WIP) tool to allow visualization of kmonad files in keyboard layout editor (http://www.keyboard-layout-editor.com/). I share it here because it can be useful for the community.

![keyboard-layout (12)](https://user-images.githubusercontent.com/1087317/150805172-4a0bc938-f905-46d5-a9dc-ddb34546ace9.jpg)

# Project:
https://github.com/mnesarco/kmonad_dump

# Disclaimer: 
I have no relation with http://www.keyboard-layout-editor.com/ development.

**Comment by tristanCadet** [comment]
It looks pretty handy ! Do you have any plan to make the reverse conversion possible too, i.e. from KLE to Kmonad files ? 

If we can go both ways it basically gives a GUI to Kmonad, which is really neat and would enable less technical users to tweak their layout more easily.

**Comment by mnesarco** [comment]
Hi @tristanCadet ,
It could be a better idea to develop a KMonad UI in Flutter. KLE is apparently unmaintained :(

**Comment by tristanCadet** [comment]
That's true, on the other hand developing a UI from scratch seems like it would take a while so it's maybe not worth it. Also being interoperable with KLE would bring more visibility to Kmonad

**Comment by mnesarco** [comment]
KLE is good for visualization, but it lacks a proper semantic model.

| KMonad                                                  | KLE                     |
|---------------------------------------------------------|-------------------------|
| Deep semantic model                                     | Flat rendering model    |
| Layer concept                                           | Keycap label position   |
| Alias                                                   | XX                      |
| Button layout depends on context (current layer + mods) | Fixed                   |
| XX                                                      | Geometry representation |
| XX                                                      | Style                   |

- Going from KMonad Model to KLE is easy, just add some layout hints (done in this repo)
- Going from KLE to KMonad is hard, requires a lot more info not supported currently in KLE.

So to use KLE as a GUI for KMonad it is required to fork KLE to add the missing parts (Because the project is unmaintained so they do not accept PRs). It is probably more productive to create a GUI from scratch. It could be an interesting project.

**Comment by slotThe** [comment]
Tangentially related to https://github.com/kmonad/kmonad/issues/507 

From my point of view, I think it would be a decent compromise to create a TUI with [brick](https://github.com/jtdaugherty/brick/) or something
