### ISSUE TITLE
windows mpv arrow keys not working

### ISSUE THREAD

**Issue by ixzh** [kmonad/kmonad#485]
when pressing arrow keys to seek forward/backward in mpv, they are interpreted as Key Press 2(down) 4(left) 6(right) 8(up). In other  apps the arrow keys are working fine. 

below is my defsrc:
```
 (defsrc
   esc     f1      f2      f3      f4      f5      f6      f7      f8      f9      f10     f11     f12     prnt    ins     del
   `       1       2       3       4       5       6       7       8       9       0       -       =       bspc
   tab     q       w       e       r       t       y       u       i       o       p       [       ]       \
   caps    a       s       d       f       g       h       j       k       l       ;       '       ret
   lsft    z       x       c       v       b       n       m       ,       .       /       rsft    up
   lctl            lmet    lalt    spc                     ralt    rctrl                   left    down    rght
 )
```

How can I resolve this? currently I can't fast forward or rewind in mpv.  Thanks!

**Comment by slotThe** [comment]
What does `evtest` say?  If it reports the correct keys then that sounds like something on the mpv side (though I can say that it is working just fine for me with regards to arrow keys)

**Comment by ixzh** [comment]
> it is working just fine for me with regards to arrow keys

in mpv? I'm on windows no evtest?

**Comment by slotThe** [comment]
On Tue, Feb 15 2022 21:13, HALS wrote:
>> it is working just fine for me with regards to arrow keys
> in mpv?

Yes

> I'm on windows no evtest?

Well, then I don't know :)

**Comment by ixzh** [comment]
arrow keys to seek forward/backward works on my linux laptop as well. Just mpv intepret the keys as KP2 KP4 KP6 and KP8....maybe it is windows or mpv problem. Thanks will close the issue.
