### ISSUE TITLE
Keyboard + Mouse combination not working if remapped

### ISSUE THREAD

**Issue by glyh** [kmonad/kmonad#492]
I've remapped Caps to Shift when hold, Esc when release. I expect holding the key and middle mouse wheel would be treated as shift+ middle mouse(Which is a hot key in Blender), but it won't work. I guess Kmonad only take care of keys but not mouse inputs?

**Comment by slotThe** [comment]
On Sat, Feb 26 2022 06:00, ***@***.*** wrote:
> I guess Kmonad only take care of keys but not mouse inputs?

Indeed, there is no mouse support right now and so keyboard + mouse
combinations won't be recognized properly.

**Comment by slotThe** [comment]
Closing as a duplicate of #150
