### ISSUE TITLE
how to escape @ character?

### ISSUE THREAD

**Issue by zmitry** [kmonad/kmonad#497]
`\` doesn't work

<img width="701" alt="image" src="https://user-images.githubusercontent.com/14317641/156902130-e7b59581-b29a-421d-b08b-06339c3c336c.png">

**Comment by slotThe** [comment]
On Sat, Mar 05 2022 14:43, Dmitry Zherebko wrote:
> `\` doesn't work
>
> <img width="701" alt="image"
> src="https://user-images.githubusercontent.com/14317641/156902130-e7b59581-b29a-421d-b08b-06339c3c336c.png">

That's not a `\`, but a `/`!  But more importantly, you don't need to
escape `@`; kmonad can parse it just fine.
