### ISSUE TITLE
Parse error parsing tutorial.kbd

### ISSUE THREAD

**Issue by mikeyj13** [kmonad/kmonad#501]
I installed kmonad via the Arch AUR. I'm running into an issue and I can't find any reports of it on the Arch website or elsewhere, so I'm sure I've got something screwed up (maybe a dependency issue?). 

Anyway, I've cloned the repo (on April 5th), and when I run `kmonad -d tutorial.kbd`, I get:

```
kmonad: Parse error at 158:3:
    |
158 |   cmp-seq-delay 5 ;; 5ms delay between each compose-key sequence press
    |   ^
unexpected 'c'
expecting ')'
```

**Comment by slotThe** [comment]
On Mon, Mar 07 2022 19:46, mikeyj wrote:
> I installed kmonad via the Arch AUR. I'm running into an issue and I
> can't find any reports of it on the Arch website or elsewhere, so I'm
> sure I've got something screwed up (maybe a dependency issue?).
>
> Anyway, I've cloned the repo (on April 5th), and when I run `kmonad -d
> tutorial.kbd`, I get:
> […]

I would guess that your version of kmonad does not yet support
cmp-seq-delay (afaik it's a new-ish feature)

**Comment by mikeyj13** [comment]
Thanks @slotThe. Looks like you are correct. The Arch package is using release 0.4.1 currently, and when I look through the source here for the release (https://github.com/kmonad/kmonad/releases/tag/0.4.1), I can see the cmp-seq is in there but not cmp-seq-delay. I'll go ahead and remove it from my config for now. Closing this issue.

**Comment by jankoettgen** [comment]
Hey everybody, I also got a similar error for my 50% keyboard, but use no fancy functions, I just wanna use the fn buttons...
This is my config:

`(defcfg
  input (low-level-hook)
  output (send-event-sink)
  ;;output (send-event-sink 300 100)
  fallthrough true
  ;;allow-cmd true

)

(defsrc
  esc   1    2    3    4    5    6    7    8    9    0    bspc
  tab   q    w    e    r    t    y    u    i    o    p    \   
  caps  a    s    d    f    g    h    j    k    l    ;    ret
  lsft  z    x    c    v    b    n    m    ,    .    /    rsft
  lctl lmet lalt  cmp  fn     spc     fn  left down up  rght
)

(defalias fn (around (layer-toggle function) fn))

(deflayer base
  esc   1    2    3    4    5    6    7    8    9    0    bspc
  tab   q    w    e    r    t    y    u    i    o    p    \   
  caps  a    s    d    f    g    h    j    k    l    ;    ret
  lsft  z    x    c    v    b    n    m    ,    .    /    rsft
  lctl lmet lalt  cmp  @fn    spc    @fn  left down up  rght

)

(deflayer function
  _    f1   f2   f3   f4   f5   f6   f7   f8   f9   f10   _
  _    _    _    _    _    _    _    _    _    _    _     _ 
  _    _    _    _    _    _    _    _    _    _    _     _
  _    _    _    _    _    _    _    _    _    _    _     _
  _    _    _    _    _       _      _    _    _    _     _   
)
`
The error I get is 
`kmonad.exe: Parse error at 15:24:
   |
15 |   lctl lmet lalt  cmp  fn     spc     fn  left down up  rght
   |                        ^
unexpected 'f'
expecting ')'`
Any idea what the issue could be?

**Comment by KaitlynEthylia** [comment]
fn tends to me handled internally by the keyboard so kmonad can't pick it up

**Comment by jankoettgen** [comment]
Ah ok thx for the quick reply. So I just ignore it in my config? 
And does this mean I can not use these buttons to switch my layers?

**Comment by KaitlynEthylia** [comment]
yes unfortunately if youre not using it for it's built in function, fn may as well be an empty key slot

**Comment by jankoettgen** [comment]
Ah good to know. But I actually could remap the buttons on the keyboard itself. So I think I can use it now. Thanks for your time
