### ISSUE TITLE
kmonad does not emit any keypresses on MacOS

### ISSUE THREAD

**Issue by chr-sa** [kmonad/kmonad#502]
I am trying to use kmonad on an M1 MacBook Air, MacOS Version 12.2.1. After some googling I got stack to build the binary:

```
kmonad --version
0.4.1, commit ca616766a6ebf36e946c2e60dbc31e583b9f8e5f
```

Trying to launch the provided template for apple leaves my keyboard not doing anything on keypresses. Launching kmonad in debug mode yields:

```
sudo kmonad keymap/template/apple.kbd -l debug

Opening KeySink
Initializing Mac key sink
Opening KeySource
Opening IOKit devices
Launching process: emitter_proc
connected

--------------------------------------------------------------------------------
Received event: Press <a>
Running hooks
Registering untimed hook: 1
Emitting: Press <a>

--------------------------------------------------------------------------------
Received event: Release <a>
Running hooks
Emitting: Release <a>

```
This seems fine to me, beside that there seems to be an `a` missing after `Emitting: Press <a>`.
I sadly have no idea how to diagnose this myself. If you need any further information I am happy to provide it.

**Comment by molleweide** [comment]
Yo! Have you turned on the kext/dext. See the macos installer instructions. I forgot to do that once and nothing happens then. I totally missed it in the docs at first but it is very important.

**Comment by chr-sa** [comment]
Hey, thanks for the reply. I totally forgot that this did not work and did not think about checking again. The activation fails because there is a newer version installed.

```
activation of org.pqrs.Karabiner-DriverKit-VirtualHIDDevice is requested
request of org.pqrs.Karabiner-DriverKit-VirtualHIDDevice is canceled because newer version (1.6.0) is already installed
request of org.pqrs.Karabiner-DriverKit-VirtualHIDDevice is failed with error: The operation couldn’t be completed. (OSSystemExtensionErrorDomain error 11.)
```

I tried using the uninstall instructions from the Karabiner-DriverKit but that failes as well:

```
bash '/Library/Application Support/org.pqrs/Karabiner-DriverKit-VirtualHIDDevice/scripts/uninstall/deactivate_driver.sh'
sudo bash '/Library/Application Support/org.pqrs/Karabiner-DriverKit-VirtualHIDDevice/scripts/uninstall/remove_files.sh'
button returned:OK
deactivation of org.pqrs.Karabiner-DriverKit-VirtualHIDDevice is requested
request of org.pqrs.Karabiner-DriverKit-VirtualHIDDevice is failed with error: The operation couldn’t be completed. (OSSystemExtensionErrorDomain error 4.)
Password:
No matching processes were found
rmdir: /Library/Application Support/org.pqrs/tmp/rootonly: Directory not empty
rmdir: /Library/Application Support/org.pqrs/tmp: Directory not empty
rmdir: /Library/Application Support/org.pqrs: Directory not empty
```
I also tried to install activate a newer version than 1.6.0, that failed with the exactly same message... I understand that this is not a problem with kmonad, but have you maybe stumbled across this as well?

**Comment by molleweide** [comment]
Rm/disable the other dext versions. I dont remember more atm. (On mobile..)

**Comment by MuhammedZakir** [comment]
For activation command, try using `forceActivate` instead of `activate`.

**Comment by chr-sa** [comment]
Thank you very much, it did work with `forceActivate`. Now everything works as expected.

**Comment by chr-sa** [comment]
Thank you very much, it did work with `forceActivate`. Now everything works as expected.
