### ISSUE TITLE
Toggle layer button but use normally otherwise

### ISSUE THREAD

**Issue by murkylife** [kmonad/kmonad#503]
I'm trying to remap my lctrl button such as pressing lctrl + any defined button in my lctrl layer works, and for anything not defined, it works as usual without kmonad doing anything.

I've set it up like:
```
fallthrough true
deflayer base with @lct in place of  lctl
(defalias lct (tap-next ctl (layer-toggle lctrl)))
(deflayer lctrl
  _    _    _    _    _    _    _    _    _    _    _    _    _          @ssf _    _     _    _    _    _    
  _    _    _    _    _    _    _    _    _    _    _    _    _    _     _    _    _     _    _    _    _
  _    _    _    _    _    _    _    _    _    _    _    _    _    _     _    _    _     _    _    _    _
  _    _    _    _    _    _    _    _    _    _    _    _    _                          _    _    _
  _    _    _    _    _    _    _    _    _    _    _    _                    _          _    _    _    _
  _    _    _              _              _    _    _    _               _    _    _     _    _   
)
```

The layer toggling is working, but this has broken stuff like ctrl+t (new tab), ctrl+w (close tab), where t and w are not defined in my lctrl layer.

I've re-read the user guide many times but I can't figure out how to get this working. Would appreciate any help!

PS: Thanks to the maintainers for this awesome project :)

**Comment by ramonwenger** [comment]
As far as I understand, this is not possible at the moment. The fallthrough just emits the event without the modifier.

It would be a cool feature though, to be able to fallthrough and pass along the modifier that was pressed.

I wonder if that would be complicated to implement. Does anyone have any pointer for that? I have not worked with the codebase before.

**Comment by murkylife** [comment]
I found an issue with a similar requirement: https://github.com/kmonad/kmonad/issues/279#issuecomment-858935107

Vermoot's suggestion of `(defalias ctrl (tap-hold-next-release 150 (layer-next lctrl) lctrl))` is working quite well, if i press ctrl, let go, and quickly press another key, i can use this to trigger any command/key on keymonad, and normal use of ctrl is working so far. 

Not exactly what i posted about, but it's satisfying my requirements :)
