### ISSUE TITLE
iso 100 template seems to erroneously reference tenkeyless

### ISSUE THREAD

**Issue by swedneck** [kmonad/kmonad#508]
"This file contains the `defsrc' configuration for a standard ISO ten-key-less
  keyboard. Modelled on a standard European 100% keyboard."

This sentence looks weird to me, since the configuration very clearly contains a numpad.

**Comment by slotThe** [comment]
Someone forgot to change this while copying the template :)  Fancy opening a PR?

**Comment by slotThe** [comment]
The template was probably copied from the ten-key less template; someone
just forgot to adjust the message.  Would you like to open a PR that
fixes this?
