### ISSUE TITLE
Kmonad Mac OSX Monterey connect_failed asio.system:13

### ISSUE THREAD

**Issue by jaddel** [kmonad/kmonad#515]
Has anyone gotten kmonad running on OSX Monterey?

I get the following error when I try to start it. 

```
  ~/d/kmonad/.s/i/x/f/8.10.4/bin   master ⇣11 ?1                                                                                                                              ✘ INT  6s  ghc-8.10.4
❯ ./kmonad /Users/max/Downloads/miryoku_kmonad-alphas_qwerty-nav_inverted-clipboard_mac-mapping_lite-kmonad_os_mac/miryoku_kmonad.kbd --log-level debug
Opening KeySink
Initializing Mac key sink
Opening KeySource
Opening IOKit devices
connect_failed asio.system:13
Launching process: emitter_proc
IOHIDDeviceOpen error: (iokit/common) not permitted
IOHIDDeviceOpen error: (iokit/common) not permitted
IOHIDDeviceOpen error: (iokit/common) not permitted
connect_failed asio.system:13
connect_failed asio.system:13
connect_failed asio.system:13
^CClosing process: emitter_proc
Closing KeySource
Closing IOKit devices
```

**Comment by MuhammedZakir** [comment]
KMonad works fine on mine (Monterey).

`connect_failed asio.system:13` -- this error is due to you running newer dext version. Reinstall the correct dext and try again. See the `doc/installation.md` for details.

**Comment by jaddel** [comment]
> KMonad works fine on mine (Monterey).
> 
> `connect_failed asio.system:13` -- this error is due to you running newer dext version. Reinstall the correct dext and try again. See `doc/installation.md` for details.

I already did that, I installed 1.15 and activated it but it didn't help.

I recompiled kmonad and yes I also tried sudo to start it.

**Comment by MuhammedZakir** [comment]
1. When activating, try `forceActivate` and restart mac.
2. Did you give input permission for the terminal you are starting `kmonad` in? If yes, toggle it - disable and re-enable input permission.
    - `IOHIDDeviceOpen error: (iokit/common) not permitted` -- this error is because of insufficient permission.

**Comment by jaddel** [comment]
> 

thx! I wasn't aware that I have to give the permissions to the terminal. Instead I gave them to the kmonad executable. 

Enventhough I hade these [errors](https://pastebin.com/cMTvYFWj) during compiling it seems to work now. Can they be a future problem?

**Comment by MuhammedZakir** [comment]
> thx! I wasn't aware that I have to give the permissions to the terminal. Instead I gave them to the kmonad executable.

You're welcome!

It's in the installation doc. If the installation doc is not clear, say it and we will make necessary changes.

> Enventhough I hade these [errors](https://pastebin.com/cMTvYFWj) during compiling it seems to work now. Can they be a future problem?

It will (hopefully) be solved when using latest dext. It's in my todo list, but I can't say any ETA. Ignore those errors for now.

For macOS users, `keycode-refactor` branch is better. However, it is missing some newly added features and fixes that are in `master`. If you don't use those, use `keycode-refactor` branch.

**Comment by jaddel** [comment]
> It's in the installation doc. If the installation doc is not clear, say it and we will make necessary changes.

Now it makes sense when I read the lines below again but still it might be helpfull for newcommers to point out explicitly that the terminal needs to be added. 

> Enable the application(s) that you will be using to execute kmonad in System Preferences > Security & Privacy > Privacy > Input Monitoring.

Also after I had compiled kmonad at first it wasn't clear to me that I couldn't just run kmonad by > kmonad /kbfile.kbd and it took me a bit to figure out that the binary was in `/kmonad/.stack-work/install/x86_64-osx/fc5ae8be280906593ee03c8c59db2e7e1e5d800bd705161cf08272d93defd837/8.10.4/bin/kmonad`
A few instuctions on how to add kmonad as cli command might also be usefull. 

I hope this helps improving the docs.

Thank you for the great work on kmonad and your quick help over here! :)

**Comment by MuhammedZakir** [comment]
> Now it makes sense when I read the lines below again but still it might be helpfull for newcommers to point out explicitly that the terminal needs to be added.

Will do.

> A few instuctions on how to add kmonad as cli command might also be usefull.

Using `stack install` command will insatll the binary in `~/.local/bin`. Adding that to your `PATH` env var, you will be able to use it without prefixing the path.
