### ISSUE TITLE
how to add a key use shift+x

### ISSUE THREAD

**Issue by lowy** [kmonad/kmonad#517]
exaple:
caps (tap-next-release C-A-spc (layer-toggle capret))
but I want to use lsft+@caps = caps
how to do?

**Comment by slotThe** [comment]
You could create an extra layer in which caps is mapped to the normal caps; this is essentially #111.  I think this kind of thing will be a lot easier after #372 is merged

**Comment by MuhammedZakir** [comment]
> I think this kind of thing will be a lot easier after #372 is merged

How so?
