### ISSUE TITLE
QUESTION: kmonad and screen blankers

### ISSUE THREAD

**Issue by xxxserxxx** [kmonad/kmonad#518]
This is a general question, not a bug: has anyone else experienced this, and if so, how did you address it?

Every so often, when I'd try to wake up my laptop I'd find the keyboard in a state such that I couldn't unlock the computer. My solution was to remote ssh into my laptop from my phone and kill kmonad. This started happening frequently enough that, about a week ago, I just disabled kmonad.

I'm sure this has to do with the suspend/resume process; devices waking up, and states being restored in the wrong order, or something, but before I spend which will undoubtedly be several days trying to figure out the cause... has anyone else experienced this?

1. I know it's an interaction with kmonad, since the behavior stops when I disable kmonad
2. I'm using Dvorak, but it's configured at the system level: `/etc/default/keyboard`, `/etc/X11/xorg.conf.d/00-keyboard.conf`, and `/etc/vconsole.conf` are all set to dvorak
3. To get kmonad to work properly, my kmonad `defsrc` is QWERTY -- I don't understand why, but if I have a dvorak mapping for `defsrc`, it produces a really interesting layout.
4. It only happens -- as far as I can tell -- after a suspend from resume. I don't often hibernate the laptop.  I have not had it happen in any other situation, plugging/unplugging keyboards, etc.

**Comment by slotThe** [comment]
As noted on IRC, this has never happened to me on GNU/Linux.  I'm a bit at a loss how one could debug this either...
