### ISSUE TITLE
Greek characters

### ISSUE THREAD

**Issue by sonjiku** [kmonad/kmonad#521]
Is it possible to type greek characters? If so, how? kmonad seems pretty cool, but if it's not possible for me to change between english and greek, I don't think I could ditch xkb.

**Comment by slotThe** [comment]
On Wed, Apr 06 2022 23:09, Sonjiku wrote:
> Is it possible to type greek characters? If so, how? kmonad seems
> pretty cool, but if it's not possible for me to change between english
> and greek, I don't think I could ditch xkb.

You can type unicode character via compose sequences.  But what you
actually want it probably to just switch to a greek layout for a certain
layer.  E.g., I have an English default layer and a German extra one;
switching between them uses cmd-button like this:

    (defalias
      ass (around (cmd-button "setxkbmap de")
                  (layer-switch qwertz))
      cmk (around (cmd-button "setxkbmap us") 
                  (layer-switch colemak)))

**Comment by sonjiku** [comment]
Thanks a lot for the reply! Indeed, switching between an English and a Greek layer is what I had in mind! Unfortunately this is what I get every time I try the mapping. This is a result of setxkbmap being run:
 
```
Authorization required, but no authorization protocol specified
Cannot open display ":0"
```

**Comment by slotThe** [comment]
Uh, are you using X11? :)

**Comment by sonjiku** [comment]
Yes, I was using X11. I followed the configuration instructions and I have fixed my config file. I managed to  achieve the result I wanted by having `grp:alt_caps_toggle` in my sway or setxkbmap, and fixing my config file. You can [have a look here](https://gist.github.com/sonjiku/21b2f43f201787c9032f12fc57f66ca7).
