### ISSUE TITLE
Temporarily Release Key

### ISSUE THREAD

**Issue by kalkronline** [kmonad/kmonad#522]
As of right now, it doesn't appear that there is a perfect solution for creating a toggle-layer button out of keys that are used as modifiers (ctrl, shift, alt). Tragically, I have muscle memory that has me pressing ctrl and i-j-k-l for use as arrow keys. 

I've gotten as close as I could possibly get with the config below:

```
(defsrc
  grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab  q    w    e    r    t    y    u    i    o    p    [    ]    \
  caps a    s    d    f    g    h    j    k    l    ;    '         ret
  lsft z    x    c    v    b    n    m    ,    .    /              rsft
  lctl lmet lalt                spc                 ralt rmet cmp  rctl
)

(defalias
  arw (around met (layer-toggle arrows))

  up  (tap-macro met up)
  dwn (tap-macro met down)
  lft (tap-macro met left)
  rit (tap-macro met right)
)

(deflayer querty
  grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab  q    w    e    r    t    y    u    i    o    p    [    ]    \
  caps a    s    d    f    g    h    j    k    l    ;    '         ret
  lsft z    x    c    v    b    n    m    ,    .    /              rsft
  @arw lctl lalt                spc                 ralt rctl cmp  @arw
)

(deflayer arrows
  _    _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    _    _    _    _    _    _    @up  _    _    _    _    _
  _    _    _    _    _    _    _    @lft @dwn @rit _    _         _
  _    _    _    _    _    _    _    _    _    _    _              _
  _    _    _                   _                   _    _    _    _
)
```

This nearly produces the desired outcome. Pressing `@arw+C` will copy any selected text (on mac), because `met` is being held by the `around` statement. Pressing `@arw+k` will behave like an unmodified down arrow because the `tap-macro` will press and (more importantly) immediately release `met`, even though `@arw` is still physically being held down. 

An issue arises if I continue to hold `@arw` after pressing `@up`, `@dwn`, `@lft`, or `@rit`. By design, meta was unpressed by the `tap-macro` function, which would mean that I need to repress `@arw` if I wanted to copy text, or something. Obviously this isn't the end of the world, however, it would be great if there was a way to temporarily release `meta`, even while it is being held by another key. Something like:

```
(defalias
  arw (around met (layer-toggle arrows))

  ;; if met is currently held, release it, then press up, then go back to holding met again.

  ;; some possible ways of expressing this
  up  (around (avoid met) up)
  dwn (avoid met up)
  lft (around !met left)
  rit !M-left
)
```

**Comment by oblitzitate** [comment]
Yeah, xkb has a feature called `RedirectKey` where you can redirect a combination to a key and clear modifiers (e.g. Alt+j to Down).

KMonad currently doesn't have such a feature so I'd probably just use `xdotool` to simulate keyup and keydown of modifiers, then call it with `cmd-button`.

**Comment by david-janssen** [comment]
These are some interesting ideas that I'll insert into my mental drawer of things to work on in the future. However, there is a slightly cumbersom KMonad fix that should work.

```
(deflayer arrows
  _    _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    _    _    _    _    _    _    @up  _    _    _    _    _
  _    _    _    _    _    _    _    @lft @dwn @rit _    _         _
  _    M-z  M-x  M-c  _    _    _    _    _    _    _              _
  _    _    _                   _                   _    _    _    _
)
```

Now, in the `arrows` layer, `z`, `x`, and `c` correspond to their 'alted' versions. You could do this for any key you ever intend to push in the `arrows` layer. It's annoying typing it out for all the letters, and I'm hoping to come up with better abstractions, but it should work.

**Comment by oblitzitate** [comment]
@david-janssen by that method, don't you remove the ability to just the tap the initial modifier? Since I assume you're removing the modifier completely and just emitting the layer toggle.

**Comment by kalkronline** [comment]
yes, things like ctrl+mousewheel wouldn't work, since it just turns into a layer toggle rather than an actual ctrl press.

**Comment by david-janssen** [comment]
Hmmmm, then the terribly ugly fix of using both solutions might work? The `M-` part inside the layer will insure that any key so prefixed will always be pressed with `Alt`, while the `(around met...` part makes the button itself also act as a modifier.

The proposed solution at the top is currently nearly unimplementable, since it would require local buttons to know about the global output keyboard state. These have been kept very separate by design, so the architecture makes those kinds of reasonings very difficult to implement.

**Comment by david-janssen** [comment]
> The proposed solution at the top is currently nearly unimplementable, since it would require local buttons to know about the global output keyboard state. These have been kept very separate by design, so the architecture makes those kinds of reasonings very difficult to implement.

Actually: this is nonsense. This could very well be implemented relatively easily. Let me think about it for a moment.

**Comment by david-janssen** [comment]
Came up with something I think is better in 3e7f2aa. If you affix your macro with `(press-only met)` then the macro responsible for releasing `met` can then itself reactivate `met`.

**Comment by kalkronline** [comment]
Here's what my defalias looks like now:
```
(defalias
  arw (around lctl (layer-toggle arrows))

  up  #((release-only lctl) up    (press-only lctl))
  dwn #((release-only lctl) down  (press-only lctl))
  lft #((release-only lctl) left  (press-only lctl))
  rit #((release-only lctl) right (press-only lctl))
)
```
This is a great solution. Thank you for taking the time to implement it, works exactly how I want it to. Maybe some sugar is in order, but as it stands this issue has been solved. :)
