### ISSUE TITLE
kmonad: Parse error: unexpected '^'

### ISSUE THREAD

**Issue by j-steinbach** [kmonad/kmonad#527]
I want to `defsrc` a German/DE QWERTZ layout (Xbows Knight), but I am getting a parse error on `^`. This is weird, as `^` is even used in the [template keymaps](https://github.com/kmonad/kmonad/blob/master/keymap/template/thinkpad_x220_iso.kbd). 

My `defsrc`:

```kbd
(defsrc
esc	f1 f2 f3 f4		f5 f6 f7 f8		f9 f10 f11 f12		del			prnt
^		1	2	3	4	5						6	7	8	9	0		ß		apos	bspc
tab	q	w	e	r	t						z	u	i	o	p		ü		+		#		pgup
caps	a	s	d	f	g			bspc		h	j	k	l	ö		ä		ret			pgdn
shft	y	x	c	v	b			ret		n	m	,	.	-		pgdn			up	
ctl	met	alt	spc	ctl	del	shft	ralt	mod	pgup	lft	down	rght
)
```

```
 ↳ kmonad --version
0.4.1, commit
```

**Comment by slotThe** [comment]
> I want to `defsrc` a German/DE QWERTZ layout (Xbows Knight), but I am getting a parse error on `^`.

Only actual keycodes are allowed in the deflayer and `^` is produced via `S-6`, so it doesn't parse.

> This is weird, as `^` is even used in the [template keymaps](https://github.com/kmonad/kmonad/blob/master/keymap/template/thinkpad_x220_iso.kbd).

Oh!  That's probably a mistake.

**Comment by j-steinbach** [comment]
How would I add `^` then? (And I think `ß` also doesn't work)

Besides that I think "fixed" it by simply using QWERTY as `defsrc`. At least I am not getting that error anymore.

(Not closing this until I can test everything. currently facing https://github.com/kmonad/kmonad/issues/35 for my installation. Oh, the joy.)
