### ISSUE TITLE
could not perform IOCTL grab

### ISSUE THREAD

**Issue by gtms** [kmonad/kmonad#534]
I’ve been trying to setup kmonad on Fedora 35 for the last few days
without success.  My user was successfully added to the input and the newly
created uinput group.  I’ve added the recommended udev rule to
/etc/udev/rules.d.  The uinput module is definitely built into the kernel and
the device file present.  The keyboard referenced to in the defsrc struct is
positively the one I am trying to grab.  But when I do

`kmonad ~/.config/kmonad/config.kbd -l debug`

all I get is this

`Opening KeySink`
`Registering Uinput device`
`Opening KeySource`
`Initiating ioctl grab`
`Closing KeySink`
`Unregistering Uinput device`
`Closing Uinput device file`
`kmonad: Could not perform IOCTL grab on: /dev/input/by-id/usb-Topre_Corporation_HHKB_Professional-event-kbd`

The ‘could not perform IOCTL grab’ part is what is puzzling me.  I’ve checked
permissions, trimmed down my config to bare bones, and even rebuilt 0.4.1 with
stack (I was going with a master branch build).

I’m out of ideas here.  Has someone gone through a similar issue out there?

**Comment by MuhammedZakir** [comment]
Are you able to use `evtest` on that keyboard? If yes, try `evtest --grab`. This will make your keyboard unusable, so have another device - mouse or keyboard - connected before you do that to kill `evtest`/terminal.

**Comment by gtms** [comment]
There you go, thanks for the tip!

I had completely forgotten I had dual-function-keys enabled on this keyboard (for ctrl on enter): all I had to do was to disable the udevmon service that was getting a hold of the device. Now kmonad works beautifully!

Thanks again for the pointer
Cheers
