### ISSUE TITLE
cmd-button use cmd only one .

### ISSUE THREAD

**Issue by lowy** [kmonad/kmonad#536]
cmd-button only one command is allowe . write .sh too
code:
(defalias
  lck #((layer-switch disable) (cmd-button "/home/lowy/.config/kmonad/tray.sh 0"))
  def #((layer-switch default) (cmd-button "/home/lowy/.config/kmonad/tray.sh 1"))
  num #((layer-switch numbers) (cmd-button "/home/lowy/.config/kmonad/tray.sh 4"))
  mse #((layer-switch msectrl) (cmd-button "/home/lowy/.config/kmonad/tray.sh 5"))
  larr #((layer-switch leftarrow) (cmd-button "/home/lowy/.config/kmonad/tray.sh 2"))
  rarr #((layer-switch rghtarrow) (cmd-button "/home/lowy/.config/kmonad/tray.sh 3"))
)
tray.sh:
#!/bin/bash

pkill yad

layer=("disable" "default" "left" "rght" "number" "vmouse")
text=("禁用键盘模式" "默认键盘模式" "左侧方向键模式" "右侧方向键模式" "数字键盘模式" "虚拟鼠标模式")

for idx in {0..5}
do
    if [ "$1" = "$idx" ];then
    	yad --notification --no-middle --command='' --text=${text[idx]} --image=/home/lowy/.config/kmonad/icons/${layer[idx]}.png
    	exit
    fi
done

**Comment by slotThe** [comment]
On Wed, May 11 2022 05:51, lowy zhang wrote:
> cmd-button only one command is allowe . write .sh too

I believe `cmd-button` taking two arguments is a feature that's not in
0.4.1 yet, so you'll have to compile kmonad yourself if you want to use
that.

**Comment by lowy** [comment]
that's fine.  but hope to support the tray icon function natively 
![2022-05-12-09-39-54](https://user-images.githubusercontent.com/6565177/167975023-c23c706a-f3a4-49a8-8c7f-7a79f37f7730.png)

**Comment by slotThe** [comment]
On Wed, May 11 2022 05:51, lowy zhang wrote:
> cmd-button only one command is allowe . write .sh too

I believe `cmd-button` taking two arguments is a feature that's not in
0.4.1 yet, so you'll have to compile kmonad yourself if you want to use
that.
