### ISSUE TITLE
New NixOS Module is broken. Permissions denied

### ISSUE THREAD

**Issue by leifhelm** [kmonad/kmonad#544]
Hey,

I tried the new kmonad module and the service is not starting.

This is the log from systemctl
```
Mai 23 13:51:22 desktop systemd[1]: Started KMonad for /dev/input/by-id/usb-Razer_Razer_Huntsman_Elite-if01-event-kbd.
Mai 23 13:51:22 desktop kmonad-razer-huntsman-start[1502]: kmonad: /dev/input/by-id/usb-Razer_Razer_Huntsman_Elite-if01-event-kbd: openFd: permission denied (Permission denied)
Mai 23 13:51:22 desktop systemd[1]: kmonad-razer-huntsman.service: Main process exited, code=exited, status=1/FAILURE
```

And this is my configuration
```nix
{
  services.kmonad = {
    enable = true;
    keyboards = {
      razer-huntsman = {
        device = "/dev/input/by-id/usb-Razer_Razer_Huntsman_Elite-if01-event-kbd";
        fallthrough = true;
        allowCommands = false;
        config = builtins.readFile ./keyboard.kbd;
      };
    };
  };
}
```

I removed `defcfg` portion in the `keyboard.kbd` file

@pjones have I misconfigured the module? Am I missing an option?

BR

**Comment by pjones** [comment]
Yes, this appears to be a bug in the udev rule.  I'm not sure why the tests are passing but I'll get this fixed right away.

**Comment by pjones** [comment]
@leifhelm Can you tell me the group of that device file?  It should be `uinput` as assigned by the udev rule.

**Comment by leifhelm** [comment]
```
ls -l /dev/input/by-id/usb-Razer_Razer_Huntsman_Elite-if01-event-kbd
lrwxrwxrwx 1 root root 9 23. Mai 23:25 /dev/input/by-id/usb-Razer_Razer_Huntsman_Elite-if01-event-kbd -> ../event3
```
And
```
ls -l /dev/uinput
crw-rw---- 1 root uinput 10, 223 23. Mai 23:25 /dev/uinput
```
I hope that is what you asked for

**Comment by pjones** [comment]
@leifhelm Have you disconnected your keyboard (and then reconnected) or rebooted since upgrading to the latest NixOS module?  I bet that the new udev rule hasn't run for that device, but if you disconnect and reconnect it will.

**Comment by leifhelm** [comment]
I have rebooted my system

**Comment by pjones** [comment]
Can you show me the ownership and group information for `/dev/input/event3`?

I'm expecting the owner to be `root`, the group to be `input` and the mode to be 660 (`rw-rw----`).  The kmonad service runs with the ability to read files that are in the `input` and `uinput` groups.  So if your permissions aren't what I'm expecting we'll need to figure out why.
