### ISSUE TITLE
Layouts for different applications

### ISSUE THREAD

**Issue by GZLiew** [kmonad/kmonad#547]
Hi Im not sure this is explained anywhere but is it possible to apply layouts based on applications ?

Like I want a certain keyboard layout for my terminal and different for other applications

**Comment by david-janssen** [comment]
At the moment no. It is something I hope to add at some point, but first there's a lot of bugfixing and other basic features to add. Would be nice, neh?

**Comment by GZLiew** [comment]
Cant wait to see it soon thanks for working on this library!

**Comment by david-janssen** [comment]
> soon

There is no soon ;)

**Comment by GZLiew** [comment]
@oblitzitate do you have an example of how both will work together?
