### ISSUE TITLE
Option to explicitly say the base layer?

### ISSUE THREAD

**Issue by oblitzitate** [kmonad/kmonad#563]
I've got a config with a bunch of different base layers that I like to fiddle with (e.g. qwerty, colemark-dh, one with layer switching, one with layer toggling, etc.). Most of the extra layers are relatively the same.

I was wondering maybe there could be an option to explicitly state the base layer instead of having to rearrange the order and remap the alias.

Maybe you could put `base-layer <layer name>` inside `(defcfg ...)`? Then in alias you can refer to it as base-layer instead?

**Comment by david-janssen** [comment]
Although a good idea, it is only a convenience-fix for a system that I intend to overhaul sometime soon anyways. For me it makes no sense from an effort-vs-reward perspective. If anyone else is is interested in undertaking this venture I'd be happy to advise.
