### ISSUE TITLE
Dual key order issue

### ISSUE THREAD

**Issue by oblitzitate** [kmonad/kmonad#565]
I want to create a Ctrl-Esc dual key where Ctrl is *guaranteed* pressed and Esc is a conditional tap that occurs *after* Ctrl is released. I could just do...

`(tap-hold-next 200 esc lctl)`

...but Ctrl isn't guaranteed and there is a delay before Ctrl is pressed:

So I tried the following:

`(around (tap-hold-next 200 esc XX) lctl)`

I was expecting Esc to emit after Ctrl's release but it emitted before. How can I resolve this?

**Comment by david-janssen** [comment]
I'm not sure I fully understand what you are trying to achieve. You want a key that always presses a `ctrl`, but only presses an `esc` _conditionally_. Conditional on what?

**Comment by oblitzitate** [comment]
The main purpose is I want to press `ctrl` alone **without any delay** (therefore, it must be guaranteed), yet I also want the `esc` dual role when I need it.  For instance, a lot of FPS games use `ctrl` to crouch so I don't want any delay when doing that. Note: In this instance, I also know `esc` would probably interfere with the crouch action but I wanted to experiment anyway.

Also 'Conditional' just meant tap before timeout only.

If I remember correctly, I believe `at-home-modifier` had such a feature for dual role keys. I wanted to know if it's possible to do so in `kmonad`.

**Comment by oblitzitate** [comment]
So assuming the tap-hold timeout is `200`, a tap would look like:

`Pctrl P(start timeout for esc) 100 Rctrl Tesc`

While a hold, would look like:

`Pctrl P(start timeout for esc) 300 Rctrl`

**Comment by oblitzitate** [comment]
Just saw the new commit that adds `press-only` and `release-only` features so I managed to solve my issue:

  `(around ctl (tap-hold-next 200 (around (release-only ctl) esc) XX))`

**Comment by david-janssen** [comment]
Waaaa, that's 1 issue intentionally and 2 issues unintentionally fixed with 5 minutes of adding some simple buttons. Happy to see things worked out.
