### ISSUE TITLE
Up to date NixOS installation instructions

### ISSUE THREAD

**Issue by tom-on-the-internet** [kmonad/kmonad#569]
Hello!

Thank you so much for this project. It looks great. Unfortunately, I'm having trouble figuring out how to install Kmonad on NixOS.

I'm brand new to NixOS, so I am probably making a lot of mistakes. I'm still learning the terminology.

What I'm looking to do is install the most recent version (HEAD) of Kmonad on a new NixOS installation so that Kmonad works with Wayland. 

Looking at the installation instructions, they appear to reference an older version of the kmonad nix module.
I've tried to copy @pjones's configuration from his dotfiles, but he's using a flake and I'm still not 100% sure on how that is supposed to work.
I've tried installing Kmonad as a package and using the configuration, but the release version doesn't seem to work with the tutorial.

I know that most of this problem is that I haven't "grokked" NixOS yet, but I'm willing to bet there are others in the same situation as well.

Thank you so much for your time!

**Comment by david-janssen** [comment]
> I know that most of this problem is that I haven't "grokked" NixOS yet, but I'm willing to bet there are others in the same situation as well.

Yah... me :D.

I am a bit busy today and probably over the next few days, but I should probably also set up `kmonad` via `NixOS`. Currently I'm just running my own compiled binary. When I do figure it out, I'll write some docs and let you know.

NixOS takes a while to grok, but when things start clicking it truly is a lovely system. I haven't distro-hopped since I found it a few years ago :)

**Comment by tom-on-the-internet** [comment]
@david-janssen thank you for the reply!

If the creator of kmonad is just running his own compiled binary on NixOS, that gives me license to do the same while I figure this whole thing out.

Thank you so much!

**Comment by david-janssen** [comment]
> that gives me license to do the same 

Hahahaha, yep. But I'm also a NixOS nincompoop, so know who your are emulating ;).

Additionally, the busyness persists. Not going to get a chance to play with this anytime very soon.
