### ISSUE TITLE
How to insert accented character with US Qwerty Layout

### ISSUE THREAD

**Issue by pietrodito** [kmonad/kmonad#580]
### Goal
I am french and I need to type some accented letters like `à` `é` etc... I am currently using two keyboard layouts:

+ `US QWERTY`
+ `US QWERTY intl. with dead keys`

My goal is to get rid of the `US QWERTY intl with dead keys` version. In order to do that I am planning to make the following keys works as modifiers: `'` `^` `` ` ``

### Example: The `é` character
So far, this is how I try to make this working:
_____
#### One layer:
```
(deflayer accent-aigu
   _    1    2    3    4    5    6    7    8    9    0    _    _    _
   _    _    _    é    _    _    _    _    _    _    _    _    _    _
   _    _    _    _    _    _    _    _    _    _    _    _    _
   _    _    _    _    _    _    _    _    _    _    _    _
   _    _    _              _              _    _    _    _
)
```
_____
#### One alias: to make the single quote `'` acts as a modifier key:
```
(defalias  aig (tap-hold-next-release 400  '  (layer-toggle accent-aigu)))
```
_____
#### The alias assigned to the good key in the main layer
```
(deflayer qwerty
  grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab  q    w    e    r    t    y    u    i    o    p    [    ]    \
  @xcp a    s    d    f    g    h    j    k    l    ;    @aig    ret
  lsft z    x    c    v    b    n    m    ,    .    /    rsft
  @num lmet lalt           @msp            ralt rmet cmp  rctl
)
```
______
### Issue
It does not work...

**Comment by pietrodito** [comment]
Issue was from compose key configuration

**Comment by jmcarcell** [comment]
And what was the issue and answer @pietrodito ?

**Comment by pietrodito** [comment]
I do not remember... I guess it was OS windows manager side (Gnome at the time I suppose)
