### ISSUE TITLE
How to change dead keys to modifiers?

### ISSUE THREAD

**Issue by pietrodito** [kmonad/kmonad#582]
### Goal

I want to use the keys `'` and `"` as modifiers to get those kind of accented letters `é` and `ë`.

I want to do that with the `US QWERTY` traditional layout and it is worth to note that `'` and `` " `` are on the same key `"` = `S-'`.

### Setup

This is how I have tried to set up things:

I am running Gnome 42 on Arch-based Manjaro distribution with only one layout `US QWERTY`.

```
 (defalias
   LSFT (layer-toggle left-shift)
   AIGU (tap-hold-next-release 400  '  (layer-toggle accent-aigu))
   TRMA (tap-hold-next-release 400  "  (layer-toggle accent-trema)))

```

```
 (deflayer qwerty
   grv   1    2    3    4    5    6    7    8    9    0    -    =    bspc
   tab   q    w    e    r    t    y    u    i    o    p    [    ]    \
   caps  a    s    d    f    g    h    j    k    l    ;    @AIGU   ret
   @LSFT z    x    c    v    b    n    m    ,    .    /    rsft
   lctl  lmet lalt          spc            ralt rmet cmp  rctl)
```

```
(deflayer left-shift
  esc  f1   f2   f3   f4   f5   f6   f7   f8   f9   f10  f11  f12  home end del
    ~    !    @    #    $    %    ^    &    *   \(   \)   \_    +    _
    _    Q    W    E    R    T    Y    U    I    O    P    {    }    |
    _    A    S    D    F    G    H    J    K    L    :    @TRMA  _
    _    Z    X    C    V    B    N    M    <    >    ?    rsft
    _    _    _              _              _    _    _    rctl)
```

```
(deflayer accent-aigu
  esc  f1   f2   f3   f4   f5   f6   f7   f8   f9   f10  f11  f12  home end del
   _    1    2    3    4    5    6    7    8    9    0    _    _    _
   _    _    ẃ    é    ŕ    _    ý    ú    í    ó    ṕ    _    _    _
   _    á    ś    _    _    ǵ    _    _    ḱ    ĺ    _    _    _
   _    ź    _    ć    ǘ    _    _    _    _    _    _    _
   _    _    _              _              _    _    _    _)
```

```
(deflayer accent-trema
  esc  f1   f2   f3   f4   f5   f6   f7   f8   f9   f10  f11  f12  home end del
   _    1    2    3    4    5    6    7    8    9    0    _    _    _
   _    _    _    ë    _    _    _    ü    ï    ö    _    _    _    _
   _    ä    _    _    _    _    _    _    _    _    _    _    _
   _    _    _    _    _    _    _    _    _    _    _    _
   _    _    _              _              _    _    _    _)
```

### Issues

Everything works just fine in some applications `Terminator`, `gedit` and `Libre Office` but not in `Firefox`.

But I have found a strange workaround for `Firefox`. You just need to add a second layout to Gnome:`US QWERTY intl. with dead keys` (which I was using before discoverging kmonad). And now, everything works fine even in `Firefox`.

What is happening here?

### Additional question

+ Is there a way to do that without using a `left-shift` layer like above?

**Comment by pietrodito** [comment]
I had to setup Firefox to use wayland!

**Comment by david-janssen** [comment]
Ahhh interesting. UTF-8 character entry is sadly not uniform at all in Linux, Gnome and KDE apps do things one way, standard X11 stuff does stuff slightly differently. Happy to hear you found a solution.
