### ISSUE TITLE
 `Û` character rises a parse error.

### ISSUE THREAD

**Issue by pietrodito** [kmonad/kmonad#583]
Surpisingly the `Û` character  rises a parse error. Is there a known reason to this?

```
kmonad: Parse error at 55:40:
   |
55 |   grv    1    2    Ê    4    5    6    Û    Î    Ô    0    -    =    bspc
   |                                        ^
unexpected 'Û'
expecting ')'
```

I have just found that `Ù` does the same!

**Comment by david-janssen** [comment]
They simply weren't included in the list of compose sequences. I went through a large list of standard sequences on the internet and turned them into a list inside the source code of KMonad. Either I must've deleted these or they weren't there in the first place.

I think it should work now per 0dd5a0e25129b8ac9627b233db3a3a6894e44a5f

Could you check?

**Comment by pietrodito** [comment]
Works like a charm!
