### ISSUE TITLE
Kmonad launches, but does not work

### ISSUE THREAD

**Issue by reptee** [kmonad/kmonad#592]
## Context (Environment)

OS: Nixos 22.05 (current stable nixpkgs branch)

`kmonad --version`: 0.4.1, commit 95bb58b7347ebacb4654fb21c798e1cd10331b0d

Physical keyboard layout: [Ansi 104](https://www.keyboard-design.com/layouts/100/ansi-104-qwerty-fingercoded.jpg) with 2 quirks:

- Right win key is Fn

- Enter key is like in ISO keyboard(1 in width and 2 in height) and backslash is located to the left of enter

Testing environments:

- TTY after login

- TTY before login

- [hyprland](https://github.com/hyprwm/Hyprland)(wl-roots based compositor)

Installation method: added kmonad as an input to the main configuration flake.

## Behavior
Kmonad no worky, but `kmonad` binary doesn't complain.
The only happy moment was after reboot, first 4 keystrokes were typed as intended(in dvorak), but then it was plain qwerty.

### Flake installation, no module
Kmonad binary added as override to nixpkgs in the flake.nix.

System configuration:
``` nix
{
  services.xserver = {
      layout = "us";
      xkbOptions = "compose:ralt";
  };


  users.users.lex = {
    isNormalUser = true;
    extraGroups = [ "wheel" "uinput" "input" ] /* and some other omitted groups */;
    shell = pkgs.fish;
  };

  users.groups = { uinput = { }; };

  services.udev.extraRules =
    ''
      # KMonad user access to /dev/uinput
      KERNEL=="uinput", MODE="0660", GROUP="uinput", OPTIONS+="static_node=uinput"
    '';

  environment.systemPackages = with pkgs; [ kmonad ];
}
```

Kmonad configuration:
``` kbd
(defcfg
  input  (device-file "/dev/input/by-id/usb-COMPANY_USB_Device-event-kbd")
  output (uinput-sink "My KMonad output")
  cmp-seq ralt    ;; Set the compose key to `RightAlt'
  cmp-seq-delay 5 ;; 5ms delay between each compose-key sequence press
  fallthrough true
  allow-cmd false
)

(defalias
  dhp (around a (around b c))
)

(defsrc
  grv  1    2    3    4    5    6    7    8    9    0    -    =  bspc
  tab  q    w    e    r    t    y    u    i    o    p    [    ]
  caps a    s    d    f    g    h    j    k    l    ;    '    \  ret
  lsft z    x    c    v    b    n    m    ,    .    /           rsft
  lctl lmet lalt              spc                 ralt rmet cmp rctl
)

;; dvorak-programmer
(deflayer dvp
  _  &    [    {    }   \(    =    *   \)    +    ]    !    #    _
  _  ;    ,    .    p    y    f    g    c    r    l    /    @
  _  a    o    e    u    i    d    h    t    n    s    -    _    _
  _  '    q    j    k    x    b    m    w    v    z              _
  _ _ _           _                                        _ _ _ _
)
```

### Flake installation, with module

System configuration:
``` nix
{
  services.xserver = {
      layout = "us";
      xkbOptions = "compose:ralt";
  };

  users.users.lex = {
    isNormalUser = true;
    extraGroups = [ "wheel" "uinput" "input" "kmonad" ] /* and some other omitted groups */;
    shell = pkgs.fish;
  };

  services.kmonad = {
    enable = true;
    keyboards = {
      options = {
        name = "Kmonad-keyboard";
        device = "/dev/input/by-id/usb-COMPANY_USB_Device-event-kbd";
        defcfg = {
          enable = true;
          fallthrough = true;
          allowCommands = false;
        };
        config = ''
          (defalias
            dhp (around a (around b c))
          )

          (defsrc
            grv  1    2    3    4    5    6    7    8    9    0    -    =  bspc
            tab  q    w    e    r    t    y    u    i    o    p    [    ]
            caps a    s    d    f    g    h    j    k    l    ;    '    \  ret
            lsft z    x    c    v    b    n    m    ,    .    /           rsft
            lctl lmet lalt              spc                 ralt rmet cmp rctl
          )

          (deflayer dvp
            _  &    [    {    }   \(    =    *   \)    +    ]    !    #    _
            _  ;    ,    .    p    y    f    g    c    r    l    /    @
            _  a    o    e    u    i    d    h    t    n    s    -    _    _
            _  '    q    j    k    x    b    m    w    v    z              _
            _ _ _           _                                        _ _ _ _
          )
        '';
      };
    };
  };
}
```

## Extra information

Tried launching `kmonad` both as root and as non-root user

`$ sudo modprobe uinput` does not give errors

`kmonad config.kbd -l debug` gives the following output:
```
Opening KeySink
Registering Uinput device
Opening KeySource
Initiating ioctl grab
Launching process: emitter_proc
(C-c pressed)
Closing process: emitter_proc
Closing KeySource
Releasing ioctl grab
Closing KeySink
Unregistering Uinput device
Closing Uinput device file
```

**Comment by MuhammedZakir** [comment]
It didn't work even when running from a terminal?

**Comment by reptee** [comment]
yep, tried launching from both TTY and terminal emulator

**Comment by reptee** [comment]
If I got it right, `evtest` should display events incoming from the keybord, however no events are shown in my case(The last line printed by `evtest [--grab]` is `Testing ... (interrupt to exit)`).

Again, if I got it right `evtest --grab` is supposed to block all the input, but the keyboard continues working?

I tried multiple times launching it as privileged and unprivileged user, on the same input and the only input it blocks is LEDS on {caps,num,scroll}lock

`ls /dev/input/by-id/ -1` gives the following output, by the way:
``` log
usb-COMPANY_USB_Device-event-if02
usb-COMPANY_USB_Device-event-kbd
usb-COMPANY_USB_Device-if01-event-mouse
usb-COMPANY_USB_Device-if01-mouse
usb-COMPANY_USB_Device-if02-event-kbd
```

I believe only two of those are keyboards, for others evtest shows too small amount of keys

**Comment by reptee** [comment]
That test actually surprised me, my observations:

## Run#1
The device that printed hexdumb on keypress was event20. What was weird is that there was no link in /dev/input/by-id to that device. I tried through evtest --grab and it successfuly convinced me to restart my pc lol.

## Run#2(after reboot)
The device was `event0`, to which `usb-COMPANY_USB_Device-event-kbd` was symlinked.
I ran kmonad, with blank configuration(first deflayer and defsrc were identical), so no changes in layout.

## Run#3
Running the given script again gave me different result(PC wasn't rebooted), now it was `event2`(which is `usb-COMPANY_USB_Device-if02-event-kbd` for me).
I made a minor change to kmonad config(bound right shift to letter `a`) and it worked!

## Some additional runs
No changes happened, just wanted to mention that.

## So...
It's weird i would say? I was sure that every physical input device had it's entry in `/dev/input/by-id`, but run#1 proved it wrong. Secondly why would event number change? especially considering that the symlink in `/dev/input/by-id` stayed the same

Many thanks for your time and help, really appreciate it. It brought me much closer to the solution, I will make more tests and close the issue if it is solved for me.

**Comment by MuhammedZakir** [comment]
You're welcome! :-)

Some questions:

1. run#1: was that test done while KMonad, or a similiar software was running? If no, I don't know why you got that. If yes, that would make sense. Did you check the name shown by `evtest` for that device?

2.  run#2 & run#3: some keyboards do show up as 2+ event devices. For instance, one for "normal" keys, and one for consumer/multi-media keys. If that's the case, see https://github.com/kmonad/kmonad/issues/579#issuecomment-1179481171. I suggest you to do some more test on those 2 symlinks to see which keys corresponds to which event device.

> I was sure that every physical input device had it's entry in `/dev/input/by-id`, but run#1 proved it wrong.

No. Some devices don't have an entry there, but do have an entry in `/dev/input/by-path`.

**Comment by reptee** [comment]
1. Actually yes(keyd), that was bold of me to assume it won't change the order of things.
2. I made some reboots and now it seems that `/dev/input/by-id/usb-COMPANY_USB_Device-if02-event-kbd` is consistent across system launches. Will follow your advice someday, but due to laziness it will likely be the day something broke again =)

It is solved indeed!

**Comment by MuhammedZakir** [comment]
> Actually yes(keyd), that was bold of me to assume it won't change the order of things.

1. Key remappers will "grab" devices. When a device is "grabbed", other programs won't be able to read events from that device.
2. Key remappers will create virtual device(s) to send transformed events to the system.

This will essentially create a redirection from your actual device to another (virtual) device, and that's why, you got key events from `event20`.
