### ISSUE TITLE
Set context while holding button

### ISSUE THREAD

**Issue by arkadiy-telegin** [kmonad/kmonad#593]
I want to implement the following functionality:

1. If I press `Alt+I/J/K/L`, I get arrow functionality. This is as simple as `(layer-toggle arrows)`.
2. Now I also want to have a functional `Alt+Tab`. Adding `tab` to the `arrows` layer doesn't work, since to cycle through the windows, you need to have press `alt` -> `tab` -> `tab` -> ... ->  release `alt`. Merely adding `tab` to the `arrows` layer would result in press `alt` -> `tab` -> release `alt` -> press `alt` -> `tab` -> ...

Recently a couple of functions were added, namely `press-only` and `release-only`. I tried to use them to make it work, but were ultimately unable to achieve the desired functionality. N.B. when simulating arrow keys, we don't want to simulate any `alt` presses, since that triggers the menu bar in programs and prevents successful navigation.

Thank for help!

**Comment by jtroo** [comment]
With something like QMK or [kanata](https://github.com/jtroo/kanata), I would make `alt` a tap-hold key where tap is `alt` and hold is `layer-toggle arrows`. Single press+hold of `alt` results in layer-toggle. Tap then press->hold result in `alt` being held down.

However, this isn't possible in kmonad right now - this is waiting on #163 to be added.

**Comment by MuhammedZakir** [comment]
What @*jtroo* said seems possible? (I don't use QMK.)

Note:
1. If you don't want `T@lalt  ->  tap lalt`, then you can directly use `(layer-toggle arrows)` there.
2. If you want that behavior and `tap-next` didn't work well for you, use another button in the `tap-*` family.
3. You may have to adjust the `300`ms delay in `multi-tap`.

```clojure
(defsrc 
  tab
  h j k l
  lalt
  lctl c  ;; needed for killing process via Ctrl-C
)

(defalias
  ;; T@lalt        -> tap `lalt`
  ;; P@lalt        -> toggle layer `arrows`
  ;; T@lalt T@lalt -> tap `lalt`
  ;; T@lalt P@lalt -> hold `lalt`
  lalt (multi-tap 300 (tap-next lalt (layer-toggle arrows)) lalt)
)

(deflayer main
  tab
  h j k l
  @lalt
  lctl c
)

(deflayer arrows
  XX
  left down up right
  XX
  XX XX
)
```

**Comment by jtroo** [comment]
Ah that's clever! A lot more complicated and hard-to-discover than QMK's tap-hold configuration, but if it does the trick then it does the trick.

**Comment by arkadiy-telegin** [comment]
@MuhammedZakir do you think it not possible to emulate Alt+Tab behaviour as it normally is? If I'm not mistaken, your solution would not work with existing muscle memory, since before switching windows as I would normally, I would have to tap `alt` once.

What I was thinking is:
1. If I hold `alt` and press `i/j/k/l`, kmonad would just emit arrow keys.
2. If I hold `alt` and press `tab`, kmonad will send an `P@lalt T@tab`, and every next `T@tab` would work with `alt` already pressed. Then when I'm done switching windows, I would release `alt` which would send `R@lalt`.

**Comment by MuhammedZakir** [comment]
Some improvements can be made to KMonad to make this easier, but it will take time.

```clojure
(defsrc 
  tab
  h j k l
  lalt
  lctl c  ;; needed for killing process via Ctrl-C
)

(defalias
  lalt (around lalt (layer-toggle arrows))
)

(deflayer main
  tab
  h j k l
  @lalt
  lctl c
)

(defalias
  Rlalt (release-only lalt)
  Plalt (press-only lalt)

  left  (tap-macro-release @Rlalt left  @Plalt)
  down  (tap-macro-release @Rlalt down  @Plalt)
  up    (tap-macro-release @Rlalt up    @Plalt)
  right (tap-macro-release @Rlalt right @Plalt)
)

(deflayer arrows
  _
  @left @down @up @right
  _
  _  _ 
)
```

**Comment by arkadiy-telegin** [comment]
This is a neat solution, but it unfortunately triggers menu bar in apps. So e.g. when trying to use arrow keys when navigating in the firefox searchbar, emission of `P@lalt` makes it unusable. See the attached video (550 kB):

https://user-images.githubusercontent.com/58264717/179964309-85ddfafc-31d7-4894-ab46-841b1a3f6491.mp4

**Comment by MuhammedZakir** [comment]
Does `alt` have to work with keys other than `tab`?

Replace `arrows` layer and `defalias` before it with:
```clojure
(defalias
  Rlalt (release-only lalt)
  Plalt (press-only lalt)

  tab #((press-only lalt) tab)

  left  #(@Rlalt left )
  down  #(@Rlalt down )
  up    #(@Rlalt up   )
  right #(@Rlalt right)
)

(deflayer arrows
  @tab
  @left @down @up @right
  _
  _  _ 
)
```

**Comment by MuhammedZakir** [comment]
I can understand if this is not satisfactory, but because `alt` must be held for `tab`, and at the same time, whenever arrow keys are pressed, they need to be send without `alt`, this is the best I could think of. Of course, this can be fixed by improving KMonad, but I don't this will be done anytime soon [1]. :-(

[1] Unless we get new contributors.

**Comment by MuhammedZakir** [comment]
Did the above config work?

**Comment by arkadiy-telegin** [comment]
In your latest config, we still send `P@lalt R@lalt up`, so it still pulls up a menu bar unfortunately :(

**Comment by arkadiy-telegin** [comment]
We could potentially define `tab #((press-only lalt) tab)`, but then how do we send a `R@lalt` in the end after we physically release `alt`?

**Comment by MuhammedZakir** [comment]
Here is another version.

Note: you may use your main layer (`main` in below config) instead of creating a new one. However, this won't emit arrow keys for `h`/`j`/`k`/`l` keys. You said that you don't use both in a single press, so this may simplify things for you.

```clojure
(defsrc 
  tab
  h j k l
  lalt
  lctl c  ;; needed for killing process via Ctrl-C
)

(defalias
  when-releasing (tap-macro-release #((layer-rem alt-ed) (release-only lalt)))
  lalt (around (layer-toggle arrows) @when-releasing)
)

(deflayer main
  tab
  h j k l
  @lalt
  lctl c
)

(defalias
  tab #((press-only lalt) (layer-add alt-ed) tab)
)

(deflayer arrows
  @tab
  left down up right
  _
  _  _ 
)

(deflayer alt-ed
  tab
  _  _  _  _  ;; this will emit `alt` for arrows, you may change it.
  _
  _  _
)
```

**Comment by arkadiy-telegin** [comment]
Oh my god this works! Thank you so much Muhammed!

**Comment by MuhammedZakir** [comment]
A button named `(before-after-next btn1 btn2)` was added recently. It may simplify your setup. It works like `around-next` - it will tap `btn1` when it is invoked and taps `bt2` when it gets the next key press' release event.

[1] https://github.com/kmonad/kmonad/commit/ac3c0db4f7fca0f66980d1b76a64630a66a36c21
