### ISSUE TITLE
key not released: Tried cancelling expired hook

### ISSUE THREAD

**Issue by thompson-vii** [kmonad/kmonad#594]
I have two macros
```
set7 (tap-macro (around lctl (around alt 7) ) b)
set8 (tap-macro (around lctl (around alt 8) ) b)
```

trigger by 	
```
macro1 (tap-hold-next 200 @set7 @set8)
```

set7 has an error that stops `release b` so it's stuck
set8 properly releases b when the physical key is released.

![image](https://user-images.githubusercontent.com/31672176/180000500-fe8dd8d2-fab6-47e5-a4e2-176c651f1fa1.png)

tested on 95bb58 on windows

**Comment by jokesper** [comment]
Fixed in #873
