### ISSUE TITLE
repeat a  key when hold timeouts

### ISSUE THREAD

**Issue by pblgomez** [kmonad/kmonad#597]
Hi, I'm trying to find a way to do this but cannot make sense if it's possible
I use home row keys so if I:
- press `h` I get `h`
- hold `h` I have `shift`

But trying to get that If I keep holding `h` for more than a second I get `h` indefinitely until I release.

Is this even possible?

**Comment by MuhammedZakir** [comment]
If you're using `kmonad` built from `master` branch, you can use `:timeout-button`. I think it's only available for `tap-hold-next` atm.

```clojure
(tap-hold-next 1000 h lsft :timeout-button h)
```

**Comment by pblgomez** [comment]
wow, exactly what I was looking for. Thank you.

**Comment by pataquets** [comment]
@pblgomez Fancy to close the issue if you feel it solved?
Let's keep the issue list tidy for the maintainers (extra karma points :smile:)
