### ISSUE TITLE
How to run a gsettings command?

### ISSUE THREAD

**Issue by pietrodito** [kmonad/kmonad#604]
I am trying to toggle touchpad from keyboard using kmonand under Arch/Gnome/Wayland but the fact that kmonad runs as root makes impossible to update use `gsettings`.

I have tried this:
```
runuser -u fairuser -- command /home/fairuser/bin/disable-touchpad
```
but it does not work either...
Is there any workaround?

**Comment by isamert** [comment]
You can make it run on user level, see [the FAQ](https://github.com/kmonad/kmonad/blob/master/doc/faq.md#q-how-do-i-get-uinput-permissions).

**Comment by pietrodito** [comment]
I have read the FAQ but did  not find how to do it

**Comment by isamert** [comment]
If you follow the steps explained in `Q: How do I get Uinput permissions?`, you will be able to run KMonad on user level.

**Comment by pietrodito** [comment]
I have followed all the steps in the section. I have updated the daemon service file to make kmonad run by the user `ulys` as you can see here:

```
❯ ps -aux | grep kmonad
ulys         393  0.0  0.0 1075687684 12576 ?    S<sl Aug09   0:10 /usr/bin/kmonad /etc/kmonad/config.kbd
```

Everything works fine and I am able to run some scripts with a one-key `cmd-button`. But I cannot find a workaround to update gnome gsettings. This is the error I get:

```
(process:226062): dconf-WARNING **: 12:10:59.228: failed to commit changes to dconf: Cannot autolaunch D-Bus without X11 $DISPLAY
```
WIth some scripts I run with `cmd-button` I have checked that `$USER` equals `ulys` as expected. But `$DISPLAY` is empty.

**Comment by MuhammedZakir** [comment]
Most probably an issue with your daemon? When I ran `kmonad` in my terminal, and pressed below button [1], correct value was printed. Have you tested your `cmd-button` using `kmonad` instance ran from a terminal?

```
(cmd-button "echo DISPLAY=$DISPLAY")
```

**Comment by isamert** [comment]
@pietrodito Also, if you are using a systemd service for KMonad, be sure to start it after `graphical-session.target` if you want `DISPLAY` to be available to your KMonad instance by adding this to your service file:

```
[Install]
WantedBy=graphical-session.target
```
