### ISSUE TITLE
Arabic layout: Parse error

### ISSUE THREAD

**Issue by adham-omran** [kmonad/kmonad#612]
I have been using Kmonad for a while now and I want to use an Arabic layout. Just using the letters doesn't seem to work, how would I implement them?
```
(deflayer arabic
` 1 2 3 4 5 6 7 8 9 0 - = caps
tab  د ج ح خ ه ع غ ف ق ث ص ض
bspc ط ك م ن ت ا ل ب ي س ش
     ظ ز و ة ى لا ر ؤ ء ئ , . /
)
```
I get the error
```
kmonad: Parse error at 44:5:
   |
44 | tab د ج ح خ ه ع غ ف ق ث ص ض
   |     ^
unexpected 'د'
expecting ')'
```

**Comment by MuhammedZakir** [comment]
Currently, arbitrary unicode handling is not supported.

One solution is to create a custom XCompose file for unicode characters you need, and send assigned key combos from KMonad.

Another is #575. This is easier if it works for you. You can test it by merging that PR locally, and compiling it.

**Comment by adham-omran** [comment]
Thank you for the two directions. I'll test both and report back with more details.
