### ISSUE TITLE
Windows switching causes Tab key to remain pressed

### ISSUE THREAD

**Issue by avishefi** [kmonad/kmonad#613]
When switching between different privileged windows on Windows the tab key remains pressed.

For example, when opening the Windows Task Manager window and switching to another window, the window switching doesn't work smoothly and after 2-3 attempts it works, only leaving the tab key pressed until hit again.

Also, KMonad is not working entirely when using a privileged window such as Windows Task Manager.

**Comment by MuhammedZakir** [comment]
KMonad won't work for privileged windows. It's a limitation with Windows API we use. The solution is to use a kernel extesion like we're doing in macOS. For Windows, the only one I know is "Interception" [1]. However, it has some serious limitation [2].

[1] https://github.com/oblitum/Interception
[2] https://github.com/oblitum/Interception/issues/25

**Comment by avishefi** [comment]
Thanks.
