### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by bubbleguuum** [kmonad/kmonad#614]
I planned to contribute a kmonad package for my distro, put the current release version is nearly 2 years old.
And packaging git version of software is generally not accepted for that distro.

Is there a new official release in sight ?
Speaking of which, for official releases, it would be of good idea to use releases rather than tags, as you can get notifications for the former (useful for packagers!).

**Comment by slotThe** [comment]
Not in the current state I don't think.  This was discussed in https://github.com/kmonad/kmonad/issues/537 and we dedided that it was best to wait until at least a few things from `keycode-refactor` have landed into `master`.  Maybe you can convince people that packaging $HEAD is acceptable in this case.
