### ISSUE TITLE
Can kmonad turn mouse movement into keyboard presses?

### ISSUE THREAD

**Issue by ziontee113** [kmonad/kmonad#618]
Thank you for the amazing software!

The question I have is can kmonad turn mouse events into keyboard presses? A simple use case is turn mouse (trackpad) movements into `hjkl` keys to use in Vim.

Can this be achieved in the current version of kmonad? Thank you very much!

**Comment by slotThe** [comment]
We do not handle any kind of mouse events right now; see #150
