### ISSUE TITLE
Steno chording

### ISSUE THREAD

**Issue by nightscape** [kmonad/kmonad#622]
Hi all,
I bought the amazing [Charachorder One](https://www.charachorder.com/en-de) device which (apart from its unique 3D joystick keys) allows pressing multiple keys together to type full words at a time.
For example, when pressing `i`, `m` and `p` within a certain short timespan, it will expand to `important`.
This is of course fully configurable. The only downside is that I always have to carry around the device with me.

I'm aware of [Plover](http://www.openstenoproject.org/plover/) which also allows steno-chording, but it requires switching to a steno layout which is completely different from usual keyboard layouts.

What I would like to achieve is something like the [Charachorder Lite](https://www.charachorder.com/en-de/products/charachorder-lite) which behaves just like an ordinary keyboard with the additional possibility to smash multiple keys at (mostly) the same time and have it output an entire word.

Would something like this be thinkable with kmonad?
Is issuing one character/keycode output for one or more keypresses deeply embedded in the code, or would it be rather easy to allow `m` input keys (within a certain time) to `n` output characters?

**Comment by nightscape** [comment]
Here two AutoHotKey-based tools doing the same thing:
https://github.com/skimrey/stenotypy
https://github.com/psoukie/zipchord/

**Comment by entibo** [comment]
It is possible but it would require an external tool to transform a dictionary into kmonad layers.

`#(c (layer-delay 50 c+))`: output c, and if the next key is pressed within 50ms, look it up on a layer
Downside: when a chord is detected, it might need to erase the chord's characters which will mess with undo history

`(around-next-timeout 50 (layer-toggle c+) c)`: if the next key is pressed within 50ms, look it up on a layer, else output c
Downside: every key (that starts a chord) is delayed a bit


```clojure
(defsrc
  q    w    e    r    t    y    u    i    o    p 
  a    s    d    f    g    h    j    k    l    
  z    x    c    v    b    n    m 
)
(deflayer base
  _    _    _    _    _    _    _    _    @o+  _
  _    _    @d+  @f+  _    _    _    _    _
  _    _    @c+  _    _    _    _
)
(defalias
  could #(c o u l d) ;; CD
  find  #(f i n d)   ;; FD
  found #(f o u n d) ;; FDO
  c+  (around-next-timeout 50 (layer-toggle c+) c)
  d+  (around-next-timeout 50 (layer-toggle d+) d)
  f+  (around-next-timeout 50 (layer-toggle f+) f)
  o+  (around-next-timeout 50 (layer-toggle o+) o)
  df+ (around-next-timeout 50 (layer-toggle df+) @find)
  do+ (around-next-timeout 50 (layer-toggle do+) #(d o))
  fo+ (around-next-timeout 50 (layer-toggle fo+) #(f o))
  od+ (around-next-timeout 50 (layer-toggle do+) #(o d))
  of+ (around-next-timeout 50 (layer-toggle fo+) #(o f))
)
(deflayer c+
  _    _    _    _    _    _    _    _    _    _
  _    _    @could _  _    _    _    _    _
  _    _    _    _    _    _    _
)
(deflayer d+
  _    _    _    _    _    _    _    _    @do+ _
  _    _    _    @df+ _    _    _    _    _
  _    _    @could _  _    _    _
)
(deflayer f+
  _    _    _    _    _    _    _    _    @fo+ _
  _    _    @df+ _    _    _    _    _    _
  _    _    _    _    _    _    _
)
(deflayer df+
  _    _    _    _    _    _    _    _    @found _
  _    _    _    _    _    _    _    _    _
  _    _    _    _    _    _    _
)
(deflayer do+
  _    _    _    _    _    _    _    _    _    _
  _    _    _    @found _  _    _    _    _
  _    _    _    _    _    _    _
)
(deflayer fo+
  _    _    _    _    _    _    _    _    _    _
  _    _    @found _  _    _    _    _    _
  _    _    _    _    _    _    _
)
(deflayer o+
  _    _    _    _    _    _    _    _    _    _
  _    _    @od+ @of+ _    _    _    _    _
  _    _    _    _    _    _    _
)
```
