### ISSUE TITLE
tap key not registered in some application

### ISSUE THREAD

**Issue by PanAeon** [kmonad/kmonad#624]
I've mapped the esc key as such:
```clojure
 esc (tap-hold 200 esc (layer-switch mouse) )
```
It works for most applications, but some of them completely ignore `esc` taps. I've run `wev` and the only difference between mapped escape, and not mapped is the release time, which is the same as for the `pressed` event for taps:
```
[14:     wl_keyboard] key: serial: 339493; time: 499641576; key: 9; state: 1 (pressed)
                      sym: Escape       (65307), utf8: '
14:     wl_keyboard] key: serial: 339494; time: 499641576; key: 9; state: 0 (released)
                      sym: Escape       (65307), utf8: ''
```
Is it possible to add some short delay between `key pressed` and `key released` events?

- Kmonad version: __0.4.1__, commit 296e463fe7761a919a2a3e39599293526ce55454
- OS: __Linux, NixOS__
- DE: __Sway, Wayland__

**Comment by PanAeon** [comment]
I think I know exactly what happens, some games handle keyboard input as such:
`onkeypress save keypress to a hashmap` => `(on tick check if key is pressed)*` => `onrelease remove key from hashmap`
This works as normall games run at 60FPS, which gives 16ms of time to handle the event. On my keyboard a tap produce ~90 ms between events, so usually there's plenty of time. But `kmonad` tap releases the key immediately, so some games might miss the event.

**Comment by entibo** [comment]
I've had this issue in some applications with modifiers not being registered because of the lack of delay between press and release. 

Quick fix: `esc` -> `(around esc P10)` (assuming 10ms delay)

A minimum press-release delay would be problematic i think: the macro
`#(f u n c t i o n)` would take 80ms instead of being instant
...and if the delay didn't implicitly pause the macro, then the macro
`#(C-c esc)` would accidentally perform C-c C-esc

**Comment by PanAeon** [comment]
> Quick fix: `esc` -> `(around esc P10)` (assuming 10ms delay)
Thank you! It worked

> A minimum press-release delay would be problematic i think: the macro `#(f u n c t i o n)` would take 80ms instead of being instant ...and if the delay didn't implicitly pause the macro, then the macro `#(C-c esc)` would accidentally perform C-c C-esc
Good points. I thought about introducing an option specifically for `tap-*` macros (something similar to `cmp-seq-delay'. Given `tap` is instantenous key press-release it shouldn't affect next functions (in theory).

Anyway, `(around esc P10)` is a valid solution. If we add it to `tutorial.kbd` I think this ticket can be closed.
