### ISSUE TITLE
combining hold and mulit tap

### ISSUE THREAD

**Issue by gerhard-h** [kmonad/kmonad#625]
I tried to get
q on tap
! on hold
@ on double tap 
the closest I got was 
`qmt  (multi-tap 300 (tap-next q !) @ )`  but it is does not output q most of the time. All the tap-hold options will end up in endless key repeats.

Is it even possible to achive, what I want with kmonad?

**Comment by slotThe** [comment]
`(tap-hold-next-release 300 (multi-tap 300 q @) !)` works

**Comment by gerhard-h** [comment]
`(tap-hold-next-release 300 (multi-tap 300 q A-C-q) !)`

does this on tap :(

qqqqqqqqqqqqqqqqqqqqqqqq

**Comment by slotThe** [comment]
On Fri, Oct 21 2022 04:36, Lindwurm wrote:
> `(tap-hold-next-release 300 (multi-tap 300 q A-C-q) !)`

Works for me.  Are you running an older version of kmonad?

**Comment by gerhard-h** [comment]
only changes since compilation where in installation.md
