### ISSUE TITLE
Key repetition rate is slow when Kmonad is running on Windows.

### ISSUE THREAD

**Issue by c-berger** [kmonad/kmonad#634]
When hold and pressing a key (e.g. the arrow keys), the repetition rate is much slower with Kmonad running than without Kmonad:

![kmonad_slow_key_repetition_rate](https://user-images.githubusercontent.com/71664347/194508747-7a5957c0-3d4a-4b3b-a242-9cd9c987ed84.gif)

Note that this is for all keys, and it is especially annoying for arrow key. I am running Kmonad on Windows.

Is there any option to change the key repetition rate? Or is this considered a bug?

Thanks in advance!

**Comment by slotThe** [comment]
As of this point, the key repetition rate is controlled by the OS.  Since kmonad creates a new (virtual) input device, you have to change the rate _after_ starting kmonad.  The `uinput-sink` output has a handy second argment for that:

``` clojure
(uinput-sink
 "KMonad Keyboard"
 "sleep 0.2s; xset r rate 230 70; sleep 0.2s; setxkbmap -option compose:menu")
```

**Comment by c-berger** [comment]
Hi and thanks for the info. Is there a similar option for Windows OS (i.e. `(send-event-sink)`)?

**Comment by slotThe** [comment]
> Hi and thanks for the info. Is there a similar option for Windows OS
> (i.e. `(send-event-sink)`)?

Ah, Windows, of course.  I think there is something like

    (send-event-sink 500 20)

**Comment by c-berger** [comment]
Ah, that works great! Thank you very much!

**Comment by Acumane** [comment]
I'm experiencing issues regardless of the values I choose! If 2nd arg is low, I get stuck keys every other sentence. If it's high, I get this latency when keys are held down. Unusable for me on Windows, unfortunately.
