### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by fesnavarro** [kmonad/kmonad#636]
Is Kmonad capable to handle a key using three keys to create a click? For instance pression j,k and l together presses the ESC key.

**Comment by qyurila** [comment]
That's called 'Combo' and there is an open issue about it: #157

The bottom line is, there is no such feature currently. But there is a walkaround that at least makes 2-key combos possible. Check out the mentioned issue above.

...and it would be good if the title describes your issue properly.

**Comment by slotThe** [comment]
Yes, closed as a duplicate of #157
