### ISSUE TITLE
kmonad: Could not perform IOCTL grab

### ISSUE THREAD

**Issue by formula-spectre** [kmonad/kmonad#640]
hello. I've not used kmonad in a while, decided to give it a go recently, but I've encountered this problem:
```
 doas kmonad -l debug ~/.config/kmonad/kmonad-x230.kbd
Opening KeySink
Registering Uinput device
Opening KeySource
Initiating ioctl grab
Closing KeySink
Unregistering Uinput device
Closing Uinput device file
kmonad: Could not perform IOCTL grab on: /dev/input/by-path/platform-i8042-serio-0-event-kbd

file /dev/input/by-path/platform-i8042-serio-0-event-kbd
/dev/input/by-path/platform-i8042-serio-0-event-kbd: symbolic link to ../event3
file /dev/input/event3
/dev/input/event3: character special (13/67)
```
what is wrong exactly? I'm in the input and uinput group, although I don't know if the latter has been created in the right way; I also have this udev rule:
```KERNEL=="uinput", GROUP="input", MODE="0660", OPTIONS+="static_node=uinput"```  
think this covers it; thank you for your time and consideration.

**Comment by formula-spectre** [comment]
apparently swhkd was grabbing my keyboard, closing this

**Comment by kohane27** [comment]
To add on this: I was using `xremap`. Once I stopped `xremap` I could run `kmonad`.
