### ISSUE TITLE
Encountered error in KeySource: Cannot translate from windows keycode: 255 [Windows 10]

### ISSUE THREAD

**Issue by Will-Hendrix** [kmonad/kmonad#695]
Whenever the Fn key is pressed on my "Lenovo ThinkPad Yoga X1 gen 6" running Windows 10, I get this error; it causes kmonad to crash and stops catching any keys. I have my usual base layer as colemak so I start typing gibberish all of a sudden when it stops working. I never use the fn key, but apparently it's close enough to the ctrl key that I accidently press it fairly often, is there any way to make the fn key be ignored rather than having it crash kmonad? Should I just take off the keycap, or is there a easier way?

**Comment by Will-Hendrix** [comment]
Was doing some additional testing; pressing ctrl+fn+another key crashes kmonad, but it does not appear to release the keys; so ctrl is held down for all future keypresses. trying to stop kmonad.exe from the task manager threw a "this action could not be preformed with this program," and pressing the same ctrl did not fix it, but pressing the ctrl on the other side of the keyboard did. I have no idea what the error is exactly, but maybe this helps?

**Comment by Will-Hendrix** [comment]
looks like this was supposed to have been fixed in [#72](https://github.com/kmonad/kmonad/issues/72), but I can't tell what's different now... is there a way to use github to try using an old version? I'm not very familiar with coding or installing programs manually.

**Comment by PockyBum522** [comment]
See my post on this thread: https://github.com/kmonad/kmonad/issues/681 it will reference a guide for how to build the current master branch.

**Comment by PockyBum522** [comment]
https://learn.microsoft.com/en-us/powershell/scripting/developer/cmdlet/background-jobs?view=powershell-7.3 this is how to run things if you need the command prompt back. 

I should also note that on my machine, ctrl + c works as expected to kill it in powershell. Worst I've had to deal with is ctrl sticking as down sometimes, which goes away when I tap left control.

**Comment by PockyBum522** [comment]
I had a look at the commit you mentioned, but it looks like a lot has changed since then and it might not even matter anymore.

So, in order to work around this, I made a powershell script that relaunches kmonad on crash. 

Check out my comment here for where to find the script: https://github.com/kmonad/kmonad/issues/432

**Comment by slotThe** [comment]
This is essentially https://github.com/kmonad/kmonad/pull/475

If anyone wants to pick up that PR again (or implement what David talked about [here](https://github.com/kmonad/kmonad/issues/72)) at this point I wouldn't be opposed to merging, as `keycode-refactor` will probably never be merged at this rate.
