### ISSUE TITLE
tap-next + mouse event does not recognize held key

### ISSUE THREAD

**Issue by lellolillili** [kmonad/kmonad#696]
Hi, I set up my ctrl/esk key as
```
ec  (tap-next esc lctl)
```

It works as espected with reguard keys, but on 
``` ec + click ```
only the click is registered.

Is this not implemented?

Cheers

**Comment by Aldairng** [comment]
Same issue here, tap-next work perfectly with the keyboard, but I can use a hold key with my mouse.

In my case, I'm using `lmet` as the hold key, something like
`ec (tap-next a lmet )`, 
but click does get the held `lmet`

**Comment by slotThe** [comment]
KMonad does not process mouse events, so this is expected
