### ISSUE TITLE
tap-hold-next-release :timeout-button (stop gap in replace of key chords / combos)

### ISSUE THREAD

**Issue by Aeyk** [kmonad/kmonad#700]
I am trying to simulate key chords as discussed in issue #157 on  release version 0.4.1 because I would like when I press both qw at the same time, it acts like a backspace. 

```
(defalias
	qw (tap-hold-next-release 12 q (layer-toggle qw) :timeout-button q)
```

 

```   |
24 |         qw (tap-hold-next-release 12 q (layer-toggle qw) :timeout-button q)
   |                                                          ^
unexpected ':'
expecting button
```

I am a pretty new user to kmonad (first successfully ran it today), but I tried my best to go through the documentation, tutorial and skim the titles of open issues, so forgive me if I have missed something clearly laid out. 

Unrelated to my issue but I would also like to say, I am in love with the idea, and thus far the implementation of kmonad, I dislike switching back and forth  between mouse and keyboard, and also strongly dislike the distance for modifiers, and overuse of my weak pinkies and using ugly wrist angles, with kmonad I have started using home row mods, and it is surprisingly intuitive compared to trying and failing to learn other keyboard layouts in the past. Once chords/combos are implemented I will be very happy, moreso than I already am with this lovely piece of software, thanks so much!

**Comment by slotThe** [comment]
The `:timeout-button` feature is only available on HEAD right now, until we cut a new release
