### ISSUE TITLE
Which tap-* command issues based on press, not release?

### ISSUE THREAD

**Issue by xxxserxxx** [kmonad/kmonad#705]
The standard X input issues keystrokes based on the order of tapping; for example, typing "is" quickly will always issue "is" regardless of the order of release. For chording, kmonad must also consider the release; I'm unable to find a configuration where -- if chording is not triggered, such as after a delay of holding -- events are triggered based on the order of key press, rather than release. I've tried various combinations of `tap-*` -- `tap-hold`, `tap-next-release`, `tap-hold-next-release` etc. -- and all appear to issue events based on the order of release. As a result, if I have any chording configured for a key, I can type quickly enough such that I often get "si" instead of "is".  This is a relatively recent behavior; it's been happening for the past couple of months. Prior to this, I had no problems with chording keys issuing taps in the correct sequence.

Which `tap-*` allows chording after the key is held for a period, but issues keys in the order of the original tap (vs. the order of the release)?

I'm attaching my config with the caveat that I've tried a number of the `tap-*` commands (with and without timeouts) and with varying timeouts (extremely short eg 50 and long eg 1000). I may not have tried them all.

[kmonad.txt](https://github.com/kmonad/kmonad/files/11601424/kmonad.txt)

**Comment by jtroo** [comment]
It seems you have run into this known issue: https://github.com/kmonad/kmonad/issues/256

Apparently there's a [draft PR](https://github.com/kmonad/kmonad/pull/524) that fixes it, which you could try. Or you [could try](https://github.com/jtroo/kanata) my solution if you're [not on MacOS](https://github.com/jtroo/kanata/blob/main/docs/kmonad_comparison.md#why-i-built-and-use-kanata).

**Comment by xxxserxxx** [comment]
Agree that it's a dupe; closing in favor of #256
