### ISSUE TITLE
Can't run kmonad as system service..

### ISSUE THREAD

**Issue by JennytheDragon2000** [kmonad/kmonad#719]
when I run kmonad as system service it can't use the commands such as jumpapp to switch the windows..

╭─ ~ 
╰─ systemctl status kmonad         
● kmonad.service - kmonad keyboard config
     Loaded: loaded (/usr/lib/systemd/system/kmonad.service; enabled; pres>
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: active (running) since Fri 2023-07-14 11:59:05 +0530; 54s ago
   Main PID: 185085 (kmonad)
      Tasks: 22 (limit: 9321)
     Memory: 4.3M
        CPU: 1.552s
     CGroup: /system.slice/kmonad.service
             └─185085 /usr/bin/kmonad /home/srinath/.config/kmonad/config.>

Jul 14 11:59:16 fedora kmonad[185155]: Cannot open display.
Jul 14 11:59:16 fedora kmonad[185145]: Error: found running process for 'l>
Jul 14 11:59:16 fedora kmonad[185169]: Cannot open display.
Jul 14 11:59:16 fedora kmonad[185159]: Error: found running process for 'k>
Jul 14 11:59:16 fedora kmonad[185183]: Cannot open display.
Jul 14 11:59:16 fedora kmonad[185173]: Error: found running process for 'l>
Jul 14 11:59:17 fedora kmonad[185197]: Cannot open display.
Jul 14 11:59:17 fedora kmonad[185187]: Error: found running process for 'k>
Jul 14 11:59:19 fedora kmonad[185211]: Cannot open display.
Jul 14 11:59:19 fedora kmonad[185201]: Error: found running process for 'l>

this is my .service file 

╰─ systemctl cat kmonad                    
/usr/lib/systemd/system/kmonad.service
[Unit]
Description=kmonad keyboard config

[Service]
Restart=always
RestartSec=3
ExecStart=/usr/bin/kmonad /home/srinath/.config/kmonad/config.kbd
Nice=-20

[Install]
DefaultInstance=config
WantedBy=default.target

[Service]
TimeoutStopFailureMode=abort
lines 1-29/29 (END)

but if I run the kmonad in a terminal with the command

kmonad config.kbd

it works.

How can I resolve this issue?

**Comment by Ultrahalf** [comment]
```
[Unit]
Description=kmonad keyboard config

[Service]
Restart=always
RestartSec=3
ExecStart=/usr/bin/kmonad %E/kmonad/config.kbd
Nice=-20

[Install]
WantedBy=default.target
```

try putting config in /etc/kmonad/config.kbd and running the service


look at the example in the doc: https://github.com/kmonad/kmonad/blob/master/startup/kmonad%40.service

---


are you sure your service file is correct?

**Comment by JennytheDragon2000** [comment]
it works. but the problem is kmonad can't run commands. 

here are few lines of my config.

    lbw (cmd-button "jumpapp -r librewolf")
    ktt (cmd-button "jumpapp -r kitty")
    mpv (cmd-button "jumpapp -r mpv")
    lgsq (cmd-button "jumpapp -r logseq")

it cant execute these lines. but all the keyboard shortcuts it can execute. 

    aret (around alt ret)
    ultNext (around ctl (around alt j))
    ultPrev (around ctl (around alt k))

I hope you understood my problem.

╰─ systemctl status kmonad
● kmonad.service - kmonad keyboard config
     Loaded: loaded (/usr/lib/systemd/system/kmonad.service; disabled; pre>
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: active (running) since Sun 2023-07-16 08:57:54 +0530; 4min 17>
   Main PID: 33229 (kmonad)
      Tasks: 22 (limit: 9321)
     Memory: 5.4M
        CPU: 2.839s
     CGroup: /system.slice/kmonad.service
             └─33229 /usr/bin/kmonad etc/kmonad/config.kbd

Jul 16 08:58:18 fedora rofi[33296]: Failed to open display: (null)
Jul 16 08:58:18 fedora rofi[33296]: Connection has error
Jul 16 08:58:18 fedora kmonad[33293]: Program terminated.
Jul 16 08:58:20 fedora rofi[33300]: Failed to open display: (null)
Jul 16 08:58:20 fedora rofi[33300]: Connection has error
lines 1-17

**Comment by jtroo** [comment]
@JennytheDragon2000 this is happening because `jumpapp` inherits the environment, e.g. the user, from `kmonad`. You could try having kmonad start `jumpapp` with a different user:

    sudo -u <YOUR_LOGIN_USER> jumpapp ...

Otherwise if that doesn't work, you probably need to mess around in the `jumpapp` source to figure out what other info it needs (like maybe X session ID?). I'm no desktop programming expert though, so that's all the advice I have.

**Comment by Ultrahalf** [comment]
> it works. but the problem is kmonad can't run commands.
> 
> here are few lines of my config.
> 
> ```
> lbw (cmd-button "jumpapp -r librewolf")
> ktt (cmd-button "jumpapp -r kitty")
> mpv (cmd-button "jumpapp -r mpv")
> lgsq (cmd-button "jumpapp -r logseq")
> ```
> 
> it cant execute these lines. but all the keyboard shortcuts it can execute.
> 
> ```
> aret (around alt ret)
> ultNext (around ctl (around alt j))
> ultPrev (around ctl (around alt k))
> ```
> 
> I hope you understood my problem.
> 
> ╰─ systemctl status kmonad ● kmonad.service - kmonad keyboard config Loaded: loaded (/usr/lib/systemd/system/kmonad.service; disabled; pre> Drop-In: /usr/lib/systemd/system/service.d └─10-timeout-abort.conf Active: active (running) since Sun 2023-07-16 08:57:54 +0530; 4min 17> Main PID: 33229 (kmonad) Tasks: 22 (limit: 9321) Memory: 5.4M CPU: 2.839s CGroup: /system.slice/kmonad.service └─33229 /usr/bin/kmonad etc/kmonad/config.kbd
> 
> Jul 16 08:58:18 fedora rofi[33296]: Failed to open display: (null) Jul 16 08:58:18 fedora rofi[33296]: Connection has error Jul 16 08:58:18 fedora kmonad[33293]: Program terminated. Jul 16 08:58:20 fedora rofi[33300]: Failed to open display: (null) Jul 16 08:58:20 fedora rofi[33300]: Connection has error lines 1-17

sorry I misunderstood your problem
