### ISSUE TITLE
A GNOME Shell extension for KMonad

### ISSUE THREAD

**Issue by jurf** [kmonad/kmonad#720]
Hey, I made a simple [GNOME Shell extension](https://github.com/jurf/gnome-kmonad-toggle) for autostarting and controlling KMonad through the GNOME UI. Would you be interested in linking to it from the documentation?

**Comment by slotThe** [comment]
> Would you be interested in linking to it from the documentation?

Sure! Would you like to prepare a PR?

**Comment by jurf** [comment]
Sure! Any particular place you would prefer? The startup section or inside the Linux FAQ? Perhaps as a new section to installation?
