### ISSUE TITLE
Update latest compiled release

### ISSUE THREAD

**Issue by j-ace-svg** [kmonad/kmonad#725]
The compiled releases are a convenient way to install KMonad on systems without installing any tools to compile it yourself. However, the latest release is currently 3 years old. Many fixes and improvements have been made in that time (including a bug I just dealt with that has been patched) - it would be nice to have an up-to-date release so that we could use a prebuilt binary while getting these benefits.

I don't believe a pull request can be made to create a release (if so I could potentially create one) so I believe it has to be a maintainer/someone with control over the repository to do so.

**Comment by Gavinok** [comment]
Would also like to see this

**Comment by ArielHorwitz** [comment]
I believe this issue is solved:
https://github.com/kmonad/kmonad/releases/tag/0.4.2

**Comment by slotThe** [comment]
Indeed, thanks!
