### ISSUE TITLE
Map to a special symbol (e.g. "_") without holding shift

### ISSUE THREAD

**Issue by xihu91** [kmonad/kmonad#733]
According to the [tutorial](https://github.com/kmonad/kmonad/blob/master/keymap/tutorial.kbd#L381-L384),

> We have already seen other examples of modded buttons, \\(, \\), *, and +. There are no Keycodes for these buttons in KMonad, but they are buttons. They simply evaluate to `(around lsft x)`. All shifted numbers have their corresponding characters, the same is true for all capitals, and < > : ~ " | { } \\_ + and ?.

However, this causes some inconvenience and slows down my typing compared to QMK. The reason is that
1. If I try to type `a_b` but press `b` before releasing the key that mapped to `_`, it would become `a_B`.
2. More interestingly, if I actually try to type `a_BCD` but release `_` after I press and hold shift, then the shift is released even if I'm holding it, and I eventually get `a_bcd`.

To put it in the Kmonad language:

- We have some button `_`
- `_` is bound to '_' on the input keyboard
- the letters a, lsft are bound to themselves
- Px signifies the press of button x on the keyboard
- Rx signifies the release of said button
- Tx signifies the sequential and near instantaneous press and release of x
- 100 signifies 100ms pass

What it currently does:

    P_ Pa R_ Ra           -> _A 
    P_ Plsft R_ Ta    -> _a

What I expect it to do (so I can type the next key without worrying about releasing the previous key):

    P_ Pa R_ Ra           -> _a
    P_ Plsft R_ Ta    -> _A

~~I have a feeling that I might need to use the compose-key sequence but the [tutorial](https://github.com/kmonad/kmonad/blob/master/keymap/tutorial.kbd#L910-L960) might need some update. The example config doesn't match the document.~~

**Comment by jokesper** [comment]
for the second problem you could use `rsft`, though it would be a bit hacky and rely on `sft` being `lsft`.
The first is a bit mory tricky.
If you were to hold `_` your os would translate it to many `_`s. If you then press `a` linux (and I think windows and mac) translate stop repeating `_`s as if you had released it and only pressed `a`.
If we assume this is what the operating system does, one could release shift and then press a and press it again if `a` is released or something similar.
But there exists a system in which this isn't what you want:
For example if I use KMonad in a game and I bind one action to `_` (`lsft` + `-`)
and another to `a` and press both `a` and `_` I would want both to be held (or maybe a combination).
Still I think this could be a configuration option. Where you can specify how to handle shifted keys:
- `error`: Disallow implicit shifting
- `around`: The old behavior
- ???: Your new behavior (maybe one could even add an around variant or use `around-next-single`*)
*) `around-next-single` doesn't seem to be fully implemented / parsable
