### ISSUE TITLE
Gaming toggle key (ads, sprint etc)

### ISSUE THREAD

**Issue by Hoshi98** [kmonad/kmonad#735]
can you tell if this is even possible? so for example.....

press and release (tap) "z" key
"y" key auto repeats indefinitely
press and release (tap) "z" key
"y" key stops repeating

this "toggle" scenario comes in handy for many gaming situations. only reason why i'm bound to ahk. thanks

**Comment by slotThe** [comment]
At the moment, we have no way of seeing which keys are pressed, so a toggle like this is not possible
