### ISSUE TITLE
Spawning a terminal that isn't owned by kmonad

### ISSUE THREAD

**Issue by jmcarcell** [kmonad/kmonad#739]
Is there a way to spawn a terminal that isn't owned by kmonad with `cmd-button`?. I have the following:
```
(defalias
  sck (cmd-button "alacritty --working-directory /tmp")
)
```
The issue here is that when I restart or stop kmonad the terminal will be killed as it seems to be attached to its parent process. I have tried the obvious solutions with `nohup` `&` `disown` but I haven't made it work. 
Unrelated to this, the way terminals are spawned in kmonad is different from other ways: when doing this it doesn't source `/etc/zsh/zprofile` which is something that happens when I spawn another terminal from any other place (even from my windows manager (i3) with a similar command to the one above).

**Comment by slotThe** [comment]
> Is there a way to spawn a terminal that isn't owned by kmonad with `cmd-button`?.

There isn't; everything is spawned as child processes of the main `kmonad` process. This feels like the right thing to me intuitively; what are your use cases for restarting kmonad in the middle of a session? I don't think I've ever had to do that beyond experimenting with my configuration (which is a temporary thing).

> Unrelated to this, the way terminals are spawned in kmonad is different from other ways: when doing this it doesn't source `/etc/zsh/zprofile` which is something that happens when I spawn another terminal from any other place (even from my windows manager (i3) with a similar command to the one above).

`cmd-button` essentially just executes `/bin/sh -c «CMD»`, so it doesn't know about your user shell. It should, however, respect the environment that KMonad itself was started in (say, if you start it with your Xsession)

**Comment by jmcarcell** [comment]
> There isn't; everything is spawned as child processes of the main kmonad process. This feels like the right thing to me intuitively; what are your use cases for restarting kmonad in the middle of a session? I don't think I've ever had to do that beyond experimenting with my configuration (which is a temporary thing).

Precisely that, I still find that I want to make changes often and after a long session of work with lots of terminals open with different environments set in each it's mildly annoying having to close them. It's not a huge issue though.

> cmd-button essentially just executes /bin/sh -c «CMD», so it doesn't know about your user shell. It should, however, respect the environment that KMonad itself was started in (say, if you start it with your Xsession)

Hmm I have `systemd` start it so maybe that's why. I guess then I should give it a try to start it from my `.xinitrc` instead

**Comment by jmcarcell** [comment]
Closing since there is nothing to do here
