### ISSUE TITLE
MacBook M1 support (Miryoku layout)

### ISSUE THREAD

**Issue by xbladesub** [kmonad/kmonad#760]
I tried kmonad around 1 year ago and I didn't success with my m1. I'd like to know is it supported now and what should I know to be able to use it with M1?.

My goal is to remap my built-in macbook keyboard according to this:

![image](https://github.com/kmonad/kmonad/assets/45129790/16f73a2f-be96-4998-867f-9f19a6777dd4)

**Comment by molleweide** [comment]
silicon ships have been supported for two years at least - it is just a bit messy to build. I have pretty much the setup youre describing and when it works, then it works just as you'd imagine.
