### ISSUE TITLE
howto use multi-tap 

### ISSUE THREAD

**Issue by lowy** [kmonad/kmonad#761]
kmonad --version: 0.4.2 
i wanna to do something, exaple:
61 keymap default esc, one-tap is ` , double-tap is esc , and tap-hold-down is layer-together , how to do? 
just like this sure ok:
(defalias
  grv (tap-hold-next 300 
        (multi-tap 300 ` (layer-toggle volctl) esc)
        `))

**Comment by slotThe** [comment]
I think I'm missing a question here—sounds like everything works fine?

**Comment by lowy** [comment]
same question: multi-tap-hold #203
Maybe I didn't make it clear, What should I do if I have the same problem?

**Comment by slotThe** [comment]
You should… wait until the issue is resolved :) Or submit a PR yourself!
