### ISSUE TITLE
Karabiner 14.13.0 installs Karabiner DriverKit VirtualHIDKeyboard 1.7.0 seems to break kmonad

### ISSUE THREAD

**Issue by TC72** [kmonad/kmonad#779]
I'm only just getting started with configuring kmonad so still relying on Karabiner right now.
I updated it yesterday and it forced me to restart my machine so I guess there were some low level changes.

After restarting I see the VirtualHIDKeyboard is showing 1.7.0. If I try to run kmonad I see the message `connected` but no keyboard inout works. I use my mouse to shutdown the iTerm running kmonad and disconnecting and reconnecting my keyboard gets it working again.

I did build against the new version of Karabiner, with this command:
```
 stack build --flag kmonad:dext --extra-include-dirs=c_src/mac/Karabiner-DriverKit-VirtualHIDDevice/include/pqrs/karabiner/driverkit:c_src/mac/Karabiner-DriverKit-VirtualHIDDevice/src/Client/vendor/include
```

I am on the very latest Apple release Sonoma 14.2 which I also upgraded yesterday but I think the Karabiner update is the more likely issue.

Running
```
 defaults read /Applications/.Karabiner-VirtualHIDDevice-Manager.app/Contents/Info.plist CFBundleVersion
```
Shows `3.1.0`

No complaints, I know I shouldn't have upgraded. Just wanted to put this out there in case it helps someone else before they break their install.

**Comment by slotThe** [comment]
This sounds like: https://github.com/kmonad/kmonad/pull/716#issuecomment-1854622531 See there for more (and a potential fix!)
