### ISSUE TITLE
Cannot translate to windows keycode

### ISSUE THREAD

**Issue by tsengf** [kmonad/kmonad#785]
Posted this in the discussions section but realized this may be a better place. I run in a Windows environment and built KMonad from top of tree. 50% of the time I start up KMonad, I receive the following message.

```
Encountered error in KeySink: Cannot translate to windows keycode: Missing254
Encountered error in <emitter_proc>: Cannot translate to windows keycode: Missing254
```

What does this message mean, and how can I debug it? Thanks.

**Comment by bogorad** [comment]
Same here. Pressed two keys - `(layer-toggle U_BUTTON))` and `KeyUndo`:

```
> .\kmonad-0.4.1-win.exe -l debug .\miryoku_kmonad.kbd
Opening KeySink
Initializing Windows key sink
Opening KeySource
Registering low-level Windows keyboard hook
Launching process: emitter_proc

--------------------------------------------------------------------------------
Received event: Release <ret>
Running hooks

--------------------------------------------------------------------------------
**Received event: Press </>**
Running hooks
Block level set to: 1
Registering untimed hook: 2
Registering 200ms hook: 1

--------------------------------------------------------------------------------
**Received event: Press <z>**
Running hooks
Registering untimed hook: 4
Registering 82ms hook: 3
Storing event, current store:
 - Press <z>

Cancelling hook: 3
Pushed layer to stack: U_BUTTON
 1. U_BUTTON
Base-layer: U_BASE

Registering untimed hook: 5
Unblocking input stream, rerunning:
Press <z>


--------------------------------------------------------------------------------
Rerunning event: Press <z>
Running hooks
Registering untimed hook: 6
Registering untimed hook: 7
Registering untimed hook: 8
**Emitting: Press <undo>**
**Encountered error in KeySink: Cannot translate to windows keycode: KeyUndo**

--------------------------------------------------------------------------------
Received event: Release <z>
Encountered error in <emitter_proc>: Cannot translate to windows keycode: KeyUndo
Running hooks
Closing process: emitter_proc
Closing KeySource
Unregistering low-level Windows keyboard hook
Closing KeySink
Closing Windows key sink
```

**Comment by bogorad** [comment]
Same here for KeyAgain:

```
Emitting: Press <again>
Encountered error in KeySink: Cannot translate to windows keycode: KeyAgain
Encountered error in <emitter_proc>: Cannot translate to windows keycode: KeyAgain
Closing process: emitter_proc
```

I'm trying https://github.com/manna-harbour/miryoku_kmonad under Windows.

**Comment by ryantam626** [comment]
```diff
diff --git a/src/KMonad/Keyboard/IO/Windows/Types.hs b/src/KMonad/Keyboard/IO/Windows/Types.hs
index 77f60bf..106256e 100644
--- a/src/KMonad/Keyboard/IO/Windows/Types.hs
+++ b/src/KMonad/Keyboard/IO/Windows/Types.hs
@@ -473,8 +473,8 @@ keyCodeToWinCode = M.fromList
   -- , (KeySendFile, ???)
   -- , (KeyDeleteFile, ???)
   -- , (KeyXfer, ???)
-  -- , (KeyProg1, ???)
-  -- , (KeyProg2, ???)
+   , (KeyProg1, 0xB6)
+   , (KeyProg2, 0xB7)
   -- , (KeyWww, ???)
   -- , (KeyMsDos, ???)
   -- , (KeyCoffee, ???)
@@ -579,6 +579,6 @@ keyCodeToWinCode = M.fromList
   -- , (Missing251, ???)
   -- , (Missing252, ???)
   -- , (Missing253, ???)
-  -- , (Missing254, ???)
+   , (Missing254, 0x00)
   -- , (Missing255, ???)
   ]
```

here is a diff that I applied to kmonad source before compling, seems to sort it out, haven't had a crash in a while, still smoke testing personally at the moment, hopefully this helps! 

basically `winCodeToKeyCode` contains a mapping to `Missing254` but the reverse mapping of `Missing254` in `keyCodeToWinCode` is missing, that diff just adds it along other two entries that i found to be missing.

**Comment by kareemmahlees** [comment]
@ryantam626 ok so what about the other way around!?
```
Encountered error in KeySource: Cannot translate from windows keycode: 1819042164
```
There are multiple keycodes that are causing this so if you could explain the approach ( to someone who doesn't know haskell )

**Comment by ajwells256** [comment]
> @kareemmahlees I also don't know haskell 😅 So I can't be immediately helpful on that front.
> 
> My first observation is that 1819042164 doesn't seem to be a valid window keycode anyway, do you have any ideas where is it coming from? I have been seeing something like this at work as well, but I can't pinpoint where are they coming from, and it seems to be only on start up, so usually I just repeated try to start up kmonad a few times until this stop happening. (ref: https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes kmonad's window keycode list is mostly taken from here I believe)

Wow it really feels like I ghostwrote this :sweat_smile: 

I've been meaning to try to figure out why the program crashes and change the behavior so that failed keycode maps are logged but don't stop the flow. This doesn't seem to be the case currently (hence the repeated startups), but my brief glance at the code tells me I don't know enough Haskell right now to figure it out immediately. We could also ignore (or pass through?) keycodes that are obviously outside the range of acceptable values.

**Comment by dougpowers** [comment]
I'm getting identical behavior using kmonad 4.1, since there aren't any Windows binaries for the later releases and I don't have a development environment up yet.
