### ISSUE TITLE
Windows binary unable to load even default testing config.

### ISSUE THREAD

**Issue by dnaik42** [kmonad/kmonad#787]
Here's the config I'm using for testing

```
(defcfg
  input (low-level-hook)
  output (send-event-sink 300 100)
)

(defsrc q w e r t y lsft)

(deflayer base
  q w e r t y lsft)
```

and this is the error that pops up:

```
kmonad-0.4.0-windows.exe: Parse error at 3:3:
  |
3 |   output (send-event-sink 300 100)
  |   ^
unexpected 'o'
expecting ')'   
```

The same thing happens for any other config I try out.

**Comment by slotThe** [comment]
This is curious indeed, but version `0.4.0` is… a bit on the old side as well. Could you try with either the newest binary available for your OS (I guess that would be `0.4.1`) or compile KMonad yourself?

**Comment by dnaik42** [comment]
@slotThe version 0.4.1 binary gives the exact same error

**Comment by slotThe** [comment]
Well, this is certainly curious. Could you upload *the exact file* that's giving you this issue somewhere?

**Comment by dnaik42** [comment]
[testing.zip](https://github.com/kmonad/kmonad/files/13853367/testing.zip)

**Comment by slotThe** [comment]
Mh, sorry I can't reproduce this at all with any released version of KMonad (with that very file). I suppose make sure that your OS doesn't garble the file somehow and inserts strange characters
