### ISSUE TITLE
Keycode for <

### ISSUE THREAD

**Issue by haferburg** [kmonad/kmonad#792]
kmonad: Parse error at 30:8:
       |
    30 |   lsft <    z    x    c    v    b    n    m    ,    .    /    rsft
       |        ^
    unexpected '<'
    expecting ')' or keycode

Couldn't find it in https://github.com/kmonad/kmonad/blob/master/src/KMonad/Keyboard/Keycode.hs

On German keyboards there's a key with <, >, and |.
See here (bottom left).
![image](https://github.com/kmonad/kmonad/assets/4941909/8d9c9b05-edcd-47c8-b26f-3805060d98ba)

**Comment by slotThe** [comment]
Your `defsrc` should be based on a us layout; it's only in your first `deflayer` that you can do anything you want. (I believe `<` is not available as a straight keycode, but only as a shifted version of `,`, so `defsrc` does not like it)
