### ISSUE TITLE
is it unsolvable using Logitech K400 Plus with touchpad

### ISSUE THREAD

**Issue by vincentaxhe** [kmonad/kmonad#801]
It's being a year, I get many kmonad-git updates, I try my Logitech K400 Plus again with kmonad, but unfunately it's the same problem, once use touchpad ,kmonad fail and quit.
fail info as blow:
kmonad: toEnum{Keycode}: tag (272) is outside of enumeration's range (0,255)
CallStack (from HasCallStack):
  error, called at src/KMonad/Keyboard/Keycode.hs:311:32 in kmonad-0.4.2-8oQHCGjCGLl6RkBR2pFHD8:KMonad.Keyboard.Keycode

If it's unsolvable ,I better sell it soon.

**Comment by jokesper** [comment]
I think your problem may be fixed with #807.

**Comment by vincentaxhe** [comment]
It's a good news, but I have give it away, cannot test it anymore
