### ISSUE TITLE
[FR] Arabic character support

### ISSUE THREAD

**Issue by mdSlash** [kmonad/kmonad#811]
KMonad lacks support for Arabic Unicode. Would you please consider adding Arabic support in the near future?

**Comment by mdSlash** [comment]
Hey @slotThe, thanks for this awesome project. I wanna contribute by adding Arabic characters. What do I need to do to achieve that? Do I just need to add the characters to the "ComposeSeq.hs" file, or is there something else I should do?

**Comment by slotThe** [comment]
@mdSlash I don't really know how Arabic characters work, but if they can be composed using X11 compose key sequences then that file is exactly the right place to add them!

**Comment by mdSlash** [comment]
It doesn't necessarily require inserting Arabic characters. I'm using `setxkbmap` to change the layout to Arabic and adding English characters with their Arabic equivalents in the KMonad config.
