### ISSUE TITLE
Please provide precompiled binaries for windows again

### ISSUE THREAD

**Issue by hupfdule** [kmonad/kmonad#818]
The README states: “You can download binaries for Windows and Linux (64bit) from the [releases page](https://github.com/kmonad/kmonad/releases)”, but unfortunately for the current release 0.4.2 only a Linux binary is available. It would be great if a precompiled Windows binary could be provided as well.

**Comment by slotThe** [comment]
See https://github.com/kmonad/kmonad/issues/767

**Comment by anotatta** [comment]
I forked the workflow from [https://github.com/ForkPrince/kmonad](ForkPrince).
Then run the workflow for 0.4.3. Here is the link: [https://github.com/anotatta/test-kmonad/actions/runs/11230218330/artifacts/2027809936](kmonadWindowsBinary).
