### ISSUE TITLE
Delay in the tap part of `tap-hold`

### ISSUE THREAD

**Issue by paniash** [kmonad/kmonad#827]
Hi!

I recently came across kmonad and was wondering if this is a common issue and if so, how I could rectify it.

I'm remapping capslock to act as escape when tapping and ctrl when holding. The holding part works just as expected. However, when tapping capslock, there is a noticeable delay for the escape to act. Not deal-breaking, but noticeable compared to if I just remap capslock to act as escape all the time.

Here's the line in my config:
```
(defalias
  axx (tap-hold 300 esc lctl)     ;; Long delay for easier testing
)
```

With `@axx` going at the position of the capslock key in the `deflayer` section.

I'd appreciate any help! Thanks!!

**Comment by slotThe** [comment]
Well, we have to know whether we should act as escape or caps! :) This is pretty unavoidable, I think. You can experiment with the different variants of tap-* keys, like `tap-hold-next`, `tap-next-release`, `tap-hold-next-release`, … to see if the behaviour of any of these is more to your liking (though with a key that often gets pressed on its own—like escape—this may not yield anything completely satisfactory)
