### ISSUE TITLE
before-after-next unstable

### ISSUE THREAD

**Issue by vincentaxhe** [kmonad/kmonad#832]
for it is unstable that it is not mentioned in any doc file?
I try it to auto quit hyprland submap with 'wms  ( before-after-next M-A-s esc )', but it sometimes cannot quit "split submap", sometimes it worked fine.
It's being some days it exists, and did not improved much.

**Comment by slotThe** [comment]
That is… not a key that exists in kmonad

**Comment by vincentaxhe** [comment]
> That is… not a key that exists in kmonad

oh, it is written in src/KMonad/Args/Parser.hs, kmonad -d didnot tell me wrong.

**Comment by slotThe** [comment]
Oh, well seems like I was wrong, then :) Trying it out just now I do not notice any problems, though

**Comment by vincentaxhe** [comment]
```
bind = $mainMod ALT, S, submap, split
submap = split
	bind = , 1, splitratio, 0.1
	bind = , q, splitratio, -0.1
	bind = , 2, splitratio, 0.2
	bind = , w, splitratio, -0.2
	bind = , 3, splitratio, 0.3
	bind = , e, splitratio, -0.3
	bind = , 4, splitratio, 0.4
	bind = , r, splitratio, -0.4
	bind = , 5, splitratio, 0.5
	bind = , t, splitratio, -0.5
	bind = , 6, splitratio, 0.6
	bind = , y, splitratio, -0.6
	bind = , 7, splitratio, 0.7
	bind = , u, splitratio, -0.7
	bind = , 8, splitratio, 0.8
	bind = , i, splitratio, -0.8
	bind = , 9, splitratio, 0.9
	bind = , o, splitratio, -0.9
	bind = ,escape,submap,reset
	bind = ,return,submap,reset
submap = reset
```
I test its behavior, It should work but not work always, sometimes 'esc' didnot quit split mode, I add some pause time didnot make it right.Maybe it is Hyprland's fault.
The key seems to be left forgotton, so docs need to include it, give example, and test more.
I assume if before-after-next is an official member, there is a lot to do, the issue is not completed yet
