### ISSUE TITLE
Issues setting up with nixos

### ISSUE THREAD

**Issue by hfytr** [kmonad/kmonad#837]
So Im trying to setup nixos by following the instructions at the bottom of Installation.md. However I run into an error: 
`
/build/.attr-0l2nkwhif96f51f4amnlf414lhl4rv9vh8iffyp431v6s28gsr90: line 14: /nix/store/l50k5c4amwy1cj3bg72xbc4rds68c1ds-kmonad-0.4.2/bin/kmonad: No such file or directory
error: builder for '/nix/store/cjqvly4gspymnix7vnl92w5g5d49w9s3-kmonad-myKMonadOutput.cfg.drv' failed with exit code 127
error: 1 dependencies of derivation '/nix/store/slgx34rwl9c6ql033xkbi1i1417pjf0h-unit-script-kmonad-myKMonadOutput-start.drv' failed to build
error: 1 dependencies of derivation '/nix/store/diqfvs6i40qhw66z1mg5zndl6lzfrc66-unit-kmonad-myKMonadOutput.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/pb8va0yf693nh0ly7x0aaq4cirbna17d-system-units.drv' failed to build
error: 1 dependencies of derivation '/nix/store/kvsqgdl1nhhk3pvf6ikf7q97l8528c20-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/44mppz4jr712mw0vipkp47dc8yjm4aa1-nixos-system-nixos-24.05pre621993.25865a40d14b.drv' failed to build
`

**Comment by slotThe** [comment]
Curious! Do you have the full log perhaps? (N.b.: if you use flakes, I would strongly recommend to add `kmonad` to your inputs, and use our nix module)

**Comment by hfytr** [comment]
When you say logs do you mean the full output of nixos-rebuild switch: https://pastebin.com/BZfQMJn1

As for the second part of your message, this is how im setting up kmonad: 
```
  imports = [
    ./kmonad-module.nix
    ...
  ];

  services.kmonad = {
    enable = true;
    keyboards = {
      laptopKeeb = {
        device = "/dev/input/by-path/platform-i8042-serio-0-event-kbd";
        config = builtins.readFile /home/fbwdw/.config/kmonad.conf;
      };
    };
    package = pkgs.haskellPackages.kmonad;
  };

  environment.systemPackages = with pkgs; [
    haskellPackages.kmonad
    ...
  ];
```

**Comment by slotThe** [comment]
Perhaps try passing `-v` to `nixos-rebuild`? The error saying it can't find some binary is not super helpful :)

**Comment by hfytr** [comment]
heres the the tail end of the output:
```
these 14 derivations will be built:
  /nix/store/6kjzbpbmjiia2037c4c56md9s6a4wh87-system-path.drv
  /nix/store/p1wsyxkw8hfjvnydjh2q7zcwwmc53687-dbus-1.drv
  /nix/store/0w2wslisnyff1mn4xmz85fknh5gcy52b-X-Restart-Triggers-dbus.drv
  /nix/store/6mmzdljax7nkcvmhxqg9iadbhlzcf0n3-unit-dbus.service.drv
  /nix/store/1y750bisy67if49z19cpl4cniz3gh87c-user-units.drv
  /nix/store/l7snr5aqzazakpy0nrs2aihlz6livc0z-X-Restart-Triggers-polkit.drv
  /nix/store/n1j9p8glcdwfpc7bybpasxg2gswxb4yp-unit-polkit.service.drv
  /nix/store/vm0wnjy1haff0sscb2ad9g7vqh1zjgrk-kmonad-laptopKeeb.cfg.drv
  /nix/store/dz86bs3cb9nhcw60dsqfhmvjs7qg2whh-unit-script-kmonad-laptopKeeb-start.drv
  /nix/store/qiz6gav9z466qwl9spcy0fzhpx0cipp9-unit-kmonad-laptopKeeb.service.drv
  /nix/store/x3496qvq26v083f9mh99zp05l5h4nkv8-unit-dbus.service.drv
  /nix/store/jwghmvb2h4wbhhr2q2fikiqn88gwk326-system-units.drv
  /nix/store/l8rwmhb3l89fvysn0f3311mcc3hd63g7-etc.drv
  /nix/store/06ygyimp3adj7xih0zsniflxg4qxjrrg-nixos-system-nixos-24.05pre621993.25865a40d14b.drv
building '/nix/store/6kjzbpbmjiia2037c4c56md9s6a4wh87-system-path.drv'...
building '/nix/store/vm0wnjy1haff0sscb2ad9g7vqh1zjgrk-kmonad-laptopKeeb.cfg.drv'...
warning: collision between `/nix/store/k69i05cv62dn8zncyk8ry4mnyqdgc3h7-toybox-0.8.11/bin/readelf' and `/nix/store/8mjb3ziimfi3rki71q4s0916xkm4cm5p-gcc-wrapper-13.2.0/bin/readelf'
warning: collision between `/nix/store/k69i05cv62dn8zncyk8ry4mnyqdgc3h7-toybox-0.8.11/bin/strings' and `/nix/store/8mjb3ziimfi3rki71q4s0916xkm4cm5p-gcc-wrapper-13.2.0/bin/strings'
warning: collision between `/nix/store/7kq9hvrhcy8g1v0jd07nr54279asg9vc-systemd-255.4/bin/halt' and `/nix/store/k69i05cv62dn8zncyk8ry4mnyqdgc3h7-toybox-0.8.11/bin/halt'
warning: collision between `/nix/store/7kq9hvrhcy8g1v0jd07nr54279asg9vc-systemd-255.4/bin/reboot' and `/nix/store/k69i05cv62dn8zncyk8ry4mnyqdgc3h7-toybox-0.8.11/bin/reboot'
warning: collision between `/nix/store/7kq9hvrhcy8g1v0jd07nr54279asg9vc-systemd-255.4/bin/poweroff' and `/nix/store/k69i05cv62dn8zncyk8ry4mnyqdgc3h7-toybox-0.8.11/bin/poweroff'
/build/.attr-0l2nkwhif96f51f4amnlf414lhl4rv9vh8iffyp431v6s28gsr90: line 14: /nix/store/l50k5c4amwy1cj3bg72xbc4rds68c1ds-kmonad-0.4.2/bin/kmonad: No such file or directory
error: builder for '/nix/store/vm0wnjy1haff0sscb2ad9g7vqh1zjgrk-kmonad-laptopKeeb.cfg.drv' failed with exit code 127
error: 1 dependencies of derivation '/nix/store/dz86bs3cb9nhcw60dsqfhmvjs7qg2whh-unit-script-kmonad-laptopKeeb-start.drv' failed to build
error: 1 dependencies of derivation '/nix/store/qiz6gav9z466qwl9spcy0fzhpx0cipp9-unit-kmonad-laptopKeeb.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/jwghmvb2h4wbhhr2q2fikiqn88gwk326-system-units.drv' failed to build
error: 1 dependencies of derivation '/nix/store/l8rwmhb3l89fvysn0f3311mcc3hd63g7-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/06ygyimp3adj7xih0zsniflxg4qxjrrg-nixos-system-nixos-24.05pre621993.25865a40d14b.drv' failed to build
```

**Comment by kintrix007** [comment]
@hfytr Are you running NixOS 23.11? If so that could explain. The nixos-module they have refers to `pkgs.kmonad` which only exists on Unstable. Simply replace that with `pkgs.haskellPackages.kmonad` and you are good to go -- that one exists on 23.11.

**Comment by BirbIrl** [comment]
hello, i'd like to chip in!
using the exact same config on unstable (with different paths), i get the same error as above both with `pkgs.haskellPackages.kmonad and pkgs.kmonad`

when i use
pkgs.haskellPackages.kmonad
and remove
`package = pkgs.haskellPackages.kmonad;`
the system rebuilds, and kmonad launches for a second before crashing right after i'm done with the rebuild-switch.
same result when i use

pkgs.kmonad
and add
`package = pkgs.kmonad`

The config works when ran with the shell command

For now i'll just have it startup with hyprland. Loving it so far :D

**Comment by slotThe** [comment]
I have added some flake instructions in 9affc9f85e84e4648d097427aa9ed99ad4c0418f, which should hopefully be a bit more robust

**Comment by BirbIrl** [comment]
Hello! I'm a bit late due to uni, but it turns out - kmonad works... perfectly fine after a reboot using the old guide! whoops, should've probably checked that. I think it'd be helpful to tell users in the guide to test that.

this is without flakes. I have home manager installed as a module but it shouldn't be relevant for this:

```
     imports =
       [
         #...
         /path/to/nixos-module.nix
       ];

#...

environment.systemPackages = with pkgs; [

#...

kmonad

];

 #...
  services.kmonad = {
  enable = true;
  keyboards = {
   myKMonadOutput = {
  device = "/dev/input/by-id/[KEYBOARD];
  config = builtins.readFile ./config.kbd; # assuming the config is in the same directory as this nix file
    };
  };
  package = pkgs.kmonad;
  };  
```
