### ISSUE TITLE
"around" mapping that releases the modifier immediately

### ISSUE THREAD

**Issue by durka** [kmonad/kmonad#840]
On an unmodified keyboard, modifier keys can be released separately from the modified key. In other words, I can do this:

```
press shift
press a
release shift
release b
release a
```
This types `Ab`.

However if I use kmonad to map something else to `A`, then they are always released together. Assume I mapped `a` to `A`. Then this

```
press a
press b
release a
```
means
```
press shift
press a
press b
release b
release shift
release a
```
This types `AB`.

I have a layer with a lot of symbols and I type quickly, so I am making a lot of typos with capital letters after symbols due to this issue.

Is there any way to map `a` to `A`, *but* release the virtual shift key once the `A` is emitted, so that I can recover the `Ab` behavior?

**Comment by durka** [comment]
I found a workaround. Instead of mapping to a symbol that requires shift to be held down, I defined these aliases:

```
(defalias press_shift (press-only sft))
(defalias release_shift (release-only sft))
```

Then I can make a tap macro for the target of a symbol:

```
(defalias underscore #(@press_shift min @release_shift))

(deflayer symbols [...] @underscore
```

This has the disadvantage of making my symbols layer require an alias for almost every key. Is there a better way?

**Comment by slotThe** [comment]
> _Is_ there any way to map `a` to `A`, _but_ release the virtual shift key once the `A` is emitted, so that I can recover the `Ab` behavior?

How would this work with key-repeat? When holding down `A`, do you then get `Aaaaaaaaaaaaaaaaaaaa…`?

**Comment by durka** [comment]
That's what happens if I do Shift+A and release Shift while holding down A,
so yes.

**Comment by slotThe** [comment]
But when you press `S-A` and release `S`, then you're actually… releasing something! That's not the case when you just press and hold `A`

**Comment by durka** [comment]
In this case I'm releasing the modifier that activates the layer containing
these symbol mappings.

**Comment by jokesper** [comment]
This is the same problem described in #733. Later today I may try to implement a proper solution.
