### ISSUE TITLE
Having to specify the device file twice with the NixOS module

### ISSUE THREAD

**Issue by kintrix007** [kmonad/kmonad#845]
There is a duplication with the NixOS module. We need to first specify the keyboard device as such:

```nix
# configuration.nix
services.kmonad = {
  enable = true;
  keyboards = {
    builtinKeyboard = {
      device = "/dev/input/path/to/device/file";
      config = builtins.readFile /path/to/config.kbd;
```

Then in the config we need to specify it again:

```kbd
;; config.kbd

(defcfg
  input (device-file "/dev/input/path/to/device/file")
  output (uinput-sink "My KMonad Output")
)
```

There should be a way to tell KMonad to use whatever was specified in the NixOS config so there is not a need for this duplication.

Of course, there is the solution of having the whole config inside the Nix description as a string literal and do some string interpolation. But that is not very clean in my opinion.

**Comment by slotThe** [comment]
You probably want to use the [defcfg](https://github.com/kmonad/kmonad/blob/master/nix/nixos-module.nix#L36) option; quoting from its doc string:

> Automatically generate the defcfg block.
>
> When this is option is set to true the config option for
> this keyboard should not include a defcfg block.

**Comment by kintrix007** [comment]
Thank you, I completely missed that
