### ISSUE TITLE
Unrecognized compose-char "stepped"

### ISSUE THREAD

**Issue by caph1993** [kmonad/kmonad#864]
I am trying to use the `stepped` functionality explained in the [tutorial](https://github.com/kmonad/kmonad/blob/master/keymap/tutorial.kbd#L504) and the [quick reference](https://github.com/kmonad/kmonad/blob/master/doc/quick-reference.md#general-purpose-buttons). I copied and pasted, but kmonad reports a syntax error, as if `stepped` did not exist.

```
kmonad: Parse error at 208:11:
    |
208 |   ctl-lck (stepped (press-only lctl) (release-only lctl))
    |            ^
Unrecognized compose-char
```

Is this a bug? Is there a workaround? Thanks in advance.

I'm using the latest binary, with version `0.4.2, commit 3da3165c413225d924a55933b723ff8ee00f9231` obtained with the command `./kmonad -V`.

**Comment by caph1993** [comment]
I found the problem. The `stepped` functionality is too recent, and is not present in the latest released version (0.4.2).

I built the latest (unreleased) version following the [docker-based build instructions](https://github.com/kmonad/kmonad/blob/master/doc/installation.md#using-docker), and it worked!

It was as simple as  running these three commands:

```sh
docker build -t kmonad-builder github.com/kmonad/kmonad.git
docker run --rm -it -v ${PWD}:/host/ kmonad-builder bash -c 'cp -vp /root/.local/bin/kmonad /host/'
docker rmi kmonad-builder 
```

**Comment by jokesper** [comment]
Hmmm, this mismatch between docs and code is somewhat unfortunate, a solution would having a release and master branch.
(Spekulation)
Though this was probably tried, evidient by the fact that a develop branch exists, but people (including me) simply make their pr against the default branch or something.

Maybe a link to the docs at a specific commit?

**Comment by caph1993** [comment]
Or maybe writting in the docs "supported since version x.x.x" for those that are already supported, and something like "(only supported in dev version)". And updating those comments during each release.

**Comment by slotThe** [comment]
I think it's quite natural that the docs on `master` should be for the development version. For matching documentation there are always the respective release tags

**Comment by jokesper** [comment]
> I think it's quite natural that the docs on `master` should be for the development version.

True, but the problem lies in navigating to the docs.
Simply using the link to the tutorial on [kmonad/kmonad](github.com/kmonad/kmonad) would result on docs not matching the release.
Originally I was thinking something like this (and maybe this is the correct solution):
```diff
diff --git a/README.md b/README.md
index 3ed0551..353a1d2 100644
--- a/README.md
+++ b/README.md
@@ -60,10 +60,13 @@ For more information on how to install KMonad, please refer to:
 ## Configuration
 
 For information on how to configure KMonad, please refer you to:
-- [the configuration tutorial](keymap/tutorial.kbd)
-- [quick reference](doc/quick-reference.md)
+- [the configuration tutorial] [(latest git)](keymap/tutorial.kbd)
+- [quick reference] [latest git](doc/quick-reference.md)
 - [user configurations](https://github.com/kmonad/kmonad-contrib)
 
+[the configuration tutorial]: https://github.com/kmonad/kmonad/blob/0.4.2/keymap/tutorial.kbd
+[quick reference]: https://github.com/kmonad/kmonad/blob/0.4.2/doc/quick-reference.md
+
 Want to add your own keyboard configuration to [kmonad-contrib]? Just
 fork the repository, create a new subdirectory using your GitHub
 username and submit a pull request!https://github.com/kmonad/kmonad/blob/0.4.2/doc/quick-reference.md
```

But this means fixes to the docs, which don't add new commands, wouldn't be seen until the next release.

> Or maybe writting in the docs "supported since version x.x.x"

This is probably the best solution.

**Comment by slotThe** [comment]
> […] the problem lies in navigating to the docs. Simply using the link to the tutorial on [kmonad/kmonad](github.com/kmonad/kmonad) would result on docs not matching the release.

I don't think so. If you're on the respective release tag, e.g., [0.4.2](https://github.com/kmonad/kmonad/tree/0.4.2) then all repo-internal links should also point to that that

> > Or maybe writting in the docs "supported since version x.x.x"
>
> This is probably the best solution.

Probably the most workable one, yes
