### ISSUE TITLE
fn layer registers lctrl & lalt separately but not together

### ISSUE THREAD

**Issue by JonnySB** [kmonad/kmonad#865]
Hi, I'm not sure if this is a bug or user error but thought I'd raise it to see if anyone else has come across the same thing. Basically, I have an fn layer mapped, and yesterday I ran into an issue where I messed up some configuration on my computer and nuked my graphical tty, and I couldn't swap into a different tty to fix it with the inbuilt keyboard. 

Issue:
My other layers that have both a ctrl and alt key mapped seem to have no problem registering both being held at the same time to modify a key on that layer (E.g. lctr+lalt+1 on my numpad layer). However, on the fn layer, they will register and modify a key individually (E.g. lalt+F1, or lctl+F1), but they will not register at the same time (E.g. lalt+lctl+F1).

Is this known behaviour that I am missing, a bug or am I doing something wrong?

gist of my [config](https://gist.github.com/JonnySB/4067131a2d635575cd95cec91a8dd54a)

**Comment by jokesper** [comment]
This sounds like a roll over issue between the keys `q`, `j` and `k`.
Take a look at this [FAQ Entry](https://github.com/kmonad/kmonad/blob/master/doc/faq.md#q-why-do-some-key-combination-not-work).
t.l.d.r.:
Try pressing q, j and k on some rollover testing website while kmonad is deactivated.
If it doesn't register all three key presses, it's probably the fault of your keyboard.

**Comment by JonnySB** [comment]
Ah seems you are bang on with the roll-over issue. It's not something I've come across before but for any interested readers of this thread in the future, I'm on an xps15 laptop.  You are right that I am able to trigger the correct combo by starting with the lctl + lalt keys from my base later, then pressing the fn layer toggle, and then the desired Fn key. I'm sure I tried that yesterday but likely in a less intentional way and so didn't get the ordering correct. Will consider whether it's worth putting in a 'rescue' layer for my sins, although - as you say - it's pretty rare that I actually need another tty and can just plug in another keyboard temporarily. Thanks for the help!
