### ISSUE TITLE
The current relase is almost a year old

### ISSUE THREAD

**Issue by hirak99** [kmonad/kmonad#879]
As I was reading the documentation, I noticed it covers new features such as named sources, which do not work in the released version.

Then I realized that the last release is very old - and there has been quite a few new feature additions and bug fixes since then.

The last release 0.4.2 happened on 2023-Oct-07.

Is it time for a new release? :)

**Comment by jokesper** [comment]
I would suggest merging #873 as #859 is partially broken and then doing a release.

**Comment by slotThe** [comment]
Sounds like a good idea to me (although I'm hesitant to go a step further and revert https://github.com/kmonad/kmonad/commit/2d11c6306ebd209796474da83efeefd607a30e6c just yet)

**Comment by jokesper** [comment]
I agree on that though the fixes should still be made.

**Comment by slotThe** [comment]
Done in https://github.com/kmonad/kmonad/releases/tag/0.4.3 :)
