### ISSUE TITLE
Should a basic .kbd config on linux work OOB on windows?

### ISSUE THREAD

**Issue by ASong5** [kmonad/kmonad#886]
I'm not sure if there are additional steps that need to be taken and/or whether or not various mappings should have a one-to-one functionality between the two operating systems, but I am having trouble making my config on linux work correctly on Windows. 

```
(defcfg
  ;; ** For Linux **
  input  (device-file "/dev/input/by-id/usb-ROYUAN_EPOMAKER_TH80_SE-event-kbd")
  ;; input  (device-file "/dev/input/by-id/usb-Matias_Ergo_Pro_Keyboard-event-kbd")
  output (uinput-sink "KMonad output")

  ;; ** For Windows **
  ;; input  (low-level-hook)
  ;; output (send-event-sink)

  ;; ** For MacOS **
  ;; input  (iokit-name "my-keyboard-product-string")
  ;; output (kext)

  fallthrough true
  allow-cmd true
)

(defsrc
  esc     f1   f2   f3   f4   f5   f6   f7   f8   f9   f10  f11  f12
  grv     1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab     q    w    e    r    t    y    u    i    o    p    [    ]    \
  caps    a    s    d    f    g    h    j    k    l    ;    '    ret
  lsft      z    x    c    v    b    n    m    ,    .    /    rsft
  lctl    lmet lalt           spc            ralt rmet cmp  rctl
)
 
(defalias
  ext (layer-toggle extend) ;; Bind 'ext' to the Extend Layer
  qwe (layer-switch qwerty) ;; Set qwerty as the base layer
  col (layer-switch colemak-dh) ;; Set colemak as the base layer
  sym (layer-toggle symbols)
)

(defalias
  lalt (sticky-key 500 lalt)
  lmet (sticky-key 500 lmet)
  lsft (sticky-key 500 lsft)
  lctl (sticky-key 500 lctl)
  cpy C-c
  pst C-v
  cut C-x
  udo C-z
  rdo C-y
  all C-a
  fnd C-f
  dwd C-bspc
  bk Back
  fw Forward
  lpar S-9
  rpar S-0
  exc S-1
  at S-2
  hsh S-3
  amp S-7
  star S-8
  pct S-5
  dlr S-4
  fwsl \
  chm (cmd-button "/home/pundrew/scripts/toggle_input_source.sh")
)

(deflayer qwerty
  esc     f1   f2   f3   f4   f5   f6   f7   f8   f9   f10  f11  f12
  grv     1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab     q    w    e    r    t    y    u    i    o    p    [    ]    \
  @ext    a    s    d    f    g    h    j    k    l    ;    '    ret
  lsft      z    x    c    v    b    n    m    ,    .    /    rsft
  lctl    lmet lalt           spc            ralt rmet cmp  rctl

)

(deflayer colemak-dh
  esc     f1   f2   f3   f4   f5   f6   f7   f8   f9   f10  f11  f12
  grv      1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab      q    w    f    p    b    j    l    u    y    ;    [    ]    \\
  @ext     a    r    s    t    g    m    n    e    i    o    '    ret
  lsft       x    c    d    v    z    k    h    ,    .    /    rsft
  lctl     lmet lalt           spc            ralt rmet _    _
)

(deflayer extend
  _        play rewind previoussong nextsong ejectcd refresh brdn brup www mail prog1 prog2
  _        f1   f2   f3   f4   f5   f6   f7   f8   f9  f10   f11  f12  _
  @qwe     @sym @bk  @udo @fw  tab  pgup home up   end  menu [  prnt  @chm
  _        @lalt @lmet @lsft @lctl @rdo pgdn lft  down rght bspc  caps return
  @col       tab @cut  @cpy  @pst  pgdn  esc  del  comp lshft _  _
  _        _    _              @dwd            _    _    _    _
)

(deflayer symbols
  _        _    _    _    _    _    _    _    _    _    _    _    _    
  _        _    _    _    _    _    _    _    _    _    _    _    _    _
  _        _    grv    @exc    @star    _    _    [  -  ]     @at    _    _   _
  _        _    _    _    @pct    _    @dlr    @lpar    =    @rpar    @amp    _    _ 
  _        _    _    _    _    _    @hsh    @fwsl    _    _    _    _ 
  _        _    _              _              _    _    _    _
)
```
An issue I am having is that triggering the extend layer and then pressing @lsft along with any other key seems to trigger the colemak layer via @col. I'm not sure why this happens, but it makes working with a lot of my binds very difficult. 

Another issue is that triggering the extend layer (which is on the caps-lock key) sometimes also triggers caps-lock functionality, even though 'caps' is on a completely different key in the extend layer. 

Lastly, some windows programs (e.g., [fancywm](https://github.com/FancyWM/fancywm)), seem to not capture kmonad's inputs, but rather, the native window's inputs. When I try to use a keybind that I set in fancywm, for instance '@ext + @lmet + @lsft + home', it does not register in fancywm (as well as some other windows programs) as 'win + shift + home', but rather, 'caps + s + d + u'. 

I'm not sure whether these problems are user-error or something pertaining to windows, but if anyone could give me some assistance with this I'd appreciate it.

**Comment by ASong5** [comment]
I just realized I @'d some people by accident. Big apologies!

**Comment by jokesper** [comment]
for the first part, isn't that how you want it to be?
You specified the `@col` in the extend layer on the `lsft` key.

The third issue maybe has something to do with how we get windows key events (and maybe other software doing the same?).

But I neither know the windows part of the KMonad codebase nor how key events are handled internally in windows.

**Comment by ASong5** [comment]
> You specified the `@col` in the extend layer on the `lsft` key.

`@col` is on the `lsft` key on the physical keyboard, yes, but I was referring to the `@lsft` alias which is located on the `d` key on a qwerty keyboard. 
![image](https://github.com/user-attachments/assets/92ec375e-fbda-475f-944f-518e03e7df2a)

**Comment by ASong5** [comment]
It seems possible that my third issue is related to keyboard events that use the win+shift key combination on Windows. The issue referenced above outlines a similar problem but with AHK instead of kmonad. My guess is there underlying mechanism or low-level hook that is used by kmonad to send keyboard events may be responsible for this problem, but I am not sure.

**Comment by jokesper** [comment]
Oh sorry my mistake,
this would imply that KMonad is reacting on itself.
Could you maybe send the logging output of KMonad in debug mode (`-d` I think).
I.e. start KMonad in debug trigger the bug and then copy said output (probably good to stop KMonad before)

**Comment by ASong5** [comment]
> Oh sorry my mistake, this would imply that KMonad is reacting on itself. Could you maybe send the logging output of KMonad in debug mode (`-d` I think). I.e. start KMonad in debug trigger the bug and then copy said output (probably good to stop KMonad before)

```
Opening KeySink
Initializing Windows key sink
Opening KeySource
Registering low-level Windows keyboard hook
Launching process: emitter_proc

--------------------------------------------------------------------------------
Received event: Press <caps>
Running hooks
Pushed layer to stack: extend
 1. extend
Base-layer: qwerty

Registering untimed hook: 1

--------------------------------------------------------------------------------
Received event: Press <s>
Running hooks
Registering untimed hook: 2
Registering untimed hook: 3
Registering untimed hook: 4

--------------------------------------------------------------------------------
Received event: Press <d>
Running hooks
Registering untimed hook: 5
Registering untimed hook: 6
Emitting: Press <met>
Injecting event: Press <d>
Registering untimed hook: 7

--------------------------------------------------------------------------------
Rerunning event: Press <d>
Running hooks
Registering untimed hook: 8
Registering untimed hook: 9
Registering untimed hook: 10
Registering untimed hook: 11
Registering untimed hook: 12

--------------------------------------------------------------------------------
Received event: Press <j>
Running hooks
Registering untimed hook: 13
Registering untimed hook: 14
Registering untimed hook: 15
Registering untimed hook: 16
Emitting: Press <sft>
Injecting event: Press <j>
Registering untimed hook: 17

--------------------------------------------------------------------------------
Rerunning event: Press <j>
Running hooks
Registering untimed hook: 18
Registering untimed hook: 19
Registering untimed hook: 20
Registering untimed hook: 21
Registering untimed hook: 22
Registering untimed hook: 23
Emitting: Press <lft>

--------------------------------------------------------------------------------
Received event: Release <sft>
Running hooks
Registering untimed hook: 24
Registering untimed hook: 25
Registering untimed hook: 26
Registering untimed hook: 27
Registering untimed hook: 28
Registering untimed hook: 29

--------------------------------------------------------------------------------
Received event: Press <sft>
Running hooks
Registering untimed hook: 30
Registering untimed hook: 31
Registering untimed hook: 32
Registering untimed hook: 33
Registering untimed hook: 34
Registering untimed hook: 35
Set base layer to: colemak-dh
 1. extend
Base-layer: colemak-dh

Registering untimed hook: 36

--------------------------------------------------------------------------------
Received event: Release <j>
Running hooks
Registering untimed hook: 37
Registering untimed hook: 38
Registering untimed hook: 39
Registering untimed hook: 40
Emitting: Release <lft>
Registering untimed hook: 41
Registering untimed hook: 42

--------------------------------------------------------------------------------
Received event: Release <sft>
Running hooks
Registering untimed hook: 43
Registering untimed hook: 44
Registering untimed hook: 45
Registering untimed hook: 46
Registering untimed hook: 47

--------------------------------------------------------------------------------
Received event: Press <sft>
Running hooks
Registering untimed hook: 48
Registering untimed hook: 49
Registering untimed hook: 50
Registering untimed hook: 51
Registering untimed hook: 52
Set base layer to: colemak-dh
 1. extend
Base-layer: colemak-dh

Registering untimed hook: 53

--------------------------------------------------------------------------------
Received event: Release <s>
Running hooks
Registering untimed hook: 54
Registering untimed hook: 55
Registering untimed hook: 56
Registering untimed hook: 57
Emitting: Release <met>

--------------------------------------------------------------------------------
Received event: Release <caps>
Running hooks
Registering untimed hook: 58
Registering untimed hook: 59
Popped layer from stack: extend
Base-layer: colemak-dh

Registering untimed hook: 60

--------------------------------------------------------------------------------
Received event: Release <d>
Running hooks
Registering untimed hook: 61
Emitting: Release <sft>
```

This is the log after pressing `caps + s + d + j` on my keyboard, which should map to `@ext + @met/@win + @lsft + @lft`. 
If I am interpreting this correctly, it seems like the emitted keys are completely wrong based on the received event. `s` should emit `met/win`, `d` should emit `lsft` and `j` should emit `lft`. The order of the emitted keys seems mixed up given the input. It does seem like they get corrected later in the log, but I feel like this isn't quite right; though, again, I may be completely misinterpreting this. Thoughts?

**Comment by ASong5** [comment]
I'm wondering if this may also be a related issue https://github.com/kmonad/kmonad/issues/153

**Comment by jokesper** [comment]
> If I am interpreting this correctly, it seems like the emitted keys are completely wrong based on the received event.

No, `sticky-key` presses the key only as soon as the next is pressed. So everything is just as expected. What is broken is the Release <sft> and Press <sft> after every press of `j`.
Maybe it has something todo with your second problem:
I.e. Caps lock is providing a permanent shift press and `j` which causes `lft` arrow key should be unshifted since shift+arrows is for highlighting.

Does this also happen for other keys?

Though in general I won't be of much help in this area, as I am neither familiar with the Windows part, how windows handles such things, have access to a windows machine for testing or C.

**Comment by ASong5** [comment]
> No, `sticky-key` presses the key only as soon as the next is pressed. So everything is just as expected.

Ah, I somehow forgot those were set to sticky keys lol - seems my recent lack of sleep is getting to me... 

But yes, the issue is present when using keys other than `j` as well. Also, regarding the third problem, it seems no debug logs are generated at all when certain apps/windows are in focus, e.g., fancywm or the native Windows shortcut editor interface. This leads me to believe that certain apps can circumvent or override key events emitted by kmonad, which is quite strange as I was under the impression that kmonad used native low-level Windows hooks to proc key events which would look no different to any program that tried to capture keyboard presses. I'm not very well-versed in Windows either, so I don't know whether there are different implementations of these hooks or if these programs are able to manually override certain syscalls which may lead to this behaviour.

As far as 'needing' to get this to work: I'm a little too stubborn/rigid in wanting complete uniformity wrt. keyboard functionality across my Linux install and Windows, so this not working means I probably just won't be using a tiling window manager on Windows, as setting up and using binds different to the ones I use in Linux seems like more of a hassle than its worth.

> If you really need this to work I heard [Kanata](https://github.com/jtroo/kanata) is a similar project

For a similar reason to above, I probably won't use Kanata only because it adds on another set of configs that I'd need to manage for a set of functionalities that kmonad is already responsible for; my OCD and loyalty to kmonad is too strong to allow me to use Kanata lol. I will take a look at it, however, since it does seem interesting from a project standpoint, so thanks for bringing it up.

**Comment by jokesper** [comment]
> But yes, the issue is present when using keys other than j as well

Hmm now I am out of ideas.

> This leads me to believe that certain apps can circumvent or override key events emitted by kmonad

I don't know exactly what permissions KMonad is using but in general I would say anything that has the same permissions can do the same. I.e. if KMonad under Windows requires Admin privileges, most likely those are needed to do the same. If not then probably not as well.
Taking linux as an example: most programs don't expect to have the privileges of grabbing input devices and therefore don't use it even if they could (`input` / `uinput` group) and sometimes they just cannot (KMonad running as `root`).
So it isn't impossible that something like a custom window manager wants to also take low level input devices.

> [...] I probably won't use Kanata only because it adds on another set of configs [...]

I think Kanata was created as a kind of reimplementation due to missing features and has now growing into a slightly different direction.
Though from what I could see in your config you don't use many of KMonad's features so it could be possible to use Kanata as a drop in replacement (not intended & I never used Kanata).

Am I correct in assuming that issues 1 and 2 are independent of whether you use the default Windows DE?

**Comment by ASong5** [comment]
> Am I correct in assuming that issues 1 and 2 are independent of whether you use the default Windows DE?

Yes, that is correct. 

And yeah, I'm reading through some of the kanata configs and they look quite similar syntactically to kmonad. It definitely won't be difficult configuring kanata to match my kmonad config, but I'm quite OCD about having as much 1-1 transfer among programs/configs between the two operating systems as possible (I know this isn't realistic, but I'm trying my best to do so regardless lol), especially for day-to-day productivity use-cases like typing and keyboard management. Having a tiling manager with 1-1 keybinds is also quite important in that use-case hierarchy, but I don't code or do anything productivity related on Windows anyways, so I suppose I can live without a WM.

I will definitely use it as a drop-in replacement, like you said, if I get desperate enough though.

**Comment by jokesper** [comment]
Hmmm after having read a bit through the Windows code I still cannot find the issue(s).
I doubt that we get key repeat events when listening for `WH_KEYBOARD_LL`.
For the second and third issue I can only assume something also registers those hooks but instead they sit before KMonad.

For the other two issues I have some further questions:
1. Are you able to trigger caps lock via the remapped button (`'` in `extend`) when caps toggles when switching layers?
2. When you use a empty config (i.e. one layer with only fallthrough\*) and enable logging (`-l debug`) what happens with a slightly varied sequence (`Pcaps Tlft Rcaps`)?
3. Does the first issue also happen with other keyboards? (probably)

\* like this:
```clojure
(defcfg
	input (low-level-hook)
	output (send-event-sink)
	fallthrough true
)
(defsrc)
(deflayer empty)
```

**Comment by ASong5** [comment]
> Are you able to trigger caps lock via the remapped button (' in extend) when caps toggles when switching layers?

So the issue of caps-lock triggering issue occurs quite sporadically. I've been testing for a good 5 minutes now trying to get it to happen again but it hasn't. There is a good chance that restarting my pc since yesterday possibly fixed it, but I will keep monitoring the issue.

> When you use a empty config (i.e. one layer with only fallthrough*) and enable logging (-l debug) what happens with a slightly varied sequence (Pcaps Tlft Rcaps)?

Sorry I'm unfamiliar what the P, T, R prefixes are in this context (modifiers?) If you could elaborate on that I will send the debug log ASAP.

> Does the first issue also happen with other keyboards? (probably)

Unfortunately I don't have another keyboard or laptop to test this on, but I'm going to agree and say "probably".

**Comment by jokesper** [comment]
Hmmm...
The P, T and R prefixes stand for press tap and release respectively with:
`Pa` being a press of a
`Ra` it's release
and `Ta` a short form of `Pa Ra`
commonly we write after the prefix the button or aliases with `@` in this case I'm referring to your source mapping.
So your original debug logs would suggest that you pressed:
`Pcaps Ps Pd Pj Rsft Psft Rj Rsft Psft Rs Rcaps Rd`
with the bug beeing with the extra `Rsft Psft` (wrong order for `Tsft`) after the `j`s.
and it resulted in
`Pmet Psft Tlft Rmet Rsft` (layer changes left out for brevity).

So I was asking for a tap of `a` while `caps` is held.

Someday I may add an FAQ entry to link to in issues.

Feel free to report on the other two questions when / if you can. Also there is no time pressure here ;)

**Comment by ASong5** [comment]
Ah yes, I recall those prefixes being used in the docs/configuration guide, though it's been a while since I've read them :p

Anyways, I bit the bullet and did some digging on kanata. Transferring my kmonad config over was basically 1-1 outside of `sticky-keys` -> `one-shot` and a couple keycodes. 

In the kanata repo, there are a bunch of resources relating to my specific issue. After a bit of reading, it basically came down to the fact that Windows exposes a user-level hook whereas Linux exposes a kernal-level hook for keyboard event processing. The implications of this for Windows are that many applications (like fancywm, espanso, barrier, some native windows tools, or most elevated privilege apps) either directly (WH_KEYBOARD_LL hook is triggered ***after*** the remap is performed) or indirectly override/filter out injected events propagated via ```SendInput``` from applications like kmonad. Not sure if I explained this well/correctly, so feel free to read what kanata's author says on the matter: https://github.com/jtroo/kanata/issues/152#issuecomment-1278332233

Kanata has binary releases that employ [an interception driver](https://github.com/oblitum/Interception) rather than higher-level Window's hooks. Using that fixes issue 3 for me.

Issue 1 is also resolved, but I'm not sure how or why. I'd need to dig into their codebase, but I don't really have the energy or time.

Issue 2 seems more or less resolved, seems like it was a one-off.

Appreciate you sticking with me for these issues. Gonna play around more with kanata for the time being (haven't tested other functionality extensively) as its far more conducive to my specific use-case. Oh, they also have chord-combos, which is something I've been wanting for a while (not sure if kmonad has implemented them yet). 

Not sure where additional Windows support is on the roadmap for kmonad, but whenever you guys get to it hopefully this issue can be of some use.

Thanks again

**Comment by jokesper** [comment]
Ahh, maybe we could use the same interception method.

Though I would probably leave the issue open, since it's still a bug (that can even be fixed as seen in Kanata).

Glad I could help

**Comment by ASong5** [comment]
Ah good point. I've re-opened the issue. Thanks again.
