### ISSUE TITLE
No Output from KMonad on macOS (Connected but No Key Events Emitted)

### ISSUE THREAD

**Issue by randoman14** [kmonad/kmonad#905]
I am encountering an issue where KMonad is connected to my keyboard on macOS but does not output any key events. The debug logs show that key presses are being detected, but no output is emitted.

Use KMonad with the following configuration on macOS:

Input: Apple Internal Keyboard / Trackpad

Output: Kext

Run KMonad using the command:

sudo kmonad mac-homie.kbd -l debug

KMonad successfully connects and detects key presses but does not emit key events.

While KMonad successfully connects and detects key presses, no output is produced 

Debug Output
Running KMonad in debug mode shows the following output when pressing the j key:

--------------------------------------------------------------------------------
Received event: Press <j>
Running hooks
Registering untimed hook: 1
Emitting: Press <j>

--------------------------------------------------------------------------------
Received event: Release <j>
Running hooks
Emitting: Release <j>
Despite this, no key events are actually emitted.

System Info
macOS Version: macOS 14.6 
arm64
KMonad Version: 0.4.3
Keyboard: Apple Internal Keyboard / Trackpad

**Comment by randoman14** [comment]
Here is the config file
#| --------------------------------------------------------------------------
                          KMonad Configuration for macOS
  A simple KMonad configuration with a basic QWERTY layout.
--------------------------------------------------------------------------- |#

(defcfg
  ;; Input device configuration for Mac
  input (iokit-name "Apple Internal Keyboard / Trackpad")  ;; Ensure this matches your keyboard name
  output (kext)  ;; Output using kext for macOS

  fallthrough true         ;; Allow unhandled events to pass through
  allow-cmd true           ;; Enable command execution
  implicit-around around    ;; Set the implicit around behavior
)

#| --------------------------------------------------------------------------
                       Source Definition
  A simplified source layout for basic key mapping.
--------------------------------------------------------------------------- |#

(defsrc
  grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab  q    w    e    r    t    y    u    i    o    p    [    ]    \
  caps a    s    d    f    g    h    j    k    l    ;    '    ret
)

#| --------------------------------------------------------------------------
                        QWERTY Layer Definition
  A simplified QWERTY layer.
--------------------------------------------------------------------------- |#

(deflayer qwerty
  grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab  q    w    e    r    t    y    u    i    o    p    [    ]    \
  caps a    s    d    f    g    h    j    k    l    ;    '    ret
)

#| --------------------------------------------------------------------------
                       Optional: Alias Example
  Here we define an alias that could be used later.
--------------------------------------------------------------------------- |#

(defalias
  num (layer-toggle qwerty) ;; Toggle to the QWERTY layer
)

**Comment by randoman14** [comment]
Im using a macbook pro sonoma 14.7

and when I download it and try to install its not compatible with newer versions of mac.

**Comment by ALPHAvibe** [comment]
@randoman14 I am on Sonoma 14.6.1. Just had similar issues. Had to restart my Mac before emitted events started to be handled. Did this after verifying I was on the correct for version 3.1.0 (was on 5.0.0). I also had karabiner Elements installed which I had to uninstall.

**Comment by Jsonbourne-dev** [comment]
@ALPHAvibe Interesting I have the correct version 3.1.0 it was (5.0.0) but I still have karabiner elements installed so ill try uninstall and restart my mac and see if that solves it thanks!

**Comment by derrik-fleming** [comment]
@randoman14 @Jsonbourne-dev did you end up resolving this? I ran into the same thing when upgrading to 0.4.3.

I found that if I use 0.4.2 and kext specifically that it works.

**Comment by randoman14** [comment]
@derrik-fleming yeah I got it resolved all I had to do was uninstall karabiner-elements, and made sure I had the correct version 3.1.0.
